{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "mtcilsim.serviceAccountName" . }}
  labels:
{{ include "mtcilsim.labels" . | indent 4 }}
{{- end -}}
