{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "bccsim.serviceAccountName" . }}
  labels:
{{ include "bccsim.labels" . | indent 4 }}
{{- end -}}
