apiVersion: v1
kind: Service
metadata:
  name: {{.Values.componentSpec.deployment.container.service}}
  labels:
    app: simuctl
spec:
  ports:
  - port: 8765
    targetPort: 8765
    name: simuctl
  selector:
    app: simuctl
