apiVersion: apps/v1
kind: Deployment
metadata:
  name: simucucp
  namespace: default
  # annotations:
  #       k8s.v1.cni.cncf.io/networks: cuup-macvlan-e1, macvlan-conf-1
spec:
  replicas: 1
  selector:
          matchLabels:
                  app: simucucp
  template:
          metadata:
                  labels:
                          app: simucucp
          spec:
              initContainers:
                  - name: init-nats-server
                    image: busybox:latest
                    command: ['sh', '-c', 'until nslookup myetcd; do echo waiting for etcd server; sleep 2; done;']
              containers:
                  - name: {{.Values.componentSpec.deployment.container.image}}
                    imagePullPolicy: Always
                    image: {{ .Values.global.hub }}/{{.Values.componentSpec.deployment.container.image}}:{{.Values.componentSpec.deployment.container.tag}}
                    command: ["./simucucp"]
                    imagePullPolicy: IfNotPresent
                    securityContext:
                        capabilities:
                         add:
                           - NET_ADMIN
                    restartPolicy: OnFailure
