apiVersion: v1
kind: Service
metadata:
        name: simucucp-service-nodeport
spec:
        selector:
                app: simucucp
        ports:
                - name: sctp
                  port: 38462
                  protocol: TCP
                  targetPort: 38462
        type: NodePort
