apiVersion: v1
kind: Service
metadata:
        name: {{.Values.componentSpec.deployment.container.service}}
spec:
        selector:
                app: simucucp
        ports:
                - name: sctp
                  port: 38462
                  protocol: TCP
                  targetPort: 38462
        type: NodePort
