/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_ActivityNotificationLevel_H_
#define	_ActivityNotificationLevel_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ActivityNotificationLevel {
	ActivityNotificationLevel_drb	= 0,
	ActivityNotificationLevel_pdu_session	= 1,
	ActivityNotificationLevel_ue	= 2
	/*
	 * Enumeration is extensible
	 */
} e_ActivityNotificationLevel;

/* ActivityNotificationLevel */
typedef long	 ActivityNotificationLevel_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ActivityNotificationLevel_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ActivityNotificationLevel;
extern const asn_INTEGER_specifics_t asn_SPC_ActivityNotificationLevel_specs_1;
asn_struct_free_f ActivityNotificationLevel_free;
asn_struct_print_f ActivityNotificationLevel_print;
asn_constr_check_f ActivityNotificationLevel_constraint;
ber_type_decoder_f ActivityNotificationLevel_decode_ber;
der_type_encoder_f ActivityNotificationLevel_encode_der;
xer_type_decoder_f ActivityNotificationLevel_decode_xer;
xer_type_encoder_f ActivityNotificationLevel_encode_xer;
oer_type_decoder_f ActivityNotificationLevel_decode_oer;
oer_type_encoder_f ActivityNotificationLevel_encode_oer;
per_type_decoder_f ActivityNotificationLevel_decode_uper;
per_type_encoder_f ActivityNotificationLevel_encode_uper;
per_type_decoder_f ActivityNotificationLevel_decode_aper;
per_type_encoder_f ActivityNotificationLevel_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ActivityNotificationLevel_H_ */
#include <asn_internal.h>
