/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_ActivityInformation_H_
#define	_ActivityInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UE-Activity.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ActivityInformation_PR {
	ActivityInformation_PR_NOTHING,	/* No components present */
	ActivityInformation_PR_dRB_Activity_List,
	ActivityInformation_PR_pDU_Session_Resource_Activity_List,
	ActivityInformation_PR_uE_Activity,
	ActivityInformation_PR_choice_extension
} ActivityInformation_PR;

/* Forward declarations */
struct DRB_Activity_List;
struct PDU_Session_Resource_Activity_List;
struct ProtocolIE_SingleContainer;

/* ActivityInformation */
typedef struct ActivityInformation {
	ActivityInformation_PR present;
	union ActivityInformation_u {
		struct DRB_Activity_List	*dRB_Activity_List;
		struct PDU_Session_Resource_Activity_List	*pDU_Session_Resource_Activity_List;
		UE_Activity_t	 uE_Activity;
		struct ProtocolIE_SingleContainer	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ActivityInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ActivityInformation;
extern asn_CHOICE_specifics_t asn_SPC_ActivityInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_ActivityInformation_1[4];
extern asn_per_constraints_t asn_PER_type_ActivityInformation_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ActivityInformation_H_ */
#include <asn_internal.h>
