/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

#ifndef _ASN_CONSTANT_H
#define _ASN_CONSTANT_H

#ifdef __cplusplus
extern "C" {
#endif

#define maxPrivateIEs (65535)
#define maxProtocolExtensions (65535)
#define maxProtocolIEs (65535)
#define maxnoofErrors (256)
#define maxnoofSPLMNs (12)
#define maxnoofSliceItems (1024)
#define maxnoofIndividualE1ConnectionsToReset (65536)
#define maxnoofEUTRANQOSParameters (256)
#define maxnoofNGRANQOSParameters (256)
#define maxnoofDRBs (32)
#define maxnoofNRCGI (512)
#define maxnoofPDUSessionResource (256)
#define maxnoofQoSFlows (64)
#define maxnoofUPParameters (8)
#define maxnoofCellGroups (4)
#define maxnooftimeperiods (2)
#define maxnoofTNLAssociations (32)


#ifdef __cplusplus
}
#endif

#endif /* _ASN_CONSTANT_H */
