/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_BearerContextStatusChange_H_
#define	_BearerContextStatusChange_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum BearerContextStatusChange {
	BearerContextStatusChange_suspend	= 0,
	BearerContextStatusChange_resume	= 1
	/*
	 * Enumeration is extensible
	 */
} e_BearerContextStatusChange;

/* BearerContextStatusChange */
typedef long	 BearerContextStatusChange_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_BearerContextStatusChange_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_BearerContextStatusChange;
extern const asn_INTEGER_specifics_t asn_SPC_BearerContextStatusChange_specs_1;
asn_struct_free_f BearerContextStatusChange_free;
asn_struct_print_f BearerContextStatusChange_print;
asn_constr_check_f BearerContextStatusChange_constraint;
ber_type_decoder_f BearerContextStatusChange_decode_ber;
der_type_encoder_f BearerContextStatusChange_encode_der;
xer_type_decoder_f BearerContextStatusChange_decode_xer;
xer_type_encoder_f BearerContextStatusChange_encode_xer;
oer_type_decoder_f BearerContextStatusChange_decode_oer;
oer_type_encoder_f BearerContextStatusChange_encode_oer;
per_type_decoder_f BearerContextStatusChange_decode_uper;
per_type_encoder_f BearerContextStatusChange_encode_uper;
per_type_decoder_f BearerContextStatusChange_decode_aper;
per_type_encoder_f BearerContextStatusChange_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _BearerContextStatusChange_H_ */
#include <asn_internal.h>
