/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#include "Cell-Group-Information-Item.h"

#include "ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_Cell_Group_Information_Item_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Cell_Group_Information_Item, cell_Group_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Cell_Group_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cell-Group-ID"
		},
	{ ATF_POINTER, 4, offsetof(struct Cell_Group_Information_Item, uL_Configuration),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UL_Configuration,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uL-Configuration"
		},
	{ ATF_POINTER, 3, offsetof(struct Cell_Group_Information_Item, dL_TX_Stop),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DL_TX_Stop,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dL-TX-Stop"
		},
	{ ATF_POINTER, 2, offsetof(struct Cell_Group_Information_Item, rAT_Type),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RAT_Type,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rAT-Type"
		},
	{ ATF_POINTER, 1, offsetof(struct Cell_Group_Information_Item, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_128P0,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_Cell_Group_Information_Item_oms_1[] = { 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_Cell_Group_Information_Item_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Cell_Group_Information_Item_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* cell-Group-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* uL-Configuration */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* dL-TX-Stop */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* rAT-Type */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_Cell_Group_Information_Item_specs_1 = {
	sizeof(struct Cell_Group_Information_Item),
	offsetof(struct Cell_Group_Information_Item, _asn_ctx),
	asn_MAP_Cell_Group_Information_Item_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_Cell_Group_Information_Item_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Cell_Group_Information_Item = {
	"Cell-Group-Information-Item",
	"Cell-Group-Information-Item",
	&asn_OP_SEQUENCE,
	asn_DEF_Cell_Group_Information_Item_tags_1,
	sizeof(asn_DEF_Cell_Group_Information_Item_tags_1)
		/sizeof(asn_DEF_Cell_Group_Information_Item_tags_1[0]), /* 1 */
	asn_DEF_Cell_Group_Information_Item_tags_1,	/* Same as above */
	sizeof(asn_DEF_Cell_Group_Information_Item_tags_1)
		/sizeof(asn_DEF_Cell_Group_Information_Item_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Cell_Group_Information_Item_1,
	5,	/* Elements count */
	&asn_SPC_Cell_Group_Information_Item_specs_1	/* Additional specs */
};

