/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_Cell_Group_Information_H_
#define	_Cell_Group_Information_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Cell_Group_Information_Item;

/* Cell-Group-Information */
typedef struct Cell_Group_Information {
	A_SEQUENCE_OF(struct Cell_Group_Information_Item) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Cell_Group_Information_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Cell_Group_Information;
extern asn_SET_OF_specifics_t asn_SPC_Cell_Group_Information_specs_1;
extern asn_TYPE_member_t asn_MBR_Cell_Group_Information_1[1];
extern asn_per_constraints_t asn_PER_type_Cell_Group_Information_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Cell_Group_Information_H_ */
#include <asn_internal.h>
