/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_DataDiscardRequired_H_
#define	_DataDiscardRequired_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum DataDiscardRequired {
	DataDiscardRequired_required	= 0
	/*
	 * Enumeration is extensible
	 */
} e_DataDiscardRequired;

/* DataDiscardRequired */
typedef long	 DataDiscardRequired_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_DataDiscardRequired_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_DataDiscardRequired;
extern const asn_INTEGER_specifics_t asn_SPC_DataDiscardRequired_specs_1;
asn_struct_free_f DataDiscardRequired_free;
asn_struct_print_f DataDiscardRequired_print;
asn_constr_check_f DataDiscardRequired_constraint;
ber_type_decoder_f DataDiscardRequired_decode_ber;
der_type_encoder_f DataDiscardRequired_encode_der;
xer_type_decoder_f DataDiscardRequired_decode_xer;
xer_type_encoder_f DataDiscardRequired_encode_xer;
oer_type_decoder_f DataDiscardRequired_decode_oer;
oer_type_encoder_f DataDiscardRequired_encode_oer;
per_type_decoder_f DataDiscardRequired_decode_uper;
per_type_encoder_f DataDiscardRequired_encode_uper;
per_type_decoder_f DataDiscardRequired_decode_aper;
per_type_encoder_f DataDiscardRequired_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _DataDiscardRequired_H_ */
#include <asn_internal.h>
