/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#include "Data-Forwarding-Information.h"

#include "UP-TNL-Information.h"
#include "ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_Data_Forwarding_Information_1[] = {
	{ ATF_POINTER, 3, offsetof(struct Data_Forwarding_Information, uL_Data_Forwarding),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UP_TNL_Information,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uL-Data-Forwarding"
		},
	{ ATF_POINTER, 2, offsetof(struct Data_Forwarding_Information, dL_Data_Forwarding),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UP_TNL_Information,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dL-Data-Forwarding"
		},
	{ ATF_POINTER, 1, offsetof(struct Data_Forwarding_Information, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_128P4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_Data_Forwarding_Information_oms_1[] = { 0, 1, 2 };
static const ber_tlv_tag_t asn_DEF_Data_Forwarding_Information_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Data_Forwarding_Information_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* uL-Data-Forwarding */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* dL-Data-Forwarding */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_Data_Forwarding_Information_specs_1 = {
	sizeof(struct Data_Forwarding_Information),
	offsetof(struct Data_Forwarding_Information, _asn_ctx),
	asn_MAP_Data_Forwarding_Information_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_Data_Forwarding_Information_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Data_Forwarding_Information = {
	"Data-Forwarding-Information",
	"Data-Forwarding-Information",
	&asn_OP_SEQUENCE,
	asn_DEF_Data_Forwarding_Information_tags_1,
	sizeof(asn_DEF_Data_Forwarding_Information_tags_1)
		/sizeof(asn_DEF_Data_Forwarding_Information_tags_1[0]), /* 1 */
	asn_DEF_Data_Forwarding_Information_tags_1,	/* Same as above */
	sizeof(asn_DEF_Data_Forwarding_Information_tags_1)
		/sizeof(asn_DEF_Data_Forwarding_Information_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Data_Forwarding_Information_1,
	3,	/* Elements count */
	&asn_SPC_Data_Forwarding_Information_specs_1	/* Additional specs */
};

