/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#include "Data-Usage-Report-Item.h"

#include "ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_Data_Usage_Report_Item_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Data_Usage_Report_Item, dRB_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DRB_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dRB-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data_Usage_Report_Item, rAT_Type),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RAT_Type,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rAT-Type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Data_Usage_Report_Item, dRB_Usage_Report_List),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DRB_Usage_Report_List,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dRB-Usage-Report-List"
		},
	{ ATF_POINTER, 1, offsetof(struct Data_Usage_Report_Item, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_128P7,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_Data_Usage_Report_Item_oms_1[] = { 3 };
static const ber_tlv_tag_t asn_DEF_Data_Usage_Report_Item_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Data_Usage_Report_Item_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* dRB-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* rAT-Type */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* dRB-Usage-Report-List */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_Data_Usage_Report_Item_specs_1 = {
	sizeof(struct Data_Usage_Report_Item),
	offsetof(struct Data_Usage_Report_Item, _asn_ctx),
	asn_MAP_Data_Usage_Report_Item_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_Data_Usage_Report_Item_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Data_Usage_Report_Item = {
	"Data-Usage-Report-Item",
	"Data-Usage-Report-Item",
	&asn_OP_SEQUENCE,
	asn_DEF_Data_Usage_Report_Item_tags_1,
	sizeof(asn_DEF_Data_Usage_Report_Item_tags_1)
		/sizeof(asn_DEF_Data_Usage_Report_Item_tags_1[0]), /* 1 */
	asn_DEF_Data_Usage_Report_Item_tags_1,	/* Same as above */
	sizeof(asn_DEF_Data_Usage_Report_Item_tags_1)
		/sizeof(asn_DEF_Data_Usage_Report_Item_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Data_Usage_Report_Item_1,
	4,	/* Elements count */
	&asn_SPC_Data_Usage_Report_Item_specs_1	/* Additional specs */
};

