/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_Data_Usage_Report_List_H_
#define	_Data_Usage_Report_List_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Data_Usage_Report_Item;

/* Data-Usage-Report-List */
typedef struct Data_Usage_Report_List {
	A_SEQUENCE_OF(struct Data_Usage_Report_Item) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Data_Usage_Report_List_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Data_Usage_Report_List;
extern asn_SET_OF_specifics_t asn_SPC_Data_Usage_Report_List_specs_1;
extern asn_TYPE_member_t asn_MBR_Data_Usage_Report_List_1[1];
extern asn_per_constraints_t asn_PER_type_Data_Usage_Report_List_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Data_Usage_Report_List_H_ */
#include <asn_internal.h>
