/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_Data_Forwarding_Request_H_
#define	_Data_Forwarding_Request_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Data_Forwarding_Request {
	Data_Forwarding_Request_uL	= 0,
	Data_Forwarding_Request_dL	= 1,
	Data_Forwarding_Request_both	= 2
	/*
	 * Enumeration is extensible
	 */
} e_Data_Forwarding_Request;

/* Data-Forwarding-Request */
typedef long	 Data_Forwarding_Request_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Data_Forwarding_Request_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Data_Forwarding_Request;
extern const asn_INTEGER_specifics_t asn_SPC_Data_Forwarding_Request_specs_1;
asn_struct_free_f Data_Forwarding_Request_free;
asn_struct_print_f Data_Forwarding_Request_print;
asn_constr_check_f Data_Forwarding_Request_constraint;
ber_type_decoder_f Data_Forwarding_Request_decode_ber;
der_type_encoder_f Data_Forwarding_Request_encode_der;
xer_type_decoder_f Data_Forwarding_Request_decode_xer;
xer_type_encoder_f Data_Forwarding_Request_encode_xer;
oer_type_decoder_f Data_Forwarding_Request_decode_oer;
oer_type_encoder_f Data_Forwarding_Request_encode_oer;
per_type_decoder_f Data_Forwarding_Request_decode_uper;
per_type_encoder_f Data_Forwarding_Request_encode_uper;
per_type_decoder_f Data_Forwarding_Request_decode_aper;
per_type_encoder_f Data_Forwarding_Request_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Data_Forwarding_Request_H_ */
#include <asn_internal.h>
