/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#include "DRB-Setup-Mod-Item-NG-RAN.h"

#include "Data-Forwarding-Information.h"
#include "QoS-Flow-Failed-List.h"
#include "ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_DRB_Setup_Mod_Item_NG_RAN_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DRB_Setup_Mod_Item_NG_RAN, dRB_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DRB_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dRB-ID"
		},
	{ ATF_POINTER, 1, offsetof(struct DRB_Setup_Mod_Item_NG_RAN, dRB_data_Forwarding_Information_Response),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Data_Forwarding_Information,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dRB-data-Forwarding-Information-Response"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DRB_Setup_Mod_Item_NG_RAN, uL_UP_Transport_Parameters),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UP_Parameters,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uL-UP-Transport-Parameters"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct DRB_Setup_Mod_Item_NG_RAN, flow_Setup_List),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_QoS_Flow_List,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"flow-Setup-List"
		},
	{ ATF_POINTER, 2, offsetof(struct DRB_Setup_Mod_Item_NG_RAN, flow_Failed_List),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_QoS_Flow_Failed_List,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"flow-Failed-List"
		},
	{ ATF_POINTER, 1, offsetof(struct DRB_Setup_Mod_Item_NG_RAN, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_128P24,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_DRB_Setup_Mod_Item_NG_RAN_oms_1[] = { 1, 4, 5 };
static const ber_tlv_tag_t asn_DEF_DRB_Setup_Mod_Item_NG_RAN_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DRB_Setup_Mod_Item_NG_RAN_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* dRB-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* dRB-data-Forwarding-Information-Response */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* uL-UP-Transport-Parameters */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* flow-Setup-List */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* flow-Failed-List */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_DRB_Setup_Mod_Item_NG_RAN_specs_1 = {
	sizeof(struct DRB_Setup_Mod_Item_NG_RAN),
	offsetof(struct DRB_Setup_Mod_Item_NG_RAN, _asn_ctx),
	asn_MAP_DRB_Setup_Mod_Item_NG_RAN_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_DRB_Setup_Mod_Item_NG_RAN_oms_1,	/* Optional members */
	3, 0,	/* Root/Additions */
	6,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_DRB_Setup_Mod_Item_NG_RAN = {
	"DRB-Setup-Mod-Item-NG-RAN",
	"DRB-Setup-Mod-Item-NG-RAN",
	&asn_OP_SEQUENCE,
	asn_DEF_DRB_Setup_Mod_Item_NG_RAN_tags_1,
	sizeof(asn_DEF_DRB_Setup_Mod_Item_NG_RAN_tags_1)
		/sizeof(asn_DEF_DRB_Setup_Mod_Item_NG_RAN_tags_1[0]), /* 1 */
	asn_DEF_DRB_Setup_Mod_Item_NG_RAN_tags_1,	/* Same as above */
	sizeof(asn_DEF_DRB_Setup_Mod_Item_NG_RAN_tags_1)
		/sizeof(asn_DEF_DRB_Setup_Mod_Item_NG_RAN_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_DRB_Setup_Mod_Item_NG_RAN_1,
	6,	/* Elements count */
	&asn_SPC_DRB_Setup_Mod_Item_NG_RAN_specs_1	/* Additional specs */
};

