/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_DRB_Required_To_Modify_Item_EUTRAN_H_
#define	_DRB_Required_To_Modify_Item_EUTRAN_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DRB-ID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct UP_TNL_Information;
struct GNB_CU_UP_CellGroupRelatedConfiguration;
struct Cause;
struct ProtocolExtensionContainer;

/* DRB-Required-To-Modify-Item-EUTRAN */
typedef struct DRB_Required_To_Modify_Item_EUTRAN {
	DRB_ID_t	 dRB_ID;
	struct UP_TNL_Information	*s1_DL_UP_TNL_Information;	/* OPTIONAL */
	struct GNB_CU_UP_CellGroupRelatedConfiguration	*gNB_CU_UP_CellGroupRelatedConfiguration;	/* OPTIONAL */
	struct Cause	*cause;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DRB_Required_To_Modify_Item_EUTRAN_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DRB_Required_To_Modify_Item_EUTRAN;
extern asn_SEQUENCE_specifics_t asn_SPC_DRB_Required_To_Modify_Item_EUTRAN_specs_1;
extern asn_TYPE_member_t asn_MBR_DRB_Required_To_Modify_Item_EUTRAN_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _DRB_Required_To_Modify_Item_EUTRAN_H_ */
#include <asn_internal.h>
