/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#include "DRB-Required-To-Modify-Item-NG-RAN.h"

#include "GNB-CU-UP-CellGroupRelatedConfiguration.h"
#include "QoS-Flow-List.h"
#include "Cause.h"
#include "ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_DRB_Required_To_Modify_Item_NG_RAN_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct DRB_Required_To_Modify_Item_NG_RAN, dRB_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DRB_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dRB-ID"
		},
	{ ATF_POINTER, 4, offsetof(struct DRB_Required_To_Modify_Item_NG_RAN, gNB_CU_UP_CellGroupRelatedConfiguration),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_GNB_CU_UP_CellGroupRelatedConfiguration,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"gNB-CU-UP-CellGroupRelatedConfiguration"
		},
	{ ATF_POINTER, 3, offsetof(struct DRB_Required_To_Modify_Item_NG_RAN, flow_To_Remove),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_QoS_Flow_List,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"flow-To-Remove"
		},
	{ ATF_POINTER, 2, offsetof(struct DRB_Required_To_Modify_Item_NG_RAN, cause),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Cause,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cause"
		},
	{ ATF_POINTER, 1, offsetof(struct DRB_Required_To_Modify_Item_NG_RAN, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_128P20,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_DRB_Required_To_Modify_Item_NG_RAN_oms_1[] = { 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_DRB_Required_To_Modify_Item_NG_RAN_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_DRB_Required_To_Modify_Item_NG_RAN_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* dRB-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* gNB-CU-UP-CellGroupRelatedConfiguration */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* flow-To-Remove */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* cause */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_DRB_Required_To_Modify_Item_NG_RAN_specs_1 = {
	sizeof(struct DRB_Required_To_Modify_Item_NG_RAN),
	offsetof(struct DRB_Required_To_Modify_Item_NG_RAN, _asn_ctx),
	asn_MAP_DRB_Required_To_Modify_Item_NG_RAN_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_DRB_Required_To_Modify_Item_NG_RAN_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_DRB_Required_To_Modify_Item_NG_RAN = {
	"DRB-Required-To-Modify-Item-NG-RAN",
	"DRB-Required-To-Modify-Item-NG-RAN",
	&asn_OP_SEQUENCE,
	asn_DEF_DRB_Required_To_Modify_Item_NG_RAN_tags_1,
	sizeof(asn_DEF_DRB_Required_To_Modify_Item_NG_RAN_tags_1)
		/sizeof(asn_DEF_DRB_Required_To_Modify_Item_NG_RAN_tags_1[0]), /* 1 */
	asn_DEF_DRB_Required_To_Modify_Item_NG_RAN_tags_1,	/* Same as above */
	sizeof(asn_DEF_DRB_Required_To_Modify_Item_NG_RAN_tags_1)
		/sizeof(asn_DEF_DRB_Required_To_Modify_Item_NG_RAN_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_DRB_Required_To_Modify_Item_NG_RAN_1,
	5,	/* Elements count */
	&asn_SPC_DRB_Required_To_Modify_Item_NG_RAN_specs_1	/* Additional specs */
};

