/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_DRB_Setup_Mod_Item_NG_RAN_H_
#define	_DRB_Setup_Mod_Item_NG_RAN_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DRB-ID.h"
#include "UP-Parameters.h"
#include "QoS-Flow-List.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Data_Forwarding_Information;
struct QoS_Flow_Failed_List;
struct ProtocolExtensionContainer;

/* DRB-Setup-Mod-Item-NG-RAN */
typedef struct DRB_Setup_Mod_Item_NG_RAN {
	DRB_ID_t	 dRB_ID;
	struct Data_Forwarding_Information	*dRB_data_Forwarding_Information_Response;	/* OPTIONAL */
	UP_Parameters_t	 uL_UP_Transport_Parameters;
	QoS_Flow_List_t	 flow_Setup_List;
	struct QoS_Flow_Failed_List	*flow_Failed_List;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DRB_Setup_Mod_Item_NG_RAN_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DRB_Setup_Mod_Item_NG_RAN;
extern asn_SEQUENCE_specifics_t asn_SPC_DRB_Setup_Mod_Item_NG_RAN_specs_1;
extern asn_TYPE_member_t asn_MBR_DRB_Setup_Mod_Item_NG_RAN_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _DRB_Setup_Mod_Item_NG_RAN_H_ */
#include <asn_internal.h>
