/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_DRB_To_Setup_Item_NG_RAN_H_
#define	_DRB_To_Setup_Item_NG_RAN_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DRB-ID.h"
#include "SDAP-Configuration.h"
#include "PDCP-Configuration.h"
#include "Cell-Group-Information.h"
#include "QoS-Flow-QoS-Parameter-List.h"
#include "Inactivity-Timer.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Data_Forwarding_Information_Request;
struct PDCP_SN_Status_Information;
struct ProtocolExtensionContainer;

/* DRB-To-Setup-Item-NG-RAN */
typedef struct DRB_To_Setup_Item_NG_RAN {
	DRB_ID_t	 dRB_ID;
	SDAP_Configuration_t	 sDAP_Configuration;
	PDCP_Configuration_t	 pDCP_Configuration;
	Cell_Group_Information_t	 cell_Group_Information;
	QoS_Flow_QoS_Parameter_List_t	 qos_flow_Information_To_Be_Setup;
	struct Data_Forwarding_Information_Request	*dRB_Data_Forwarding_Information_Request;	/* OPTIONAL */
	Inactivity_Timer_t	*dRB_Inactivity_Timer;	/* OPTIONAL */
	struct PDCP_SN_Status_Information	*pDCP_SN_Status_Information;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DRB_To_Setup_Item_NG_RAN_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DRB_To_Setup_Item_NG_RAN;
extern asn_SEQUENCE_specifics_t asn_SPC_DRB_To_Setup_Item_NG_RAN_specs_1;
extern asn_TYPE_member_t asn_MBR_DRB_To_Setup_Item_NG_RAN_1[9];

#ifdef __cplusplus
}
#endif

#endif	/* _DRB_To_Setup_Item_NG_RAN_H_ */
#include <asn_internal.h>
