/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_DRBBStatusTransfer_H_
#define	_DRBBStatusTransfer_H_


#include <asn_application.h>

/* Including external dependencies */
#include <BIT_STRING.h>
#include "PDCP-Count.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* DRBBStatusTransfer */
typedef struct DRBBStatusTransfer {
	BIT_STRING_t	*receiveStatusofPDCPSDU;	/* OPTIONAL */
	PDCP_Count_t	 countValue;
	struct ProtocolExtensionContainer	*iE_Extension;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DRBBStatusTransfer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DRBBStatusTransfer;
extern asn_SEQUENCE_specifics_t asn_SPC_DRBBStatusTransfer_specs_1;
extern asn_TYPE_member_t asn_MBR_DRBBStatusTransfer_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _DRBBStatusTransfer_H_ */
#include <asn_internal.h>
