/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_DRBs_Subject_To_Counter_Check_List_NG_RAN_H_
#define	_DRBs_Subject_To_Counter_Check_List_NG_RAN_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct DRBs_Subject_To_Counter_Check_Item_NG_RAN;

/* DRBs-Subject-To-Counter-Check-List-NG-RAN */
typedef struct DRBs_Subject_To_Counter_Check_List_NG_RAN {
	A_SEQUENCE_OF(struct DRBs_Subject_To_Counter_Check_Item_NG_RAN) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DRBs_Subject_To_Counter_Check_List_NG_RAN_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DRBs_Subject_To_Counter_Check_List_NG_RAN;
extern asn_SET_OF_specifics_t asn_SPC_DRBs_Subject_To_Counter_Check_List_NG_RAN_specs_1;
extern asn_TYPE_member_t asn_MBR_DRBs_Subject_To_Counter_Check_List_NG_RAN_1[1];
extern asn_per_constraints_t asn_PER_type_DRBs_Subject_To_Counter_Check_List_NG_RAN_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _DRBs_Subject_To_Counter_Check_List_NG_RAN_H_ */
#include <asn_internal.h>
