/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_Duplication_Activation_H_
#define	_Duplication_Activation_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Duplication_Activation {
	Duplication_Activation_active	= 0,
	Duplication_Activation_inactive	= 1
	/*
	 * Enumeration is extensible
	 */
} e_Duplication_Activation;

/* Duplication-Activation */
typedef long	 Duplication_Activation_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_Duplication_Activation_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_Duplication_Activation;
extern const asn_INTEGER_specifics_t asn_SPC_Duplication_Activation_specs_1;
asn_struct_free_f Duplication_Activation_free;
asn_struct_print_f Duplication_Activation_print;
asn_constr_check_f Duplication_Activation_constraint;
ber_type_decoder_f Duplication_Activation_decode_ber;
der_type_encoder_f Duplication_Activation_encode_der;
xer_type_decoder_f Duplication_Activation_decode_xer;
xer_type_encoder_f Duplication_Activation_encode_xer;
oer_type_decoder_f Duplication_Activation_decode_oer;
oer_type_encoder_f Duplication_Activation_encode_oer;
per_type_decoder_f Duplication_Activation_decode_uper;
per_type_encoder_f Duplication_Activation_encode_uper;
per_type_decoder_f Duplication_Activation_decode_aper;
per_type_encoder_f Duplication_Activation_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _Duplication_Activation_H_ */
#include <asn_internal.h>
