/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#include "GNB-CU-UP-CellGroupRelatedConfiguration-Item.h"

#include "ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_GNB_CU_UP_CellGroupRelatedConfiguration_Item_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct GNB_CU_UP_CellGroupRelatedConfiguration_Item, cell_Group_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Cell_Group_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cell-Group-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct GNB_CU_UP_CellGroupRelatedConfiguration_Item, uP_TNL_Information),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_UP_TNL_Information,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uP-TNL-Information"
		},
	{ ATF_POINTER, 2, offsetof(struct GNB_CU_UP_CellGroupRelatedConfiguration_Item, uL_Configuration),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UL_Configuration,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uL-Configuration"
		},
	{ ATF_POINTER, 1, offsetof(struct GNB_CU_UP_CellGroupRelatedConfiguration_Item, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_128P44,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_GNB_CU_UP_CellGroupRelatedConfiguration_Item_oms_1[] = { 2, 3 };
static const ber_tlv_tag_t asn_DEF_GNB_CU_UP_CellGroupRelatedConfiguration_Item_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_GNB_CU_UP_CellGroupRelatedConfiguration_Item_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* cell-Group-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* uP-TNL-Information */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* uL-Configuration */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_GNB_CU_UP_CellGroupRelatedConfiguration_Item_specs_1 = {
	sizeof(struct GNB_CU_UP_CellGroupRelatedConfiguration_Item),
	offsetof(struct GNB_CU_UP_CellGroupRelatedConfiguration_Item, _asn_ctx),
	asn_MAP_GNB_CU_UP_CellGroupRelatedConfiguration_Item_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_GNB_CU_UP_CellGroupRelatedConfiguration_Item_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_GNB_CU_UP_CellGroupRelatedConfiguration_Item = {
	"GNB-CU-UP-CellGroupRelatedConfiguration-Item",
	"GNB-CU-UP-CellGroupRelatedConfiguration-Item",
	&asn_OP_SEQUENCE,
	asn_DEF_GNB_CU_UP_CellGroupRelatedConfiguration_Item_tags_1,
	sizeof(asn_DEF_GNB_CU_UP_CellGroupRelatedConfiguration_Item_tags_1)
		/sizeof(asn_DEF_GNB_CU_UP_CellGroupRelatedConfiguration_Item_tags_1[0]), /* 1 */
	asn_DEF_GNB_CU_UP_CellGroupRelatedConfiguration_Item_tags_1,	/* Same as above */
	sizeof(asn_DEF_GNB_CU_UP_CellGroupRelatedConfiguration_Item_tags_1)
		/sizeof(asn_DEF_GNB_CU_UP_CellGroupRelatedConfiguration_Item_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_GNB_CU_UP_CellGroupRelatedConfiguration_Item_1,
	4,	/* Elements count */
	&asn_SPC_GNB_CU_UP_CellGroupRelatedConfiguration_Item_specs_1	/* Additional specs */
};

