/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_GNB_CU_UP_Capacity_H_
#define	_GNB_CU_UP_Capacity_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* GNB-CU-UP-Capacity */
typedef long	 GNB_CU_UP_Capacity_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_GNB_CU_UP_Capacity_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_GNB_CU_UP_Capacity;
asn_struct_free_f GNB_CU_UP_Capacity_free;
asn_struct_print_f GNB_CU_UP_Capacity_print;
asn_constr_check_f GNB_CU_UP_Capacity_constraint;
ber_type_decoder_f GNB_CU_UP_Capacity_decode_ber;
der_type_encoder_f GNB_CU_UP_Capacity_encode_der;
xer_type_decoder_f GNB_CU_UP_Capacity_decode_xer;
xer_type_encoder_f GNB_CU_UP_Capacity_encode_xer;
oer_type_decoder_f GNB_CU_UP_Capacity_decode_oer;
oer_type_encoder_f GNB_CU_UP_Capacity_encode_oer;
per_type_decoder_f GNB_CU_UP_Capacity_decode_uper;
per_type_encoder_f GNB_CU_UP_Capacity_encode_uper;
per_type_decoder_f GNB_CU_UP_Capacity_decode_aper;
per_type_encoder_f GNB_CU_UP_Capacity_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _GNB_CU_UP_Capacity_H_ */
#include <asn_internal.h>
