/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_New_UL_TNL_Information_Required_H_
#define	_New_UL_TNL_Information_Required_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum New_UL_TNL_Information_Required {
	New_UL_TNL_Information_Required_required	= 0
	/*
	 * Enumeration is extensible
	 */
} e_New_UL_TNL_Information_Required;

/* New-UL-TNL-Information-Required */
typedef long	 New_UL_TNL_Information_Required_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_New_UL_TNL_Information_Required_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_New_UL_TNL_Information_Required;
extern const asn_INTEGER_specifics_t asn_SPC_New_UL_TNL_Information_Required_specs_1;
asn_struct_free_f New_UL_TNL_Information_Required_free;
asn_struct_print_f New_UL_TNL_Information_Required_print;
asn_constr_check_f New_UL_TNL_Information_Required_constraint;
ber_type_decoder_f New_UL_TNL_Information_Required_decode_ber;
der_type_encoder_f New_UL_TNL_Information_Required_encode_der;
xer_type_decoder_f New_UL_TNL_Information_Required_decode_xer;
xer_type_encoder_f New_UL_TNL_Information_Required_encode_xer;
oer_type_decoder_f New_UL_TNL_Information_Required_decode_oer;
oer_type_encoder_f New_UL_TNL_Information_Required_encode_oer;
per_type_decoder_f New_UL_TNL_Information_Required_decode_uper;
per_type_encoder_f New_UL_TNL_Information_Required_encode_uper;
per_type_decoder_f New_UL_TNL_Information_Required_decode_aper;
per_type_encoder_f New_UL_TNL_Information_Required_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _New_UL_TNL_Information_Required_H_ */
#include <asn_internal.h>
