/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#include "NG-RAN-QoS-Support-Item.h"

#include "ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_NG_RAN_QoS_Support_Item_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct NG_RAN_QoS_Support_Item, non_Dynamic5QIDescriptor),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Non_Dynamic5QIDescriptor,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"non-Dynamic5QIDescriptor"
		},
	{ ATF_POINTER, 1, offsetof(struct NG_RAN_QoS_Support_Item, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_128P58,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_NG_RAN_QoS_Support_Item_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_NG_RAN_QoS_Support_Item_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_NG_RAN_QoS_Support_Item_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* non-Dynamic5QIDescriptor */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_NG_RAN_QoS_Support_Item_specs_1 = {
	sizeof(struct NG_RAN_QoS_Support_Item),
	offsetof(struct NG_RAN_QoS_Support_Item, _asn_ctx),
	asn_MAP_NG_RAN_QoS_Support_Item_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_NG_RAN_QoS_Support_Item_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_NG_RAN_QoS_Support_Item = {
	"NG-RAN-QoS-Support-Item",
	"NG-RAN-QoS-Support-Item",
	&asn_OP_SEQUENCE,
	asn_DEF_NG_RAN_QoS_Support_Item_tags_1,
	sizeof(asn_DEF_NG_RAN_QoS_Support_Item_tags_1)
		/sizeof(asn_DEF_NG_RAN_QoS_Support_Item_tags_1[0]), /* 1 */
	asn_DEF_NG_RAN_QoS_Support_Item_tags_1,	/* Same as above */
	sizeof(asn_DEF_NG_RAN_QoS_Support_Item_tags_1)
		/sizeof(asn_DEF_NG_RAN_QoS_Support_Item_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_NG_RAN_QoS_Support_Item_1,
	2,	/* Elements count */
	&asn_SPC_NG_RAN_QoS_Support_Item_specs_1	/* Additional specs */
};

