/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_Non_Dynamic5QIDescriptor_H_
#define	_Non_Dynamic5QIDescriptor_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "QoSPriorityLevel.h"
#include "AveragingWindow.h"
#include "MaxDataBurstVolume.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* Non-Dynamic5QIDescriptor */
typedef struct Non_Dynamic5QIDescriptor {
	long	 fiveQI;
	QoSPriorityLevel_t	*qoSPriorityLevel;	/* OPTIONAL */
	AveragingWindow_t	*averagingWindow;	/* OPTIONAL */
	MaxDataBurstVolume_t	*maxDataBurstVolume;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Non_Dynamic5QIDescriptor_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Non_Dynamic5QIDescriptor;
extern asn_SEQUENCE_specifics_t asn_SPC_Non_Dynamic5QIDescriptor_specs_1;
extern asn_TYPE_member_t asn_MBR_Non_Dynamic5QIDescriptor_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _Non_Dynamic5QIDescriptor_H_ */
#include <asn_internal.h>
