/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_PDCP_DataRecovery_H_
#define	_PDCP_DataRecovery_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PDCP_DataRecovery {
	PDCP_DataRecovery_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_PDCP_DataRecovery;

/* PDCP-DataRecovery */
typedef long	 PDCP_DataRecovery_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PDCP_DataRecovery_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PDCP_DataRecovery;
extern const asn_INTEGER_specifics_t asn_SPC_PDCP_DataRecovery_specs_1;
asn_struct_free_f PDCP_DataRecovery_free;
asn_struct_print_f PDCP_DataRecovery_print;
asn_constr_check_f PDCP_DataRecovery_constraint;
ber_type_decoder_f PDCP_DataRecovery_decode_ber;
der_type_encoder_f PDCP_DataRecovery_encode_der;
xer_type_decoder_f PDCP_DataRecovery_decode_xer;
xer_type_encoder_f PDCP_DataRecovery_encode_xer;
oer_type_decoder_f PDCP_DataRecovery_decode_oer;
oer_type_encoder_f PDCP_DataRecovery_encode_oer;
per_type_decoder_f PDCP_DataRecovery_decode_uper;
per_type_encoder_f PDCP_DataRecovery_encode_uper;
per_type_decoder_f PDCP_DataRecovery_decode_aper;
per_type_encoder_f PDCP_DataRecovery_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _PDCP_DataRecovery_H_ */
#include <asn_internal.h>
