/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_PDCP_Duplication_H_
#define	_PDCP_Duplication_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PDCP_Duplication {
	PDCP_Duplication_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_PDCP_Duplication;

/* PDCP-Duplication */
typedef long	 PDCP_Duplication_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PDCP_Duplication_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PDCP_Duplication;
extern const asn_INTEGER_specifics_t asn_SPC_PDCP_Duplication_specs_1;
asn_struct_free_f PDCP_Duplication_free;
asn_struct_print_f PDCP_Duplication_print;
asn_constr_check_f PDCP_Duplication_constraint;
ber_type_decoder_f PDCP_Duplication_decode_ber;
der_type_encoder_f PDCP_Duplication_encode_der;
xer_type_decoder_f PDCP_Duplication_decode_xer;
xer_type_encoder_f PDCP_Duplication_encode_xer;
oer_type_decoder_f PDCP_Duplication_decode_oer;
oer_type_encoder_f PDCP_Duplication_encode_oer;
per_type_decoder_f PDCP_Duplication_decode_uper;
per_type_encoder_f PDCP_Duplication_encode_uper;
per_type_decoder_f PDCP_Duplication_decode_aper;
per_type_encoder_f PDCP_Duplication_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _PDCP_Duplication_H_ */
#include <asn_internal.h>
