/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_PDU_Session_Resource_Setup_Item_H_
#define	_PDU_Session_Resource_Setup_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PDU-Session-ID.h"
#include "UP-TNL-Information.h"
#include <NativeEnumerated.h>
#include "DRB-Setup-List-NG-RAN.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum PDU_Session_Resource_Setup_Item__nG_DL_UP_Unchanged {
	PDU_Session_Resource_Setup_Item__nG_DL_UP_Unchanged_true	= 0
	/*
	 * Enumeration is extensible
	 */
} e_PDU_Session_Resource_Setup_Item__nG_DL_UP_Unchanged;

/* Forward declarations */
struct SecurityResult;
struct Data_Forwarding_Information;
struct DRB_Failed_List_NG_RAN;
struct ProtocolExtensionContainer;

/* PDU-Session-Resource-Setup-Item */
typedef struct PDU_Session_Resource_Setup_Item {
	PDU_Session_ID_t	 pDU_Session_ID;
	struct SecurityResult	*securityResult;	/* OPTIONAL */
	UP_TNL_Information_t	 nG_DL_UP_TNL_Information;
	struct Data_Forwarding_Information	*pDU_Session_Data_Forwarding_Information_Response;	/* OPTIONAL */
	long	*nG_DL_UP_Unchanged;	/* OPTIONAL */
	DRB_Setup_List_NG_RAN_t	 dRB_Setup_List_NG_RAN;
	struct DRB_Failed_List_NG_RAN	*dRB_Failed_List_NG_RAN;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDU_Session_Resource_Setup_Item_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_nG_DL_UP_Unchanged_6;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_PDU_Session_Resource_Setup_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_PDU_Session_Resource_Setup_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_PDU_Session_Resource_Setup_Item_1[8];

#ifdef __cplusplus
}
#endif

#endif	/* _PDU_Session_Resource_Setup_Item_H_ */
#include <asn_internal.h>
