/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#include "PDU-Session-Resource-Failed-To-Modify-Item.h"

#include "ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_PDU_Session_Resource_Failed_To_Modify_Item_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct PDU_Session_Resource_Failed_To_Modify_Item, pDU_Session_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PDU_Session_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pDU-Session-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct PDU_Session_Resource_Failed_To_Modify_Item, cause),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Cause,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cause"
		},
	{ ATF_POINTER, 1, offsetof(struct PDU_Session_Resource_Failed_To_Modify_Item, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_128P72,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_PDU_Session_Resource_Failed_To_Modify_Item_oms_1[] = { 2 };
static const ber_tlv_tag_t asn_DEF_PDU_Session_Resource_Failed_To_Modify_Item_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_PDU_Session_Resource_Failed_To_Modify_Item_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* pDU-Session-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* cause */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_PDU_Session_Resource_Failed_To_Modify_Item_specs_1 = {
	sizeof(struct PDU_Session_Resource_Failed_To_Modify_Item),
	offsetof(struct PDU_Session_Resource_Failed_To_Modify_Item, _asn_ctx),
	asn_MAP_PDU_Session_Resource_Failed_To_Modify_Item_tag2el_1,
	3,	/* Count of tags in the map */
	asn_MAP_PDU_Session_Resource_Failed_To_Modify_Item_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_PDU_Session_Resource_Failed_To_Modify_Item = {
	"PDU-Session-Resource-Failed-To-Modify-Item",
	"PDU-Session-Resource-Failed-To-Modify-Item",
	&asn_OP_SEQUENCE,
	asn_DEF_PDU_Session_Resource_Failed_To_Modify_Item_tags_1,
	sizeof(asn_DEF_PDU_Session_Resource_Failed_To_Modify_Item_tags_1)
		/sizeof(asn_DEF_PDU_Session_Resource_Failed_To_Modify_Item_tags_1[0]), /* 1 */
	asn_DEF_PDU_Session_Resource_Failed_To_Modify_Item_tags_1,	/* Same as above */
	sizeof(asn_DEF_PDU_Session_Resource_Failed_To_Modify_Item_tags_1)
		/sizeof(asn_DEF_PDU_Session_Resource_Failed_To_Modify_Item_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_PDU_Session_Resource_Failed_To_Modify_Item_1,
	3,	/* Elements count */
	&asn_SPC_PDU_Session_Resource_Failed_To_Modify_Item_specs_1	/* Additional specs */
};

