/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_PDU_Session_Resource_To_Setup_Mod_Item_H_
#define	_PDU_Session_Resource_To_Setup_Mod_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PDU-Session-ID.h"
#include "PDU-Session-Type.h"
#include "SNSSAI.h"
#include "SecurityIndication.h"
#include "BitRate.h"
#include "UP-TNL-Information.h"
#include "Inactivity-Timer.h"
#include "DRB-To-Setup-Mod-List-NG-RAN.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Data_Forwarding_Information_Request;
struct ProtocolExtensionContainer;

/* PDU-Session-Resource-To-Setup-Mod-Item */
typedef struct PDU_Session_Resource_To_Setup_Mod_Item {
	PDU_Session_ID_t	 pDU_Session_ID;
	PDU_Session_Type_t	 pDU_Session_Type;
	SNSSAI_t	 sNSSAI;
	SecurityIndication_t	 securityIndication;
	BitRate_t	*pDU_Session_Resource_AMBR;	/* OPTIONAL */
	UP_TNL_Information_t	 nG_UL_UP_TNL_Information;
	struct Data_Forwarding_Information_Request	*pDU_Session_Data_Forwarding_Information_Request;	/* OPTIONAL */
	Inactivity_Timer_t	*pDU_Session_Inactivity_Timer;	/* OPTIONAL */
	DRB_To_Setup_Mod_List_NG_RAN_t	 dRB_To_Setup_Mod_List_NG_RAN;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} PDU_Session_Resource_To_Setup_Mod_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_PDU_Session_Resource_To_Setup_Mod_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_PDU_Session_Resource_To_Setup_Mod_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_PDU_Session_Resource_To_Setup_Mod_Item_1[10];

#ifdef __cplusplus
}
#endif

#endif	/* _PDU_Session_Resource_To_Setup_Mod_Item_H_ */
#include <asn_internal.h>
