/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_PPI_H_
#define	_PPI_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* PPI */
typedef long	 PPI_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_PPI_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_PPI;
asn_struct_free_f PPI_free;
asn_struct_print_f PPI_print;
asn_constr_check_f PPI_constraint;
ber_type_decoder_f PPI_decode_ber;
der_type_encoder_f PPI_encode_der;
xer_type_decoder_f PPI_decode_xer;
xer_type_encoder_f PPI_encode_xer;
oer_type_decoder_f PPI_decode_oer;
oer_type_encoder_f PPI_encode_oer;
per_type_decoder_f PPI_decode_uper;
per_type_encoder_f PPI_encode_uper;
per_type_decoder_f PPI_decode_aper;
per_type_encoder_f PPI_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _PPI_H_ */
#include <asn_internal.h>
