/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-Containers"
 * 	found in "E1AP-Containers.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_ProtocolIE_Container_H_
#define	_ProtocolIE_Container_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ResetIEs;
struct ResetAcknowledgeIEs;
struct ErrorIndication_IEs;
struct GNB_CU_UP_E1SetupRequestIEs;
struct GNB_CU_UP_E1SetupResponseIEs;
struct GNB_CU_UP_E1SetupFailureIEs;
struct GNB_CU_CP_E1SetupRequestIEs;
struct GNB_CU_CP_E1SetupResponseIEs;
struct GNB_CU_CP_E1SetupFailureIEs;
struct GNB_CU_UP_ConfigurationUpdateIEs;
struct GNB_CU_UP_ConfigurationUpdateAcknowledgeIEs;
struct GNB_CU_UP_ConfigurationUpdateFailureIEs;
struct GNB_CU_CP_ConfigurationUpdateIEs;
struct GNB_CU_CP_ConfigurationUpdateAcknowledgeIEs;
struct GNB_CU_CP_ConfigurationUpdateFailureIEs;
struct E1ReleaseRequestIEs;
struct E1ReleaseResponseIEs;
struct BearerContextSetupRequestIEs;
struct EUTRAN_BearerContextSetupRequestIEs;
struct NG_RAN_BearerContextSetupRequestIEs;
struct BearerContextSetupResponseIEs;
struct EUTRAN_BearerContextSetupResponseIEs;
struct NG_RAN_BearerContextSetupResponseIEs;
struct BearerContextSetupFailureIEs;
struct BearerContextModificationRequestIEs;
struct EUTRAN_BearerContextModificationRequestIEs;
struct NG_RAN_BearerContextModificationRequestIEs;
struct BearerContextModificationResponseIEs;
struct EUTRAN_BearerContextModificationResponseIEs;
struct NG_RAN_BearerContextModificationResponseIEs;
struct BearerContextModificationFailureIEs;
struct BearerContextModificationRequiredIEs;
struct EUTRAN_BearerContextModificationRequiredIEs;
struct NG_RAN_BearerContextModificationRequiredIEs;
struct BearerContextModificationConfirmIEs;
struct EUTRAN_BearerContextModificationConfirmIEs;
struct NG_RAN_BearerContextModificationConfirmIEs;
struct BearerContextReleaseCommandIEs;
struct BearerContextReleaseCompleteIEs;
struct BearerContextReleaseRequestIEs;
struct BearerContextInactivityNotificationIEs;
struct DLDataNotificationIEs;
struct ULDataNotificationIEs;
struct DataUsageReportIEs;
struct GNB_CU_UP_CounterCheckRequestIEs;
struct EUTRAN_GNB_CU_UP_CounterCheckRequestIEs;
struct NG_RAN_GNB_CU_UP_CounterCheckRequestIEs;
struct GNB_CU_UP_StatusIndicationIEs;
struct MRDC_DataUsageReportIEs;

/* ProtocolIE-Container */
typedef struct ProtocolIE_Container_99P0 {
	A_SEQUENCE_OF(struct ResetIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P0_t;
typedef struct ProtocolIE_Container_99P1 {
	A_SEQUENCE_OF(struct ResetAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P1_t;
typedef struct ProtocolIE_Container_99P2 {
	A_SEQUENCE_OF(struct ErrorIndication_IEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P2_t;
typedef struct ProtocolIE_Container_99P3 {
	A_SEQUENCE_OF(struct GNB_CU_UP_E1SetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P3_t;
typedef struct ProtocolIE_Container_99P4 {
	A_SEQUENCE_OF(struct GNB_CU_UP_E1SetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P4_t;
typedef struct ProtocolIE_Container_99P5 {
	A_SEQUENCE_OF(struct GNB_CU_UP_E1SetupFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P5_t;
typedef struct ProtocolIE_Container_99P6 {
	A_SEQUENCE_OF(struct GNB_CU_CP_E1SetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P6_t;
typedef struct ProtocolIE_Container_99P7 {
	A_SEQUENCE_OF(struct GNB_CU_CP_E1SetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P7_t;
typedef struct ProtocolIE_Container_99P8 {
	A_SEQUENCE_OF(struct GNB_CU_CP_E1SetupFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P8_t;
typedef struct ProtocolIE_Container_99P9 {
	A_SEQUENCE_OF(struct GNB_CU_UP_ConfigurationUpdateIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P9_t;
typedef struct ProtocolIE_Container_99P10 {
	A_SEQUENCE_OF(struct GNB_CU_UP_ConfigurationUpdateAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P10_t;
typedef struct ProtocolIE_Container_99P11 {
	A_SEQUENCE_OF(struct GNB_CU_UP_ConfigurationUpdateFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P11_t;
typedef struct ProtocolIE_Container_99P12 {
	A_SEQUENCE_OF(struct GNB_CU_CP_ConfigurationUpdateIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P12_t;
typedef struct ProtocolIE_Container_99P13 {
	A_SEQUENCE_OF(struct GNB_CU_CP_ConfigurationUpdateAcknowledgeIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P13_t;
typedef struct ProtocolIE_Container_99P14 {
	A_SEQUENCE_OF(struct GNB_CU_CP_ConfigurationUpdateFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P14_t;
typedef struct ProtocolIE_Container_99P15 {
	A_SEQUENCE_OF(struct E1ReleaseRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P15_t;
typedef struct ProtocolIE_Container_99P16 {
	A_SEQUENCE_OF(struct E1ReleaseResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P16_t;
typedef struct ProtocolIE_Container_99P17 {
	A_SEQUENCE_OF(struct BearerContextSetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P17_t;
typedef struct ProtocolIE_Container_99P18 {
	A_SEQUENCE_OF(struct EUTRAN_BearerContextSetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P18_t;
typedef struct ProtocolIE_Container_99P19 {
	A_SEQUENCE_OF(struct NG_RAN_BearerContextSetupRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P19_t;
typedef struct ProtocolIE_Container_99P20 {
	A_SEQUENCE_OF(struct BearerContextSetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P20_t;
typedef struct ProtocolIE_Container_99P21 {
	A_SEQUENCE_OF(struct EUTRAN_BearerContextSetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P21_t;
typedef struct ProtocolIE_Container_99P22 {
	A_SEQUENCE_OF(struct NG_RAN_BearerContextSetupResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P22_t;
typedef struct ProtocolIE_Container_99P23 {
	A_SEQUENCE_OF(struct BearerContextSetupFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P23_t;
typedef struct ProtocolIE_Container_99P24 {
	A_SEQUENCE_OF(struct BearerContextModificationRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P24_t;
typedef struct ProtocolIE_Container_99P25 {
	A_SEQUENCE_OF(struct EUTRAN_BearerContextModificationRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P25_t;
typedef struct ProtocolIE_Container_99P26 {
	A_SEQUENCE_OF(struct NG_RAN_BearerContextModificationRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P26_t;
typedef struct ProtocolIE_Container_99P27 {
	A_SEQUENCE_OF(struct BearerContextModificationResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P27_t;
typedef struct ProtocolIE_Container_99P28 {
	A_SEQUENCE_OF(struct EUTRAN_BearerContextModificationResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P28_t;
typedef struct ProtocolIE_Container_99P29 {
	A_SEQUENCE_OF(struct NG_RAN_BearerContextModificationResponseIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P29_t;
typedef struct ProtocolIE_Container_99P30 {
	A_SEQUENCE_OF(struct BearerContextModificationFailureIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P30_t;
typedef struct ProtocolIE_Container_99P31 {
	A_SEQUENCE_OF(struct BearerContextModificationRequiredIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P31_t;
typedef struct ProtocolIE_Container_99P32 {
	A_SEQUENCE_OF(struct EUTRAN_BearerContextModificationRequiredIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P32_t;
typedef struct ProtocolIE_Container_99P33 {
	A_SEQUENCE_OF(struct NG_RAN_BearerContextModificationRequiredIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P33_t;
typedef struct ProtocolIE_Container_99P34 {
	A_SEQUENCE_OF(struct BearerContextModificationConfirmIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P34_t;
typedef struct ProtocolIE_Container_99P35 {
	A_SEQUENCE_OF(struct EUTRAN_BearerContextModificationConfirmIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P35_t;
typedef struct ProtocolIE_Container_99P36 {
	A_SEQUENCE_OF(struct NG_RAN_BearerContextModificationConfirmIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P36_t;
typedef struct ProtocolIE_Container_99P37 {
	A_SEQUENCE_OF(struct BearerContextReleaseCommandIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P37_t;
typedef struct ProtocolIE_Container_99P38 {
	A_SEQUENCE_OF(struct BearerContextReleaseCompleteIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P38_t;
typedef struct ProtocolIE_Container_99P39 {
	A_SEQUENCE_OF(struct BearerContextReleaseRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P39_t;
typedef struct ProtocolIE_Container_99P40 {
	A_SEQUENCE_OF(struct BearerContextInactivityNotificationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P40_t;
typedef struct ProtocolIE_Container_99P41 {
	A_SEQUENCE_OF(struct DLDataNotificationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P41_t;
typedef struct ProtocolIE_Container_99P42 {
	A_SEQUENCE_OF(struct ULDataNotificationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P42_t;
typedef struct ProtocolIE_Container_99P43 {
	A_SEQUENCE_OF(struct DataUsageReportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P43_t;
typedef struct ProtocolIE_Container_99P44 {
	A_SEQUENCE_OF(struct GNB_CU_UP_CounterCheckRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P44_t;
typedef struct ProtocolIE_Container_99P45 {
	A_SEQUENCE_OF(struct EUTRAN_GNB_CU_UP_CounterCheckRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P45_t;
typedef struct ProtocolIE_Container_99P46 {
	A_SEQUENCE_OF(struct NG_RAN_GNB_CU_UP_CounterCheckRequestIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P46_t;
typedef struct ProtocolIE_Container_99P47 {
	A_SEQUENCE_OF(struct GNB_CU_UP_StatusIndicationIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P47_t;
typedef struct ProtocolIE_Container_99P48 {
	A_SEQUENCE_OF(struct MRDC_DataUsageReportIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolIE_Container_99P48_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P0;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P0_specs_1;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P0_1[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P1;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P1_specs_3;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P1_3[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P1_constr_3;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P2;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P2_specs_5;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P2_5[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P2_constr_5;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P3;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P3_specs_7;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P3_7[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P3_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P4;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P4_specs_9;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P4_9[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P4_constr_9;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P5;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P5_specs_11;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P5_11[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P5_constr_11;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P6;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P6_specs_13;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P6_13[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P6_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P7;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P7_specs_15;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P7_15[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P7_constr_15;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P8;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P8_specs_17;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P8_17[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P8_constr_17;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P9;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P9_specs_19;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P9_19[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P9_constr_19;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P10;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P10_specs_21;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P10_21[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P10_constr_21;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P11;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P11_specs_23;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P11_23[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P11_constr_23;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P12;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P12_specs_25;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P12_25[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P12_constr_25;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P13;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P13_specs_27;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P13_27[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P13_constr_27;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P14;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P14_specs_29;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P14_29[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P14_constr_29;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P15;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P15_specs_31;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P15_31[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P15_constr_31;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P16;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P16_specs_33;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P16_33[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P16_constr_33;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P17;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P17_specs_35;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P17_35[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P17_constr_35;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P18;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P18_specs_37;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P18_37[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P18_constr_37;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P19;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P19_specs_39;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P19_39[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P19_constr_39;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P20;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P20_specs_41;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P20_41[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P20_constr_41;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P21;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P21_specs_43;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P21_43[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P21_constr_43;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P22;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P22_specs_45;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P22_45[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P22_constr_45;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P23;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P23_specs_47;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P23_47[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P23_constr_47;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P24;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P24_specs_49;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P24_49[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P24_constr_49;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P25;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P25_specs_51;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P25_51[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P25_constr_51;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P26;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P26_specs_53;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P26_53[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P26_constr_53;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P27;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P27_specs_55;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P27_55[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P27_constr_55;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P28;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P28_specs_57;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P28_57[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P28_constr_57;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P29;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P29_specs_59;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P29_59[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P29_constr_59;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P30;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P30_specs_61;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P30_61[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P30_constr_61;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P31;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P31_specs_63;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P31_63[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P31_constr_63;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P32;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P32_specs_65;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P32_65[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P32_constr_65;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P33;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P33_specs_67;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P33_67[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P33_constr_67;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P34;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P34_specs_69;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P34_69[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P34_constr_69;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P35;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P35_specs_71;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P35_71[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P35_constr_71;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P36;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P36_specs_73;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P36_73[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P36_constr_73;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P37;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P37_specs_75;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P37_75[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P37_constr_75;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P38;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P38_specs_77;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P38_77[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P38_constr_77;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P39;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P39_specs_79;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P39_79[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P39_constr_79;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P40;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P40_specs_81;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P40_81[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P40_constr_81;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P41;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P41_specs_83;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P41_83[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P41_constr_83;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P42;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P42_specs_85;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P42_85[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P42_constr_85;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P43;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P43_specs_87;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P43_87[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P43_constr_87;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P44;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P44_specs_89;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P44_89[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P44_constr_89;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P45;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P45_specs_91;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P45_91[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P45_constr_91;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P46;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P46_specs_93;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P46_93[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P46_constr_93;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P47;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P47_specs_95;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P47_95[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P47_constr_95;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_Container_99P48;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolIE_Container_99P48_specs_97;
extern asn_TYPE_member_t asn_MBR_ProtocolIE_Container_99P48_97[1];
extern asn_per_constraints_t asn_PER_type_ProtocolIE_Container_99P48_constr_97;

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolIE_Container_H_ */
#include <asn_internal.h>
