/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-Containers"
 * 	found in "E1AP-Containers.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_ProtocolExtensionContainer_H_
#define	_ProtocolExtensionContainer_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Cell_Group_Information_Item_ExtIEs;
struct CriticalityDiagnostics_ExtIEs;
struct CriticalityDiagnostics_IE_List_ExtIEs;
struct Data_Forwarding_Information_Request_ExtIEs;
struct Data_Forwarding_Information_ExtIEs;
struct Data_Usage_per_PDU_Session_Report_ExtIEs;
struct Data_Usage_per_QoS_Flow_Item_ExtIEs;
struct Data_Usage_Report_ItemExtIEs;
struct DRB_Activity_ItemExtIEs;
struct DRB_Confirm_Modified_Item_EUTRAN_ExtIEs;
struct DRB_Confirm_Modified_Item_NG_RAN_ExtIEs;
struct DRB_Failed_Item_EUTRAN_ExtIEs;
struct DRB_Failed_Mod_Item_EUTRAN_ExtIEs;
struct DRB_Failed_Item_NG_RAN_ExtIEs;
struct DRB_Failed_Mod_Item_NG_RAN_ExtIEs;
struct DRB_Failed_To_Modify_Item_EUTRAN_ExtIEs;
struct DRB_Failed_To_Modify_Item_NG_RAN_ExtIEs;
struct DRB_Modified_Item_EUTRAN_ExtIEs;
struct DRB_Modified_Item_NG_RAN_ExtIEs;
struct DRB_Required_To_Modify_Item_EUTRAN_ExtIEs;
struct DRB_Required_To_Modify_Item_NG_RAN_ExtIEs;
struct DRB_Setup_Item_EUTRAN_ExtIEs;
struct DRB_Setup_Mod_Item_EUTRAN_ExtIEs;
struct DRB_Setup_Item_NG_RAN_ExtIEs;
struct DRB_Setup_Mod_Item_NG_RAN_ExtIEs;
struct DRB_Status_ItemExtIEs;
struct DRBs_Subject_To_Counter_Check_Item_EUTRAN_ExtIEs;
struct DRBs_Subject_To_Counter_Check_Item_NG_RAN_ExtIEs;
struct DRB_To_Modify_Item_EUTRAN_ExtIEs;
struct DRB_To_Modify_Item_NG_RAN_ExtIEs;
struct DRB_To_Remove_Item_EUTRAN_ExtIEs;
struct DRB_Required_To_Remove_Item_EUTRAN_ExtIEs;
struct DRB_To_Remove_Item_NG_RAN_ExtIEs;
struct DRB_Required_To_Remove_Item_NG_RAN_ExtIEs;
struct DRB_To_Setup_Item_EUTRAN_ExtIEs;
struct DRB_To_Setup_Mod_Item_EUTRAN_ExtIEs;
struct DRB_To_Setup_Item_NG_RAN_ExtIEs;
struct DRB_To_Setup_Mod_Item_NG_RAN_ExtIEs;
struct DRB_Usage_Report_Item_ExtIEs;
struct Dynamic5QIDescriptor_ExtIEs;
struct Endpoint_IP_address_and_port_ExtIEs;
struct EUTRANAllocationAndRetentionPriority_ExtIEs;
struct EUTRAN_QoS_Support_Item_ExtIEs;
struct EUTRAN_QoS_ExtIEs;
struct GNB_CU_UP_CellGroupRelatedConfiguration_Item_ExtIEs;
struct GNB_CU_CP_TNLA_Setup_Item_ExtIEs;
struct GNB_CU_CP_TNLA_Failed_To_Setup_Item_ExtIEs;
struct GNB_CU_CP_TNLA_To_Add_Item_ExtIEs;
struct GNB_CU_CP_TNLA_To_Remove_Item_ExtIEs;
struct GNB_CU_CP_TNLA_To_Update_Item_ExtIEs;
struct GNB_CU_UP_TNLA_To_Remove_Item_ExtIEs;
struct GBR_QosInformation_ExtIEs;
struct GBR_QosFlowInformation_ExtIEs;
struct GTPTunnel_ExtIEs;
struct MaximumIPdatarate_ExtIEs;
struct MRDC_Data_Usage_Report_Item_ExtIEs;
struct MRDC_Usage_Information_ExtIEs;
struct NGRANAllocationAndRetentionPriority_ExtIEs;
struct NG_RAN_QoS_Support_Item_ExtIEs;
struct Non_Dynamic5QIDescriptor_ExtIEs;
struct NR_CGI_ExtIEs;
struct NR_CGI_Support_Item_ExtIEs;
struct PacketErrorRate_ExtIEs;
struct PDCP_Configuration_ExtIEs;
struct PDCP_Count_ExtIEs;
struct PDU_Session_Resource_Data_Usage_Item_ExtIEs;
struct DRBsSubjectToStatusTransfer_Item_ExtIEs;
struct DRBBStatusTransfer_ExtIEs;
struct PDU_Session_Resource_Activity_ItemExtIEs;
struct PDU_Session_Resource_Confirm_Modified_Item_ExtIEs;
struct PDU_Session_Resource_Failed_Item_ExtIEs;
struct PDU_Session_Resource_Failed_Mod_Item_ExtIEs;
struct PDU_Session_Resource_Failed_To_Modify_Item_ExtIEs;
struct PDU_Session_Resource_Modified_Item_ExtIEs;
struct PDU_Session_Resource_Required_To_Modify_Item_ExtIEs;
struct PDU_Session_Resource_Setup_Item_ExtIEs;
struct PDU_Session_Resource_Setup_Mod_Item_ExtIEs;
struct PDU_Session_Resource_To_Modify_Item_ExtIEs;
struct PDU_Session_Resource_To_Remove_Item_ExtIEs;
struct PDU_Session_Resource_To_Setup_Item_ExtIEs;
struct PDU_Session_Resource_To_Setup_Mod_Item_ExtIEs;
struct PDU_Session_To_Notify_Item_ExtIEs;
struct QoS_Flow_Item_ExtIEs;
struct QoS_Flow_Failed_Item_ExtIEs;
struct QoS_Flow_Mapping_Item_ExtIEs;
struct QoS_Parameters_Support_List_ItemExtIEs;
struct QoS_Flow_QoS_Parameter_Item_ExtIEs;
struct QoSFlowLevelQoSParameters_ExtIEs;
struct ROHC_ExtIEs;
struct SecurityAlgorithm_ExtIEs;
struct SecurityIndication_ExtIEs;
struct SecurityInformation_ExtIEs;
struct SecurityResult_ExtIEs;
struct Slice_Support_Item_ExtIEs;
struct SNSSAI_ExtIEs;
struct SDAP_Configuration_ExtIEs;
struct T_ReorderingTimer_ExtIEs;
struct UE_associatedLogicalE1_ConnectionItemExtIEs;
struct UP_Parameters_Item_ExtIEs;
struct UPSecuritykey_ExtIEs;
struct UplinkOnlyROHC_ExtIEs;
struct SupportedPLMNs_ExtIEs;

/* ProtocolExtensionContainer */
typedef struct ProtocolExtensionContainer_128P0 {
	A_SEQUENCE_OF(struct Cell_Group_Information_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P0_t;
typedef struct ProtocolExtensionContainer_128P1 {
	A_SEQUENCE_OF(struct CriticalityDiagnostics_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P1_t;
typedef struct ProtocolExtensionContainer_128P2 {
	A_SEQUENCE_OF(struct CriticalityDiagnostics_IE_List_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P2_t;
typedef struct ProtocolExtensionContainer_128P3 {
	A_SEQUENCE_OF(struct Data_Forwarding_Information_Request_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P3_t;
typedef struct ProtocolExtensionContainer_128P4 {
	A_SEQUENCE_OF(struct Data_Forwarding_Information_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P4_t;
typedef struct ProtocolExtensionContainer_128P5 {
	A_SEQUENCE_OF(struct Data_Usage_per_PDU_Session_Report_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P5_t;
typedef struct ProtocolExtensionContainer_128P6 {
	A_SEQUENCE_OF(struct Data_Usage_per_QoS_Flow_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P6_t;
typedef struct ProtocolExtensionContainer_128P7 {
	A_SEQUENCE_OF(struct Data_Usage_Report_ItemExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P7_t;
typedef struct ProtocolExtensionContainer_128P8 {
	A_SEQUENCE_OF(struct DRB_Activity_ItemExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P8_t;
typedef struct ProtocolExtensionContainer_128P9 {
	A_SEQUENCE_OF(struct DRB_Confirm_Modified_Item_EUTRAN_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P9_t;
typedef struct ProtocolExtensionContainer_128P10 {
	A_SEQUENCE_OF(struct DRB_Confirm_Modified_Item_NG_RAN_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P10_t;
typedef struct ProtocolExtensionContainer_128P11 {
	A_SEQUENCE_OF(struct DRB_Failed_Item_EUTRAN_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P11_t;
typedef struct ProtocolExtensionContainer_128P12 {
	A_SEQUENCE_OF(struct DRB_Failed_Mod_Item_EUTRAN_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P12_t;
typedef struct ProtocolExtensionContainer_128P13 {
	A_SEQUENCE_OF(struct DRB_Failed_Item_NG_RAN_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P13_t;
typedef struct ProtocolExtensionContainer_128P14 {
	A_SEQUENCE_OF(struct DRB_Failed_Mod_Item_NG_RAN_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P14_t;
typedef struct ProtocolExtensionContainer_128P15 {
	A_SEQUENCE_OF(struct DRB_Failed_To_Modify_Item_EUTRAN_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P15_t;
typedef struct ProtocolExtensionContainer_128P16 {
	A_SEQUENCE_OF(struct DRB_Failed_To_Modify_Item_NG_RAN_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P16_t;
typedef struct ProtocolExtensionContainer_128P17 {
	A_SEQUENCE_OF(struct DRB_Modified_Item_EUTRAN_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P17_t;
typedef struct ProtocolExtensionContainer_128P18 {
	A_SEQUENCE_OF(struct DRB_Modified_Item_NG_RAN_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P18_t;
typedef struct ProtocolExtensionContainer_128P19 {
	A_SEQUENCE_OF(struct DRB_Required_To_Modify_Item_EUTRAN_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P19_t;
typedef struct ProtocolExtensionContainer_128P20 {
	A_SEQUENCE_OF(struct DRB_Required_To_Modify_Item_NG_RAN_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P20_t;
typedef struct ProtocolExtensionContainer_128P21 {
	A_SEQUENCE_OF(struct DRB_Setup_Item_EUTRAN_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P21_t;
typedef struct ProtocolExtensionContainer_128P22 {
	A_SEQUENCE_OF(struct DRB_Setup_Mod_Item_EUTRAN_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P22_t;
typedef struct ProtocolExtensionContainer_128P23 {
	A_SEQUENCE_OF(struct DRB_Setup_Item_NG_RAN_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P23_t;
typedef struct ProtocolExtensionContainer_128P24 {
	A_SEQUENCE_OF(struct DRB_Setup_Mod_Item_NG_RAN_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P24_t;
typedef struct ProtocolExtensionContainer_128P25 {
	A_SEQUENCE_OF(struct DRB_Status_ItemExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P25_t;
typedef struct ProtocolExtensionContainer_128P26 {
	A_SEQUENCE_OF(struct DRBs_Subject_To_Counter_Check_Item_EUTRAN_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P26_t;
typedef struct ProtocolExtensionContainer_128P27 {
	A_SEQUENCE_OF(struct DRBs_Subject_To_Counter_Check_Item_NG_RAN_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P27_t;
typedef struct ProtocolExtensionContainer_128P28 {
	A_SEQUENCE_OF(struct DRB_To_Modify_Item_EUTRAN_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P28_t;
typedef struct ProtocolExtensionContainer_128P29 {
	A_SEQUENCE_OF(struct DRB_To_Modify_Item_NG_RAN_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P29_t;
typedef struct ProtocolExtensionContainer_128P30 {
	A_SEQUENCE_OF(struct DRB_To_Remove_Item_EUTRAN_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P30_t;
typedef struct ProtocolExtensionContainer_128P31 {
	A_SEQUENCE_OF(struct DRB_Required_To_Remove_Item_EUTRAN_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P31_t;
typedef struct ProtocolExtensionContainer_128P32 {
	A_SEQUENCE_OF(struct DRB_To_Remove_Item_NG_RAN_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P32_t;
typedef struct ProtocolExtensionContainer_128P33 {
	A_SEQUENCE_OF(struct DRB_Required_To_Remove_Item_NG_RAN_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P33_t;
typedef struct ProtocolExtensionContainer_128P34 {
	A_SEQUENCE_OF(struct DRB_To_Setup_Item_EUTRAN_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P34_t;
typedef struct ProtocolExtensionContainer_128P35 {
	A_SEQUENCE_OF(struct DRB_To_Setup_Mod_Item_EUTRAN_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P35_t;
typedef struct ProtocolExtensionContainer_128P36 {
	A_SEQUENCE_OF(struct DRB_To_Setup_Item_NG_RAN_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P36_t;
typedef struct ProtocolExtensionContainer_128P37 {
	A_SEQUENCE_OF(struct DRB_To_Setup_Mod_Item_NG_RAN_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P37_t;
typedef struct ProtocolExtensionContainer_128P38 {
	A_SEQUENCE_OF(struct DRB_Usage_Report_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P38_t;
typedef struct ProtocolExtensionContainer_128P39 {
	A_SEQUENCE_OF(struct Dynamic5QIDescriptor_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P39_t;
typedef struct ProtocolExtensionContainer_128P40 {
	A_SEQUENCE_OF(struct Endpoint_IP_address_and_port_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P40_t;
typedef struct ProtocolExtensionContainer_128P41 {
	A_SEQUENCE_OF(struct EUTRANAllocationAndRetentionPriority_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P41_t;
typedef struct ProtocolExtensionContainer_128P42 {
	A_SEQUENCE_OF(struct EUTRAN_QoS_Support_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P42_t;
typedef struct ProtocolExtensionContainer_128P43 {
	A_SEQUENCE_OF(struct EUTRAN_QoS_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P43_t;
typedef struct ProtocolExtensionContainer_128P44 {
	A_SEQUENCE_OF(struct GNB_CU_UP_CellGroupRelatedConfiguration_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P44_t;
typedef struct ProtocolExtensionContainer_128P45 {
	A_SEQUENCE_OF(struct GNB_CU_CP_TNLA_Setup_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P45_t;
typedef struct ProtocolExtensionContainer_128P46 {
	A_SEQUENCE_OF(struct GNB_CU_CP_TNLA_Failed_To_Setup_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P46_t;
typedef struct ProtocolExtensionContainer_128P47 {
	A_SEQUENCE_OF(struct GNB_CU_CP_TNLA_To_Add_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P47_t;
typedef struct ProtocolExtensionContainer_128P48 {
	A_SEQUENCE_OF(struct GNB_CU_CP_TNLA_To_Remove_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P48_t;
typedef struct ProtocolExtensionContainer_128P49 {
	A_SEQUENCE_OF(struct GNB_CU_CP_TNLA_To_Update_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P49_t;
typedef struct ProtocolExtensionContainer_128P50 {
	A_SEQUENCE_OF(struct GNB_CU_UP_TNLA_To_Remove_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P50_t;
typedef struct ProtocolExtensionContainer_128P51 {
	A_SEQUENCE_OF(struct GBR_QosInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P51_t;
typedef struct ProtocolExtensionContainer_128P52 {
	A_SEQUENCE_OF(struct GBR_QosFlowInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P52_t;
typedef struct ProtocolExtensionContainer_128P53 {
	A_SEQUENCE_OF(struct GTPTunnel_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P53_t;
typedef struct ProtocolExtensionContainer_128P54 {
	A_SEQUENCE_OF(struct MaximumIPdatarate_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P54_t;
typedef struct ProtocolExtensionContainer_128P55 {
	A_SEQUENCE_OF(struct MRDC_Data_Usage_Report_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P55_t;
typedef struct ProtocolExtensionContainer_128P56 {
	A_SEQUENCE_OF(struct MRDC_Usage_Information_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P56_t;
typedef struct ProtocolExtensionContainer_128P57 {
	A_SEQUENCE_OF(struct NGRANAllocationAndRetentionPriority_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P57_t;
typedef struct ProtocolExtensionContainer_128P58 {
	A_SEQUENCE_OF(struct NG_RAN_QoS_Support_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P58_t;
typedef struct ProtocolExtensionContainer_128P59 {
	A_SEQUENCE_OF(struct Non_Dynamic5QIDescriptor_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P59_t;
typedef struct ProtocolExtensionContainer_128P60 {
	A_SEQUENCE_OF(struct NR_CGI_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P60_t;
typedef struct ProtocolExtensionContainer_128P61 {
	A_SEQUENCE_OF(struct NR_CGI_Support_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P61_t;
typedef struct ProtocolExtensionContainer_128P62 {
	A_SEQUENCE_OF(struct PacketErrorRate_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P62_t;
typedef struct ProtocolExtensionContainer_128P63 {
	A_SEQUENCE_OF(struct PDCP_Configuration_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P63_t;
typedef struct ProtocolExtensionContainer_128P64 {
	A_SEQUENCE_OF(struct PDCP_Count_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P64_t;
typedef struct ProtocolExtensionContainer_128P65 {
	A_SEQUENCE_OF(struct PDU_Session_Resource_Data_Usage_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P65_t;
typedef struct ProtocolExtensionContainer_128P66 {
	A_SEQUENCE_OF(struct DRBsSubjectToStatusTransfer_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P66_t;
typedef struct ProtocolExtensionContainer_128P67 {
	A_SEQUENCE_OF(struct DRBBStatusTransfer_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P67_t;
typedef struct ProtocolExtensionContainer_128P68 {
	A_SEQUENCE_OF(struct PDU_Session_Resource_Activity_ItemExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P68_t;
typedef struct ProtocolExtensionContainer_128P69 {
	A_SEQUENCE_OF(struct PDU_Session_Resource_Confirm_Modified_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P69_t;
typedef struct ProtocolExtensionContainer_128P70 {
	A_SEQUENCE_OF(struct PDU_Session_Resource_Failed_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P70_t;
typedef struct ProtocolExtensionContainer_128P71 {
	A_SEQUENCE_OF(struct PDU_Session_Resource_Failed_Mod_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P71_t;
typedef struct ProtocolExtensionContainer_128P72 {
	A_SEQUENCE_OF(struct PDU_Session_Resource_Failed_To_Modify_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P72_t;
typedef struct ProtocolExtensionContainer_128P73 {
	A_SEQUENCE_OF(struct PDU_Session_Resource_Modified_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P73_t;
typedef struct ProtocolExtensionContainer_128P74 {
	A_SEQUENCE_OF(struct PDU_Session_Resource_Required_To_Modify_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P74_t;
typedef struct ProtocolExtensionContainer_128P75 {
	A_SEQUENCE_OF(struct PDU_Session_Resource_Setup_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P75_t;
typedef struct ProtocolExtensionContainer_128P76 {
	A_SEQUENCE_OF(struct PDU_Session_Resource_Setup_Mod_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P76_t;
typedef struct ProtocolExtensionContainer_128P77 {
	A_SEQUENCE_OF(struct PDU_Session_Resource_To_Modify_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P77_t;
typedef struct ProtocolExtensionContainer_128P78 {
	A_SEQUENCE_OF(struct PDU_Session_Resource_To_Remove_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P78_t;
typedef struct ProtocolExtensionContainer_128P79 {
	A_SEQUENCE_OF(struct PDU_Session_Resource_To_Setup_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P79_t;
typedef struct ProtocolExtensionContainer_128P80 {
	A_SEQUENCE_OF(struct PDU_Session_Resource_To_Setup_Mod_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P80_t;
typedef struct ProtocolExtensionContainer_128P81 {
	A_SEQUENCE_OF(struct PDU_Session_To_Notify_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P81_t;
typedef struct ProtocolExtensionContainer_128P82 {
	A_SEQUENCE_OF(struct QoS_Flow_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P82_t;
typedef struct ProtocolExtensionContainer_128P83 {
	A_SEQUENCE_OF(struct QoS_Flow_Failed_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P83_t;
typedef struct ProtocolExtensionContainer_128P84 {
	A_SEQUENCE_OF(struct QoS_Flow_Mapping_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P84_t;
typedef struct ProtocolExtensionContainer_128P85 {
	A_SEQUENCE_OF(struct QoS_Parameters_Support_List_ItemExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P85_t;
typedef struct ProtocolExtensionContainer_128P86 {
	A_SEQUENCE_OF(struct QoS_Flow_QoS_Parameter_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P86_t;
typedef struct ProtocolExtensionContainer_128P87 {
	A_SEQUENCE_OF(struct QoSFlowLevelQoSParameters_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P87_t;
typedef struct ProtocolExtensionContainer_128P88 {
	A_SEQUENCE_OF(struct ROHC_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P88_t;
typedef struct ProtocolExtensionContainer_128P89 {
	A_SEQUENCE_OF(struct SecurityAlgorithm_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P89_t;
typedef struct ProtocolExtensionContainer_128P90 {
	A_SEQUENCE_OF(struct SecurityIndication_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P90_t;
typedef struct ProtocolExtensionContainer_128P91 {
	A_SEQUENCE_OF(struct SecurityInformation_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P91_t;
typedef struct ProtocolExtensionContainer_128P92 {
	A_SEQUENCE_OF(struct SecurityResult_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P92_t;
typedef struct ProtocolExtensionContainer_128P93 {
	A_SEQUENCE_OF(struct Slice_Support_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P93_t;
typedef struct ProtocolExtensionContainer_128P94 {
	A_SEQUENCE_OF(struct SNSSAI_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P94_t;
typedef struct ProtocolExtensionContainer_128P95 {
	A_SEQUENCE_OF(struct SDAP_Configuration_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P95_t;
typedef struct ProtocolExtensionContainer_128P96 {
	A_SEQUENCE_OF(struct T_ReorderingTimer_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P96_t;
typedef struct ProtocolExtensionContainer_128P97 {
	A_SEQUENCE_OF(struct UE_associatedLogicalE1_ConnectionItemExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P97_t;
typedef struct ProtocolExtensionContainer_128P98 {
	A_SEQUENCE_OF(struct UP_Parameters_Item_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P98_t;
typedef struct ProtocolExtensionContainer_128P99 {
	A_SEQUENCE_OF(struct UPSecuritykey_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P99_t;
typedef struct ProtocolExtensionContainer_128P100 {
	A_SEQUENCE_OF(struct UplinkOnlyROHC_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P100_t;
typedef struct ProtocolExtensionContainer_128P101 {
	A_SEQUENCE_OF(struct SupportedPLMNs_ExtIEs) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ProtocolExtensionContainer_128P101_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P0;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P0_specs_1;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P0_1[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P0_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P1;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P1_specs_3;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P1_3[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P1_constr_3;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P2;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P2_specs_5;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P2_5[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P2_constr_5;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P3;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P3_specs_7;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P3_7[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P3_constr_7;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P4;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P4_specs_9;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P4_9[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P4_constr_9;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P5;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P5_specs_11;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P5_11[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P5_constr_11;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P6;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P6_specs_13;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P6_13[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P6_constr_13;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P7;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P7_specs_15;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P7_15[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P7_constr_15;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P8;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P8_specs_17;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P8_17[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P8_constr_17;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P9;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P9_specs_19;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P9_19[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P9_constr_19;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P10;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P10_specs_21;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P10_21[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P10_constr_21;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P11;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P11_specs_23;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P11_23[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P11_constr_23;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P12;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P12_specs_25;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P12_25[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P12_constr_25;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P13;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P13_specs_27;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P13_27[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P13_constr_27;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P14;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P14_specs_29;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P14_29[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P14_constr_29;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P15;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P15_specs_31;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P15_31[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P15_constr_31;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P16;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P16_specs_33;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P16_33[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P16_constr_33;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P17;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P17_specs_35;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P17_35[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P17_constr_35;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P18;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P18_specs_37;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P18_37[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P18_constr_37;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P19;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P19_specs_39;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P19_39[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P19_constr_39;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P20;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P20_specs_41;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P20_41[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P20_constr_41;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P21;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P21_specs_43;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P21_43[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P21_constr_43;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P22;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P22_specs_45;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P22_45[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P22_constr_45;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P23;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P23_specs_47;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P23_47[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P23_constr_47;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P24;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P24_specs_49;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P24_49[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P24_constr_49;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P25;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P25_specs_51;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P25_51[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P25_constr_51;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P26;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P26_specs_53;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P26_53[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P26_constr_53;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P27;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P27_specs_55;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P27_55[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P27_constr_55;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P28;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P28_specs_57;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P28_57[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P28_constr_57;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P29;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P29_specs_59;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P29_59[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P29_constr_59;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P30;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P30_specs_61;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P30_61[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P30_constr_61;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P31;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P31_specs_63;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P31_63[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P31_constr_63;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P32;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P32_specs_65;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P32_65[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P32_constr_65;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P33;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P33_specs_67;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P33_67[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P33_constr_67;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P34;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P34_specs_69;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P34_69[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P34_constr_69;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P35;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P35_specs_71;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P35_71[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P35_constr_71;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P36;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P36_specs_73;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P36_73[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P36_constr_73;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P37;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P37_specs_75;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P37_75[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P37_constr_75;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P38;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P38_specs_77;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P38_77[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P38_constr_77;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P39;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P39_specs_79;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P39_79[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P39_constr_79;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P40;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P40_specs_81;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P40_81[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P40_constr_81;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P41;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P41_specs_83;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P41_83[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P41_constr_83;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P42;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P42_specs_85;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P42_85[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P42_constr_85;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P43;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P43_specs_87;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P43_87[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P43_constr_87;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P44;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P44_specs_89;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P44_89[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P44_constr_89;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P45;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P45_specs_91;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P45_91[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P45_constr_91;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P46;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P46_specs_93;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P46_93[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P46_constr_93;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P47;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P47_specs_95;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P47_95[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P47_constr_95;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P48;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P48_specs_97;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P48_97[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P48_constr_97;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P49;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P49_specs_99;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P49_99[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P49_constr_99;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P50;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P50_specs_101;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P50_101[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P50_constr_101;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P51;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P51_specs_103;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P51_103[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P51_constr_103;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P52;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P52_specs_105;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P52_105[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P52_constr_105;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P53;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P53_specs_107;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P53_107[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P53_constr_107;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P54;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P54_specs_109;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P54_109[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P54_constr_109;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P55;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P55_specs_111;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P55_111[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P55_constr_111;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P56;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P56_specs_113;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P56_113[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P56_constr_113;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P57;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P57_specs_115;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P57_115[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P57_constr_115;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P58;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P58_specs_117;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P58_117[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P58_constr_117;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P59;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P59_specs_119;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P59_119[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P59_constr_119;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P60;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P60_specs_121;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P60_121[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P60_constr_121;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P61;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P61_specs_123;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P61_123[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P61_constr_123;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P62;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P62_specs_125;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P62_125[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P62_constr_125;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P63;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P63_specs_127;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P63_127[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P63_constr_127;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P64;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P64_specs_129;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P64_129[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P64_constr_129;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P65;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P65_specs_131;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P65_131[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P65_constr_131;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P66;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P66_specs_133;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P66_133[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P66_constr_133;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P67;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P67_specs_135;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P67_135[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P67_constr_135;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P68;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P68_specs_137;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P68_137[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P68_constr_137;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P69;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P69_specs_139;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P69_139[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P69_constr_139;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P70;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P70_specs_141;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P70_141[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P70_constr_141;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P71;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P71_specs_143;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P71_143[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P71_constr_143;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P72;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P72_specs_145;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P72_145[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P72_constr_145;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P73;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P73_specs_147;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P73_147[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P73_constr_147;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P74;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P74_specs_149;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P74_149[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P74_constr_149;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P75;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P75_specs_151;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P75_151[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P75_constr_151;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P76;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P76_specs_153;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P76_153[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P76_constr_153;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P77;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P77_specs_155;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P77_155[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P77_constr_155;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P78;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P78_specs_157;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P78_157[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P78_constr_157;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P79;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P79_specs_159;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P79_159[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P79_constr_159;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P80;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P80_specs_161;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P80_161[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P80_constr_161;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P81;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P81_specs_163;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P81_163[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P81_constr_163;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P82;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P82_specs_165;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P82_165[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P82_constr_165;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P83;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P83_specs_167;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P83_167[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P83_constr_167;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P84;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P84_specs_169;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P84_169[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P84_constr_169;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P85;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P85_specs_171;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P85_171[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P85_constr_171;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P86;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P86_specs_173;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P86_173[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P86_constr_173;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P87;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P87_specs_175;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P87_175[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P87_constr_175;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P88;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P88_specs_177;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P88_177[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P88_constr_177;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P89;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P89_specs_179;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P89_179[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P89_constr_179;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P90;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P90_specs_181;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P90_181[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P90_constr_181;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P91;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P91_specs_183;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P91_183[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P91_constr_183;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P92;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P92_specs_185;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P92_185[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P92_constr_185;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P93;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P93_specs_187;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P93_187[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P93_constr_187;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P94;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P94_specs_189;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P94_189[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P94_constr_189;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P95;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P95_specs_191;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P95_191[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P95_constr_191;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P96;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P96_specs_193;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P96_193[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P96_constr_193;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P97;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P97_specs_195;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P97_195[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P97_constr_195;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P98;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P98_specs_197;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P98_197[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P98_constr_197;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P99;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P99_specs_199;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P99_199[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P99_constr_199;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P100;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P100_specs_201;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P100_201[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P100_constr_201;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolExtensionContainer_128P101;
extern asn_SET_OF_specifics_t asn_SPC_ProtocolExtensionContainer_128P101_specs_203;
extern asn_TYPE_member_t asn_MBR_ProtocolExtensionContainer_128P101_203[1];
extern asn_per_constraints_t asn_PER_type_ProtocolExtensionContainer_128P101_constr_203;

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolExtensionContainer_H_ */
#include <asn_internal.h>
