/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-CommonDataTypes"
 * 	found in "E1AP-CommonDataTypes.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_ProtocolIE_ID_H_
#define	_ProtocolIE_ID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ProtocolIE-ID */
typedef long	 ProtocolIE_ID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ProtocolIE_ID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ProtocolIE_ID;
asn_struct_free_f ProtocolIE_ID_free;
asn_struct_print_f ProtocolIE_ID_print;
asn_constr_check_f ProtocolIE_ID_constraint;
ber_type_decoder_f ProtocolIE_ID_decode_ber;
der_type_encoder_f ProtocolIE_ID_encode_der;
xer_type_decoder_f ProtocolIE_ID_decode_xer;
xer_type_encoder_f ProtocolIE_ID_encode_xer;
oer_type_decoder_f ProtocolIE_ID_decode_oer;
oer_type_encoder_f ProtocolIE_ID_encode_oer;
per_type_decoder_f ProtocolIE_ID_decode_uper;
per_type_encoder_f ProtocolIE_ID_encode_uper;
per_type_decoder_f ProtocolIE_ID_decode_aper;
per_type_encoder_f ProtocolIE_ID_encode_aper;
#define ProtocolIE_ID_id_Cause	((ProtocolIE_ID_t)0)
#define ProtocolIE_ID_id_CriticalityDiagnostics	((ProtocolIE_ID_t)1)
#define ProtocolIE_ID_id_gNB_CU_CP_UE_E1AP_ID	((ProtocolIE_ID_t)2)
#define ProtocolIE_ID_id_gNB_CU_UP_UE_E1AP_ID	((ProtocolIE_ID_t)3)
#define ProtocolIE_ID_id_ResetType	((ProtocolIE_ID_t)4)
#define ProtocolIE_ID_id_UE_associatedLogicalE1_ConnectionItem	((ProtocolIE_ID_t)5)
#define ProtocolIE_ID_id_UE_associatedLogicalE1_ConnectionListResAck	((ProtocolIE_ID_t)6)
#define ProtocolIE_ID_id_gNB_CU_UP_ID	((ProtocolIE_ID_t)7)
#define ProtocolIE_ID_id_gNB_CU_UP_Name	((ProtocolIE_ID_t)8)
#define ProtocolIE_ID_id_gNB_CU_CP_Name	((ProtocolIE_ID_t)9)
#define ProtocolIE_ID_id_CNSupport	((ProtocolIE_ID_t)10)
#define ProtocolIE_ID_id_SupportedPLMNs	((ProtocolIE_ID_t)11)
#define ProtocolIE_ID_id_TimeToWait	((ProtocolIE_ID_t)12)
#define ProtocolIE_ID_id_SecurityInformation	((ProtocolIE_ID_t)13)
#define ProtocolIE_ID_id_UEDLAggregateMaximumBitRate	((ProtocolIE_ID_t)14)
#define ProtocolIE_ID_id_System_BearerContextSetupRequest	((ProtocolIE_ID_t)15)
#define ProtocolIE_ID_id_System_BearerContextSetupResponse	((ProtocolIE_ID_t)16)
#define ProtocolIE_ID_id_BearerContextStatusChange	((ProtocolIE_ID_t)17)
#define ProtocolIE_ID_id_System_BearerContextModificationRequest	((ProtocolIE_ID_t)18)
#define ProtocolIE_ID_id_System_BearerContextModificationResponse	((ProtocolIE_ID_t)19)
#define ProtocolIE_ID_id_System_BearerContextModificationConfirm	((ProtocolIE_ID_t)20)
#define ProtocolIE_ID_id_System_BearerContextModificationRequired	((ProtocolIE_ID_t)21)
#define ProtocolIE_ID_id_DRB_Status_List	((ProtocolIE_ID_t)22)
#define ProtocolIE_ID_id_ActivityNotificationLevel	((ProtocolIE_ID_t)23)
#define ProtocolIE_ID_id_ActivityInformation	((ProtocolIE_ID_t)24)
#define ProtocolIE_ID_id_Data_Usage_Report_List	((ProtocolIE_ID_t)25)
#define ProtocolIE_ID_id_New_UL_TNL_Information_Required	((ProtocolIE_ID_t)26)
#define ProtocolIE_ID_id_GNB_CU_CP_TNLA_To_Add_List	((ProtocolIE_ID_t)27)
#define ProtocolIE_ID_id_GNB_CU_CP_TNLA_To_Remove_List	((ProtocolIE_ID_t)28)
#define ProtocolIE_ID_id_GNB_CU_CP_TNLA_To_Update_List	((ProtocolIE_ID_t)29)
#define ProtocolIE_ID_id_GNB_CU_CP_TNLA_Setup_List	((ProtocolIE_ID_t)30)
#define ProtocolIE_ID_id_GNB_CU_CP_TNLA_Failed_To_Setup_List	((ProtocolIE_ID_t)31)
#define ProtocolIE_ID_id_DRB_To_Setup_List_EUTRAN	((ProtocolIE_ID_t)32)
#define ProtocolIE_ID_id_DRB_To_Modify_List_EUTRAN	((ProtocolIE_ID_t)33)
#define ProtocolIE_ID_id_DRB_To_Remove_List_EUTRAN	((ProtocolIE_ID_t)34)
#define ProtocolIE_ID_id_DRB_Required_To_Modify_List_EUTRAN	((ProtocolIE_ID_t)35)
#define ProtocolIE_ID_id_DRB_Required_To_Remove_List_EUTRAN	((ProtocolIE_ID_t)36)
#define ProtocolIE_ID_id_DRB_Setup_List_EUTRAN	((ProtocolIE_ID_t)37)
#define ProtocolIE_ID_id_DRB_Failed_List_EUTRAN	((ProtocolIE_ID_t)38)
#define ProtocolIE_ID_id_DRB_Modified_List_EUTRAN	((ProtocolIE_ID_t)39)
#define ProtocolIE_ID_id_DRB_Failed_To_Modify_List_EUTRAN	((ProtocolIE_ID_t)40)
#define ProtocolIE_ID_id_DRB_Confirm_Modified_List_EUTRAN	((ProtocolIE_ID_t)41)
#define ProtocolIE_ID_id_PDU_Session_Resource_To_Setup_List	((ProtocolIE_ID_t)42)
#define ProtocolIE_ID_id_PDU_Session_Resource_To_Modify_List	((ProtocolIE_ID_t)43)
#define ProtocolIE_ID_id_PDU_Session_Resource_To_Remove_List	((ProtocolIE_ID_t)44)
#define ProtocolIE_ID_id_PDU_Session_Resource_Required_To_Modify_List	((ProtocolIE_ID_t)45)
#define ProtocolIE_ID_id_PDU_Session_Resource_Setup_List	((ProtocolIE_ID_t)46)
#define ProtocolIE_ID_id_PDU_Session_Resource_Failed_List	((ProtocolIE_ID_t)47)
#define ProtocolIE_ID_id_PDU_Session_Resource_Modified_List	((ProtocolIE_ID_t)48)
#define ProtocolIE_ID_id_PDU_Session_Resource_Failed_To_Modify_List	((ProtocolIE_ID_t)49)
#define ProtocolIE_ID_id_PDU_Session_Resource_Confirm_Modified_List	((ProtocolIE_ID_t)50)
#define ProtocolIE_ID_id_DRB_To_Setup_Mod_List_EUTRAN	((ProtocolIE_ID_t)51)
#define ProtocolIE_ID_id_DRB_Setup_Mod_List_EUTRAN	((ProtocolIE_ID_t)52)
#define ProtocolIE_ID_id_DRB_Failed_Mod_List_EUTRAN	((ProtocolIE_ID_t)53)
#define ProtocolIE_ID_id_PDU_Session_Resource_Setup_Mod_List	((ProtocolIE_ID_t)54)
#define ProtocolIE_ID_id_PDU_Session_Resource_Failed_Mod_List	((ProtocolIE_ID_t)55)
#define ProtocolIE_ID_id_PDU_Session_Resource_To_Setup_Mod_List	((ProtocolIE_ID_t)56)
#define ProtocolIE_ID_id_TransactionID	((ProtocolIE_ID_t)57)
#define ProtocolIE_ID_id_Serving_PLMN	((ProtocolIE_ID_t)58)
#define ProtocolIE_ID_id_UE_Inactivity_Timer	((ProtocolIE_ID_t)59)
#define ProtocolIE_ID_id_System_GNB_CU_UP_CounterCheckRequest	((ProtocolIE_ID_t)60)
#define ProtocolIE_ID_id_DRBs_Subject_To_Counter_Check_List_EUTRAN	((ProtocolIE_ID_t)61)
#define ProtocolIE_ID_id_DRBs_Subject_To_Counter_Check_List_NG_RAN	((ProtocolIE_ID_t)62)
#define ProtocolIE_ID_id_PPI	((ProtocolIE_ID_t)63)
#define ProtocolIE_ID_id_gNB_CU_UP_Capacity	((ProtocolIE_ID_t)64)
#define ProtocolIE_ID_id_GNB_CU_UP_OverloadInformation	((ProtocolIE_ID_t)65)
#define ProtocolIE_ID_id_UEDLMaximumIntegrityProtectedDataRate	((ProtocolIE_ID_t)66)
#define ProtocolIE_ID_id_PDU_Session_To_Notify_List	((ProtocolIE_ID_t)67)
#define ProtocolIE_ID_id_PDU_Session_Resource_Data_Usage_List	((ProtocolIE_ID_t)68)
#define ProtocolIE_ID_id_SNSSAI	((ProtocolIE_ID_t)69)
#define ProtocolIE_ID_id_DataDiscardRequired	((ProtocolIE_ID_t)70)
#define ProtocolIE_ID_id_OldQoSFlowMap_ULendmarkerexpected	((ProtocolIE_ID_t)71)
#define ProtocolIE_ID_id_DRB_QoS	((ProtocolIE_ID_t)72)
#define ProtocolIE_ID_id_GNB_CU_UP_TNLA_To_Remove_List	((ProtocolIE_ID_t)73)
#define ProtocolIE_ID_id_endpoint_IP_Address_and_Port	((ProtocolIE_ID_t)74)
#define ProtocolIE_ID_id_TNLAssociationTransportLayerAddressgNBCUUP	((ProtocolIE_ID_t)75)
#define ProtocolIE_ID_id_RANUEID	((ProtocolIE_ID_t)76)
#define ProtocolIE_ID_id_GNB_DU_ID	((ProtocolIE_ID_t)77)
#define ProtocolIE_ID_id_CommonNetworkInstance	((ProtocolIE_ID_t)78)
#define ProtocolIE_ID_id_NetworkInstance	((ProtocolIE_ID_t)79)
#define ProtocolIE_ID_id_QoSFlowMappingIndication	((ProtocolIE_ID_t)80)

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolIE_ID_H_ */
#include <asn_internal.h>
