/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-Containers"
 * 	found in "E1AP-Containers.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_ProtocolIE_Field_H_
#define	_ProtocolIE_Field_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProtocolIE-ID.h"
#include "Criticality.h"
#include <ANY.h>
#include <asn_ioc.h>
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>
#include "Endpoint-IP-address-and-port.h"
#include "Presence.h"
#include "UE-associatedLogicalE1-ConnectionItem.h"
#include "TransactionID.h"
#include "Cause.h"
#include "ResetType.h"
#include "UE-associatedLogicalE1-ConnectionListResAck.h"
#include "CriticalityDiagnostics.h"
#include "GNB-CU-CP-UE-E1AP-ID.h"
#include "GNB-CU-UP-UE-E1AP-ID.h"
#include "GNB-CU-UP-ID.h"
#include "GNB-CU-UP-Name.h"
#include "CNSupport.h"
#include "SupportedPLMNs-List.h"
#include "GNB-CU-UP-Capacity.h"
#include "GNB-CU-CP-Name.h"
#include "TimeToWait.h"
#include "GNB-CU-UP-TNLA-To-Remove-List.h"
#include "GNB-CU-CP-TNLA-To-Add-List.h"
#include "GNB-CU-CP-TNLA-To-Remove-List.h"
#include "GNB-CU-CP-TNLA-To-Update-List.h"
#include "GNB-CU-CP-TNLA-Setup-List.h"
#include "GNB-CU-CP-TNLA-Failed-To-Setup-List.h"
#include "SecurityInformation.h"
#include "BitRate.h"
#include "PLMN-Identity.h"
#include "ActivityNotificationLevel.h"
#include "Inactivity-Timer.h"
#include "BearerContextStatusChange.h"
#include "System-BearerContextSetupRequest.h"
#include "RANUEID.h"
#include "GNB-DU-ID.h"
#include "DRB-To-Setup-List-EUTRAN.h"
#include "PDU-Session-Resource-To-Setup-List.h"
#include "System-BearerContextSetupResponse.h"
#include "DRB-Setup-List-EUTRAN.h"
#include "DRB-Failed-List-EUTRAN.h"
#include "PDU-Session-Resource-Setup-List.h"
#include "PDU-Session-Resource-Failed-List.h"
#include "New-UL-TNL-Information-Required.h"
#include "DataDiscardRequired.h"
#include "System-BearerContextModificationRequest.h"
#include "DRB-To-Setup-Mod-List-EUTRAN.h"
#include "DRB-To-Modify-List-EUTRAN.h"
#include "DRB-To-Remove-List-EUTRAN.h"
#include "PDU-Session-Resource-To-Setup-Mod-List.h"
#include "PDU-Session-Resource-To-Modify-List.h"
#include "PDU-Session-Resource-To-Remove-List.h"
#include "System-BearerContextModificationResponse.h"
#include "DRB-Setup-Mod-List-EUTRAN.h"
#include "DRB-Failed-Mod-List-EUTRAN.h"
#include "DRB-Modified-List-EUTRAN.h"
#include "DRB-Failed-To-Modify-List-EUTRAN.h"
#include "PDU-Session-Resource-Setup-Mod-List.h"
#include "PDU-Session-Resource-Failed-Mod-List.h"
#include "PDU-Session-Resource-Modified-List.h"
#include "PDU-Session-Resource-Failed-To-Modify-List.h"
#include "System-BearerContextModificationRequired.h"
#include "DRB-Required-To-Modify-List-EUTRAN.h"
#include "DRB-Required-To-Remove-List-EUTRAN.h"
#include "PDU-Session-Resource-Required-To-Modify-List.h"
#include "System-BearerContextModificationConfirm.h"
#include "DRB-Confirm-Modified-List-EUTRAN.h"
#include "PDU-Session-Resource-Confirm-Modified-List.h"
#include "DRB-Status-List.h"
#include "ActivityInformation.h"
#include "PPI.h"
#include "PDU-Session-To-Notify-List.h"
#include "Data-Usage-Report-List.h"
#include "System-GNB-CU-UP-CounterCheckRequest.h"
#include "DRBs-Subject-To-Counter-Check-List-EUTRAN.h"
#include "DRBs-Subject-To-Counter-Check-List-NG-RAN.h"
#include "GNB-CU-UP-OverloadInformation.h"
#include "PDU-Session-Resource-Data-Usage-List.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ActivityInformation_ExtIEs__value_PR {
	ActivityInformation_ExtIEs__value_PR_NOTHING	/* No components present */
	
} ActivityInformation_ExtIEs__value_PR;
typedef enum Cause_ExtIEs__value_PR {
	Cause_ExtIEs__value_PR_NOTHING	/* No components present */
	
} Cause_ExtIEs__value_PR;
typedef enum CP_TNL_Information_ExtIEs__value_PR {
	CP_TNL_Information_ExtIEs__value_PR_NOTHING,	/* No components present */
	CP_TNL_Information_ExtIEs__value_PR_Endpoint_IP_address_and_port
} CP_TNL_Information_ExtIEs__value_PR;
typedef enum QoS_Characteristics_ExtIEs__value_PR {
	QoS_Characteristics_ExtIEs__value_PR_NOTHING	/* No components present */
	
} QoS_Characteristics_ExtIEs__value_PR;
typedef enum ROHC_Parameters_ExtIEs__value_PR {
	ROHC_Parameters_ExtIEs__value_PR_NOTHING	/* No components present */
	
} ROHC_Parameters_ExtIEs__value_PR;
typedef enum UP_TNL_Information_ExtIEs__value_PR {
	UP_TNL_Information_ExtIEs__value_PR_NOTHING	/* No components present */
	
} UP_TNL_Information_ExtIEs__value_PR;
typedef enum ResetType_ExtIEs__value_PR {
	ResetType_ExtIEs__value_PR_NOTHING	/* No components present */
	
} ResetType_ExtIEs__value_PR;
typedef enum UE_associatedLogicalE1_ConnectionItemResIEs__value_PR {
	UE_associatedLogicalE1_ConnectionItemResIEs__value_PR_NOTHING,	/* No components present */
	UE_associatedLogicalE1_ConnectionItemResIEs__value_PR_UE_associatedLogicalE1_ConnectionItem
} UE_associatedLogicalE1_ConnectionItemResIEs__value_PR;
typedef enum UE_associatedLogicalE1_ConnectionItemResIEsAckIEs__value_PR {
	UE_associatedLogicalE1_ConnectionItemResIEsAckIEs__value_PR_NOTHING,	/* No components present */
	UE_associatedLogicalE1_ConnectionItemResIEsAckIEs__value_PR_UE_associatedLogicalE1_ConnectionItem
} UE_associatedLogicalE1_ConnectionItemResIEsAckIEs__value_PR;
typedef enum System_BearerContextSetupRequest_ExtIEs__value_PR {
	System_BearerContextSetupRequest_ExtIEs__value_PR_NOTHING	/* No components present */
	
} System_BearerContextSetupRequest_ExtIEs__value_PR;
typedef enum System_BearerContextSetupResponse_ExtIEs__value_PR {
	System_BearerContextSetupResponse_ExtIEs__value_PR_NOTHING	/* No components present */
	
} System_BearerContextSetupResponse_ExtIEs__value_PR;
typedef enum System_BearerContextModificationRequest_ExtIEs__value_PR {
	System_BearerContextModificationRequest_ExtIEs__value_PR_NOTHING	/* No components present */
	
} System_BearerContextModificationRequest_ExtIEs__value_PR;
typedef enum System_BearerContextModificationResponse_ExtIEs__value_PR {
	System_BearerContextModificationResponse_ExtIEs__value_PR_NOTHING	/* No components present */
	
} System_BearerContextModificationResponse_ExtIEs__value_PR;
typedef enum System_BearerContextModificationRequired_ExtIEs__value_PR {
	System_BearerContextModificationRequired_ExtIEs__value_PR_NOTHING	/* No components present */
	
} System_BearerContextModificationRequired_ExtIEs__value_PR;
typedef enum System_BearerContextModificationConfirm_ExtIEs__value_PR {
	System_BearerContextModificationConfirm_ExtIEs__value_PR_NOTHING	/* No components present */
	
} System_BearerContextModificationConfirm_ExtIEs__value_PR;
typedef enum System_GNB_CU_UP_CounterCheckRequest_ExtIEs__value_PR {
	System_GNB_CU_UP_CounterCheckRequest_ExtIEs__value_PR_NOTHING	/* No components present */
	
} System_GNB_CU_UP_CounterCheckRequest_ExtIEs__value_PR;
typedef enum ResetIEs__value_PR {
	ResetIEs__value_PR_NOTHING,	/* No components present */
	ResetIEs__value_PR_TransactionID,
	ResetIEs__value_PR_Cause,
	ResetIEs__value_PR_ResetType
} ResetIEs__value_PR;
typedef enum ResetAcknowledgeIEs__value_PR {
	ResetAcknowledgeIEs__value_PR_NOTHING,	/* No components present */
	ResetAcknowledgeIEs__value_PR_TransactionID,
	ResetAcknowledgeIEs__value_PR_UE_associatedLogicalE1_ConnectionListResAck,
	ResetAcknowledgeIEs__value_PR_CriticalityDiagnostics
} ResetAcknowledgeIEs__value_PR;
typedef enum ErrorIndication_IEs__value_PR {
	ErrorIndication_IEs__value_PR_NOTHING,	/* No components present */
	ErrorIndication_IEs__value_PR_TransactionID,
	ErrorIndication_IEs__value_PR_GNB_CU_CP_UE_E1AP_ID,
	ErrorIndication_IEs__value_PR_GNB_CU_UP_UE_E1AP_ID,
	ErrorIndication_IEs__value_PR_Cause,
	ErrorIndication_IEs__value_PR_CriticalityDiagnostics
} ErrorIndication_IEs__value_PR;
typedef enum GNB_CU_UP_E1SetupRequestIEs__value_PR {
	GNB_CU_UP_E1SetupRequestIEs__value_PR_NOTHING,	/* No components present */
	GNB_CU_UP_E1SetupRequestIEs__value_PR_TransactionID,
	GNB_CU_UP_E1SetupRequestIEs__value_PR_GNB_CU_UP_ID,
	GNB_CU_UP_E1SetupRequestIEs__value_PR_GNB_CU_UP_Name,
	GNB_CU_UP_E1SetupRequestIEs__value_PR_CNSupport,
	GNB_CU_UP_E1SetupRequestIEs__value_PR_SupportedPLMNs_List,
	GNB_CU_UP_E1SetupRequestIEs__value_PR_GNB_CU_UP_Capacity
} GNB_CU_UP_E1SetupRequestIEs__value_PR;
typedef enum GNB_CU_UP_E1SetupResponseIEs__value_PR {
	GNB_CU_UP_E1SetupResponseIEs__value_PR_NOTHING,	/* No components present */
	GNB_CU_UP_E1SetupResponseIEs__value_PR_TransactionID,
	GNB_CU_UP_E1SetupResponseIEs__value_PR_GNB_CU_CP_Name
} GNB_CU_UP_E1SetupResponseIEs__value_PR;
typedef enum GNB_CU_UP_E1SetupFailureIEs__value_PR {
	GNB_CU_UP_E1SetupFailureIEs__value_PR_NOTHING,	/* No components present */
	GNB_CU_UP_E1SetupFailureIEs__value_PR_TransactionID,
	GNB_CU_UP_E1SetupFailureIEs__value_PR_Cause,
	GNB_CU_UP_E1SetupFailureIEs__value_PR_TimeToWait,
	GNB_CU_UP_E1SetupFailureIEs__value_PR_CriticalityDiagnostics
} GNB_CU_UP_E1SetupFailureIEs__value_PR;
typedef enum GNB_CU_CP_E1SetupRequestIEs__value_PR {
	GNB_CU_CP_E1SetupRequestIEs__value_PR_NOTHING,	/* No components present */
	GNB_CU_CP_E1SetupRequestIEs__value_PR_TransactionID,
	GNB_CU_CP_E1SetupRequestIEs__value_PR_GNB_CU_CP_Name
} GNB_CU_CP_E1SetupRequestIEs__value_PR;
typedef enum GNB_CU_CP_E1SetupResponseIEs__value_PR {
	GNB_CU_CP_E1SetupResponseIEs__value_PR_NOTHING,	/* No components present */
	GNB_CU_CP_E1SetupResponseIEs__value_PR_TransactionID,
	GNB_CU_CP_E1SetupResponseIEs__value_PR_GNB_CU_UP_ID,
	GNB_CU_CP_E1SetupResponseIEs__value_PR_GNB_CU_UP_Name,
	GNB_CU_CP_E1SetupResponseIEs__value_PR_CNSupport,
	GNB_CU_CP_E1SetupResponseIEs__value_PR_SupportedPLMNs_List,
	GNB_CU_CP_E1SetupResponseIEs__value_PR_GNB_CU_UP_Capacity
} GNB_CU_CP_E1SetupResponseIEs__value_PR;
typedef enum GNB_CU_CP_E1SetupFailureIEs__value_PR {
	GNB_CU_CP_E1SetupFailureIEs__value_PR_NOTHING,	/* No components present */
	GNB_CU_CP_E1SetupFailureIEs__value_PR_TransactionID,
	GNB_CU_CP_E1SetupFailureIEs__value_PR_Cause,
	GNB_CU_CP_E1SetupFailureIEs__value_PR_TimeToWait,
	GNB_CU_CP_E1SetupFailureIEs__value_PR_CriticalityDiagnostics
} GNB_CU_CP_E1SetupFailureIEs__value_PR;
typedef enum GNB_CU_UP_ConfigurationUpdateIEs__value_PR {
	GNB_CU_UP_ConfigurationUpdateIEs__value_PR_NOTHING,	/* No components present */
	GNB_CU_UP_ConfigurationUpdateIEs__value_PR_TransactionID,
	GNB_CU_UP_ConfigurationUpdateIEs__value_PR_GNB_CU_UP_ID,
	GNB_CU_UP_ConfigurationUpdateIEs__value_PR_GNB_CU_UP_Name,
	GNB_CU_UP_ConfigurationUpdateIEs__value_PR_SupportedPLMNs_List,
	GNB_CU_UP_ConfigurationUpdateIEs__value_PR_GNB_CU_UP_Capacity,
	GNB_CU_UP_ConfigurationUpdateIEs__value_PR_GNB_CU_UP_TNLA_To_Remove_List
} GNB_CU_UP_ConfigurationUpdateIEs__value_PR;
typedef enum GNB_CU_UP_ConfigurationUpdateAcknowledgeIEs__value_PR {
	GNB_CU_UP_ConfigurationUpdateAcknowledgeIEs__value_PR_NOTHING,	/* No components present */
	GNB_CU_UP_ConfigurationUpdateAcknowledgeIEs__value_PR_TransactionID,
	GNB_CU_UP_ConfigurationUpdateAcknowledgeIEs__value_PR_CriticalityDiagnostics
} GNB_CU_UP_ConfigurationUpdateAcknowledgeIEs__value_PR;
typedef enum GNB_CU_UP_ConfigurationUpdateFailureIEs__value_PR {
	GNB_CU_UP_ConfigurationUpdateFailureIEs__value_PR_NOTHING,	/* No components present */
	GNB_CU_UP_ConfigurationUpdateFailureIEs__value_PR_TransactionID,
	GNB_CU_UP_ConfigurationUpdateFailureIEs__value_PR_Cause,
	GNB_CU_UP_ConfigurationUpdateFailureIEs__value_PR_TimeToWait,
	GNB_CU_UP_ConfigurationUpdateFailureIEs__value_PR_CriticalityDiagnostics
} GNB_CU_UP_ConfigurationUpdateFailureIEs__value_PR;
typedef enum GNB_CU_CP_ConfigurationUpdateIEs__value_PR {
	GNB_CU_CP_ConfigurationUpdateIEs__value_PR_NOTHING,	/* No components present */
	GNB_CU_CP_ConfigurationUpdateIEs__value_PR_TransactionID,
	GNB_CU_CP_ConfigurationUpdateIEs__value_PR_GNB_CU_UP_Name,
	GNB_CU_CP_ConfigurationUpdateIEs__value_PR_GNB_CU_CP_TNLA_To_Add_List,
	GNB_CU_CP_ConfigurationUpdateIEs__value_PR_GNB_CU_CP_TNLA_To_Remove_List,
	GNB_CU_CP_ConfigurationUpdateIEs__value_PR_GNB_CU_CP_TNLA_To_Update_List
} GNB_CU_CP_ConfigurationUpdateIEs__value_PR;
typedef enum GNB_CU_CP_ConfigurationUpdateAcknowledgeIEs__value_PR {
	GNB_CU_CP_ConfigurationUpdateAcknowledgeIEs__value_PR_NOTHING,	/* No components present */
	GNB_CU_CP_ConfigurationUpdateAcknowledgeIEs__value_PR_TransactionID,
	GNB_CU_CP_ConfigurationUpdateAcknowledgeIEs__value_PR_CriticalityDiagnostics,
	GNB_CU_CP_ConfigurationUpdateAcknowledgeIEs__value_PR_GNB_CU_CP_TNLA_Setup_List,
	GNB_CU_CP_ConfigurationUpdateAcknowledgeIEs__value_PR_GNB_CU_CP_TNLA_Failed_To_Setup_List
} GNB_CU_CP_ConfigurationUpdateAcknowledgeIEs__value_PR;
typedef enum GNB_CU_CP_ConfigurationUpdateFailureIEs__value_PR {
	GNB_CU_CP_ConfigurationUpdateFailureIEs__value_PR_NOTHING,	/* No components present */
	GNB_CU_CP_ConfigurationUpdateFailureIEs__value_PR_TransactionID,
	GNB_CU_CP_ConfigurationUpdateFailureIEs__value_PR_Cause,
	GNB_CU_CP_ConfigurationUpdateFailureIEs__value_PR_TimeToWait,
	GNB_CU_CP_ConfigurationUpdateFailureIEs__value_PR_CriticalityDiagnostics
} GNB_CU_CP_ConfigurationUpdateFailureIEs__value_PR;
typedef enum E1ReleaseRequestIEs__value_PR {
	E1ReleaseRequestIEs__value_PR_NOTHING,	/* No components present */
	E1ReleaseRequestIEs__value_PR_TransactionID,
	E1ReleaseRequestIEs__value_PR_Cause
} E1ReleaseRequestIEs__value_PR;
typedef enum E1ReleaseResponseIEs__value_PR {
	E1ReleaseResponseIEs__value_PR_NOTHING,	/* No components present */
	E1ReleaseResponseIEs__value_PR_TransactionID
} E1ReleaseResponseIEs__value_PR;
typedef enum BearerContextSetupRequestIEs__value_PR {
	BearerContextSetupRequestIEs__value_PR_NOTHING,	/* No components present */
	BearerContextSetupRequestIEs__value_PR_GNB_CU_CP_UE_E1AP_ID,
	BearerContextSetupRequestIEs__value_PR_SecurityInformation,
	BearerContextSetupRequestIEs__value_PR_BitRate,
	BearerContextSetupRequestIEs__value_PR_PLMN_Identity,
	BearerContextSetupRequestIEs__value_PR_ActivityNotificationLevel,
	BearerContextSetupRequestIEs__value_PR_Inactivity_Timer,
	BearerContextSetupRequestIEs__value_PR_BearerContextStatusChange,
	BearerContextSetupRequestIEs__value_PR_System_BearerContextSetupRequest,
	BearerContextSetupRequestIEs__value_PR_RANUEID,
	BearerContextSetupRequestIEs__value_PR_GNB_DU_ID
} BearerContextSetupRequestIEs__value_PR;
typedef enum EUTRAN_BearerContextSetupRequestIEs__value_PR {
	EUTRAN_BearerContextSetupRequestIEs__value_PR_NOTHING,	/* No components present */
	EUTRAN_BearerContextSetupRequestIEs__value_PR_DRB_To_Setup_List_EUTRAN
} EUTRAN_BearerContextSetupRequestIEs__value_PR;
typedef enum NG_RAN_BearerContextSetupRequestIEs__value_PR {
	NG_RAN_BearerContextSetupRequestIEs__value_PR_NOTHING,	/* No components present */
	NG_RAN_BearerContextSetupRequestIEs__value_PR_PDU_Session_Resource_To_Setup_List
} NG_RAN_BearerContextSetupRequestIEs__value_PR;
typedef enum BearerContextSetupResponseIEs__value_PR {
	BearerContextSetupResponseIEs__value_PR_NOTHING,	/* No components present */
	BearerContextSetupResponseIEs__value_PR_GNB_CU_CP_UE_E1AP_ID,
	BearerContextSetupResponseIEs__value_PR_GNB_CU_UP_UE_E1AP_ID,
	BearerContextSetupResponseIEs__value_PR_System_BearerContextSetupResponse
} BearerContextSetupResponseIEs__value_PR;
typedef enum EUTRAN_BearerContextSetupResponseIEs__value_PR {
	EUTRAN_BearerContextSetupResponseIEs__value_PR_NOTHING,	/* No components present */
	EUTRAN_BearerContextSetupResponseIEs__value_PR_DRB_Setup_List_EUTRAN,
	EUTRAN_BearerContextSetupResponseIEs__value_PR_DRB_Failed_List_EUTRAN
} EUTRAN_BearerContextSetupResponseIEs__value_PR;
typedef enum NG_RAN_BearerContextSetupResponseIEs__value_PR {
	NG_RAN_BearerContextSetupResponseIEs__value_PR_NOTHING,	/* No components present */
	NG_RAN_BearerContextSetupResponseIEs__value_PR_PDU_Session_Resource_Setup_List,
	NG_RAN_BearerContextSetupResponseIEs__value_PR_PDU_Session_Resource_Failed_List
} NG_RAN_BearerContextSetupResponseIEs__value_PR;
typedef enum BearerContextSetupFailureIEs__value_PR {
	BearerContextSetupFailureIEs__value_PR_NOTHING,	/* No components present */
	BearerContextSetupFailureIEs__value_PR_GNB_CU_CP_UE_E1AP_ID,
	BearerContextSetupFailureIEs__value_PR_GNB_CU_UP_UE_E1AP_ID,
	BearerContextSetupFailureIEs__value_PR_Cause,
	BearerContextSetupFailureIEs__value_PR_CriticalityDiagnostics
} BearerContextSetupFailureIEs__value_PR;
typedef enum BearerContextModificationRequestIEs__value_PR {
	BearerContextModificationRequestIEs__value_PR_NOTHING,	/* No components present */
	BearerContextModificationRequestIEs__value_PR_GNB_CU_CP_UE_E1AP_ID,
	BearerContextModificationRequestIEs__value_PR_GNB_CU_UP_UE_E1AP_ID,
	BearerContextModificationRequestIEs__value_PR_SecurityInformation,
	BearerContextModificationRequestIEs__value_PR_BitRate,
	BearerContextModificationRequestIEs__value_PR_BearerContextStatusChange,
	BearerContextModificationRequestIEs__value_PR_New_UL_TNL_Information_Required,
	BearerContextModificationRequestIEs__value_PR_Inactivity_Timer,
	BearerContextModificationRequestIEs__value_PR_DataDiscardRequired,
	BearerContextModificationRequestIEs__value_PR_System_BearerContextModificationRequest,
	BearerContextModificationRequestIEs__value_PR_RANUEID,
	BearerContextModificationRequestIEs__value_PR_GNB_DU_ID,
	BearerContextModificationRequestIEs__value_PR_ActivityNotificationLevel
} BearerContextModificationRequestIEs__value_PR;
typedef enum EUTRAN_BearerContextModificationRequestIEs__value_PR {
	EUTRAN_BearerContextModificationRequestIEs__value_PR_NOTHING,	/* No components present */
	EUTRAN_BearerContextModificationRequestIEs__value_PR_DRB_To_Setup_Mod_List_EUTRAN,
	EUTRAN_BearerContextModificationRequestIEs__value_PR_DRB_To_Modify_List_EUTRAN,
	EUTRAN_BearerContextModificationRequestIEs__value_PR_DRB_To_Remove_List_EUTRAN
} EUTRAN_BearerContextModificationRequestIEs__value_PR;
typedef enum NG_RAN_BearerContextModificationRequestIEs__value_PR {
	NG_RAN_BearerContextModificationRequestIEs__value_PR_NOTHING,	/* No components present */
	NG_RAN_BearerContextModificationRequestIEs__value_PR_PDU_Session_Resource_To_Setup_Mod_List,
	NG_RAN_BearerContextModificationRequestIEs__value_PR_PDU_Session_Resource_To_Modify_List,
	NG_RAN_BearerContextModificationRequestIEs__value_PR_PDU_Session_Resource_To_Remove_List
} NG_RAN_BearerContextModificationRequestIEs__value_PR;
typedef enum BearerContextModificationResponseIEs__value_PR {
	BearerContextModificationResponseIEs__value_PR_NOTHING,	/* No components present */
	BearerContextModificationResponseIEs__value_PR_GNB_CU_CP_UE_E1AP_ID,
	BearerContextModificationResponseIEs__value_PR_GNB_CU_UP_UE_E1AP_ID,
	BearerContextModificationResponseIEs__value_PR_System_BearerContextModificationResponse
} BearerContextModificationResponseIEs__value_PR;
typedef enum EUTRAN_BearerContextModificationResponseIEs__value_PR {
	EUTRAN_BearerContextModificationResponseIEs__value_PR_NOTHING,	/* No components present */
	EUTRAN_BearerContextModificationResponseIEs__value_PR_DRB_Setup_Mod_List_EUTRAN,
	EUTRAN_BearerContextModificationResponseIEs__value_PR_DRB_Failed_Mod_List_EUTRAN,
	EUTRAN_BearerContextModificationResponseIEs__value_PR_DRB_Modified_List_EUTRAN,
	EUTRAN_BearerContextModificationResponseIEs__value_PR_DRB_Failed_To_Modify_List_EUTRAN
} EUTRAN_BearerContextModificationResponseIEs__value_PR;
typedef enum NG_RAN_BearerContextModificationResponseIEs__value_PR {
	NG_RAN_BearerContextModificationResponseIEs__value_PR_NOTHING,	/* No components present */
	NG_RAN_BearerContextModificationResponseIEs__value_PR_PDU_Session_Resource_Setup_Mod_List,
	NG_RAN_BearerContextModificationResponseIEs__value_PR_PDU_Session_Resource_Failed_Mod_List,
	NG_RAN_BearerContextModificationResponseIEs__value_PR_PDU_Session_Resource_Modified_List,
	NG_RAN_BearerContextModificationResponseIEs__value_PR_PDU_Session_Resource_Failed_To_Modify_List
} NG_RAN_BearerContextModificationResponseIEs__value_PR;
typedef enum BearerContextModificationFailureIEs__value_PR {
	BearerContextModificationFailureIEs__value_PR_NOTHING,	/* No components present */
	BearerContextModificationFailureIEs__value_PR_GNB_CU_CP_UE_E1AP_ID,
	BearerContextModificationFailureIEs__value_PR_GNB_CU_UP_UE_E1AP_ID,
	BearerContextModificationFailureIEs__value_PR_Cause,
	BearerContextModificationFailureIEs__value_PR_CriticalityDiagnostics
} BearerContextModificationFailureIEs__value_PR;
typedef enum BearerContextModificationRequiredIEs__value_PR {
	BearerContextModificationRequiredIEs__value_PR_NOTHING,	/* No components present */
	BearerContextModificationRequiredIEs__value_PR_GNB_CU_CP_UE_E1AP_ID,
	BearerContextModificationRequiredIEs__value_PR_GNB_CU_UP_UE_E1AP_ID,
	BearerContextModificationRequiredIEs__value_PR_System_BearerContextModificationRequired
} BearerContextModificationRequiredIEs__value_PR;
typedef enum EUTRAN_BearerContextModificationRequiredIEs__value_PR {
	EUTRAN_BearerContextModificationRequiredIEs__value_PR_NOTHING,	/* No components present */
	EUTRAN_BearerContextModificationRequiredIEs__value_PR_DRB_Required_To_Modify_List_EUTRAN,
	EUTRAN_BearerContextModificationRequiredIEs__value_PR_DRB_Required_To_Remove_List_EUTRAN
} EUTRAN_BearerContextModificationRequiredIEs__value_PR;
typedef enum NG_RAN_BearerContextModificationRequiredIEs__value_PR {
	NG_RAN_BearerContextModificationRequiredIEs__value_PR_NOTHING,	/* No components present */
	NG_RAN_BearerContextModificationRequiredIEs__value_PR_PDU_Session_Resource_Required_To_Modify_List,
	NG_RAN_BearerContextModificationRequiredIEs__value_PR_PDU_Session_Resource_To_Remove_List
} NG_RAN_BearerContextModificationRequiredIEs__value_PR;
typedef enum BearerContextModificationConfirmIEs__value_PR {
	BearerContextModificationConfirmIEs__value_PR_NOTHING,	/* No components present */
	BearerContextModificationConfirmIEs__value_PR_GNB_CU_CP_UE_E1AP_ID,
	BearerContextModificationConfirmIEs__value_PR_GNB_CU_UP_UE_E1AP_ID,
	BearerContextModificationConfirmIEs__value_PR_System_BearerContextModificationConfirm
} BearerContextModificationConfirmIEs__value_PR;
typedef enum EUTRAN_BearerContextModificationConfirmIEs__value_PR {
	EUTRAN_BearerContextModificationConfirmIEs__value_PR_NOTHING,	/* No components present */
	EUTRAN_BearerContextModificationConfirmIEs__value_PR_DRB_Confirm_Modified_List_EUTRAN
} EUTRAN_BearerContextModificationConfirmIEs__value_PR;
typedef enum NG_RAN_BearerContextModificationConfirmIEs__value_PR {
	NG_RAN_BearerContextModificationConfirmIEs__value_PR_NOTHING,	/* No components present */
	NG_RAN_BearerContextModificationConfirmIEs__value_PR_PDU_Session_Resource_Confirm_Modified_List
} NG_RAN_BearerContextModificationConfirmIEs__value_PR;
typedef enum BearerContextReleaseCommandIEs__value_PR {
	BearerContextReleaseCommandIEs__value_PR_NOTHING,	/* No components present */
	BearerContextReleaseCommandIEs__value_PR_GNB_CU_CP_UE_E1AP_ID,
	BearerContextReleaseCommandIEs__value_PR_GNB_CU_UP_UE_E1AP_ID,
	BearerContextReleaseCommandIEs__value_PR_Cause
} BearerContextReleaseCommandIEs__value_PR;
typedef enum BearerContextReleaseCompleteIEs__value_PR {
	BearerContextReleaseCompleteIEs__value_PR_NOTHING,	/* No components present */
	BearerContextReleaseCompleteIEs__value_PR_GNB_CU_CP_UE_E1AP_ID,
	BearerContextReleaseCompleteIEs__value_PR_GNB_CU_UP_UE_E1AP_ID,
	BearerContextReleaseCompleteIEs__value_PR_CriticalityDiagnostics
} BearerContextReleaseCompleteIEs__value_PR;
typedef enum BearerContextReleaseRequestIEs__value_PR {
	BearerContextReleaseRequestIEs__value_PR_NOTHING,	/* No components present */
	BearerContextReleaseRequestIEs__value_PR_GNB_CU_CP_UE_E1AP_ID,
	BearerContextReleaseRequestIEs__value_PR_GNB_CU_UP_UE_E1AP_ID,
	BearerContextReleaseRequestIEs__value_PR_DRB_Status_List,
	BearerContextReleaseRequestIEs__value_PR_Cause
} BearerContextReleaseRequestIEs__value_PR;
typedef enum BearerContextInactivityNotificationIEs__value_PR {
	BearerContextInactivityNotificationIEs__value_PR_NOTHING,	/* No components present */
	BearerContextInactivityNotificationIEs__value_PR_GNB_CU_CP_UE_E1AP_ID,
	BearerContextInactivityNotificationIEs__value_PR_GNB_CU_UP_UE_E1AP_ID,
	BearerContextInactivityNotificationIEs__value_PR_ActivityInformation
} BearerContextInactivityNotificationIEs__value_PR;
typedef enum DLDataNotificationIEs__value_PR {
	DLDataNotificationIEs__value_PR_NOTHING,	/* No components present */
	DLDataNotificationIEs__value_PR_GNB_CU_CP_UE_E1AP_ID,
	DLDataNotificationIEs__value_PR_GNB_CU_UP_UE_E1AP_ID,
	DLDataNotificationIEs__value_PR_PPI
} DLDataNotificationIEs__value_PR;
typedef enum ULDataNotificationIEs__value_PR {
	ULDataNotificationIEs__value_PR_NOTHING,	/* No components present */
	ULDataNotificationIEs__value_PR_GNB_CU_CP_UE_E1AP_ID,
	ULDataNotificationIEs__value_PR_GNB_CU_UP_UE_E1AP_ID,
	ULDataNotificationIEs__value_PR_PDU_Session_To_Notify_List
} ULDataNotificationIEs__value_PR;
typedef enum DataUsageReportIEs__value_PR {
	DataUsageReportIEs__value_PR_NOTHING,	/* No components present */
	DataUsageReportIEs__value_PR_GNB_CU_CP_UE_E1AP_ID,
	DataUsageReportIEs__value_PR_GNB_CU_UP_UE_E1AP_ID,
	DataUsageReportIEs__value_PR_Data_Usage_Report_List
} DataUsageReportIEs__value_PR;
typedef enum GNB_CU_UP_CounterCheckRequestIEs__value_PR {
	GNB_CU_UP_CounterCheckRequestIEs__value_PR_NOTHING,	/* No components present */
	GNB_CU_UP_CounterCheckRequestIEs__value_PR_GNB_CU_CP_UE_E1AP_ID,
	GNB_CU_UP_CounterCheckRequestIEs__value_PR_GNB_CU_UP_UE_E1AP_ID,
	GNB_CU_UP_CounterCheckRequestIEs__value_PR_System_GNB_CU_UP_CounterCheckRequest
} GNB_CU_UP_CounterCheckRequestIEs__value_PR;
typedef enum EUTRAN_GNB_CU_UP_CounterCheckRequestIEs__value_PR {
	EUTRAN_GNB_CU_UP_CounterCheckRequestIEs__value_PR_NOTHING,	/* No components present */
	EUTRAN_GNB_CU_UP_CounterCheckRequestIEs__value_PR_DRBs_Subject_To_Counter_Check_List_EUTRAN
} EUTRAN_GNB_CU_UP_CounterCheckRequestIEs__value_PR;
typedef enum NG_RAN_GNB_CU_UP_CounterCheckRequestIEs__value_PR {
	NG_RAN_GNB_CU_UP_CounterCheckRequestIEs__value_PR_NOTHING,	/* No components present */
	NG_RAN_GNB_CU_UP_CounterCheckRequestIEs__value_PR_DRBs_Subject_To_Counter_Check_List_NG_RAN
} NG_RAN_GNB_CU_UP_CounterCheckRequestIEs__value_PR;
typedef enum GNB_CU_UP_StatusIndicationIEs__value_PR {
	GNB_CU_UP_StatusIndicationIEs__value_PR_NOTHING,	/* No components present */
	GNB_CU_UP_StatusIndicationIEs__value_PR_TransactionID,
	GNB_CU_UP_StatusIndicationIEs__value_PR_GNB_CU_UP_OverloadInformation
} GNB_CU_UP_StatusIndicationIEs__value_PR;
typedef enum MRDC_DataUsageReportIEs__value_PR {
	MRDC_DataUsageReportIEs__value_PR_NOTHING,	/* No components present */
	MRDC_DataUsageReportIEs__value_PR_GNB_CU_CP_UE_E1AP_ID,
	MRDC_DataUsageReportIEs__value_PR_GNB_CU_UP_UE_E1AP_ID,
	MRDC_DataUsageReportIEs__value_PR_PDU_Session_Resource_Data_Usage_List
} MRDC_DataUsageReportIEs__value_PR;

/* ProtocolIE-Field */
typedef struct ActivityInformation_ExtIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct ActivityInformation_ExtIEs__value {
		ActivityInformation_ExtIEs__value_PR present;
		union ActivityInformation_ExtIEs__value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ActivityInformation_ExtIEs_t;
typedef struct Cause_ExtIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct Cause_ExtIEs__value {
		Cause_ExtIEs__value_PR present;
		union Cause_ExtIEs__value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Cause_ExtIEs_t;
typedef struct CP_TNL_Information_ExtIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct CP_TNL_Information_ExtIEs__value {
		CP_TNL_Information_ExtIEs__value_PR present;
		union CP_TNL_Information_ExtIEs__value_u {
			Endpoint_IP_address_and_port_t	 Endpoint_IP_address_and_port;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CP_TNL_Information_ExtIEs_t;
typedef struct QoS_Characteristics_ExtIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct QoS_Characteristics_ExtIEs__value {
		QoS_Characteristics_ExtIEs__value_PR present;
		union QoS_Characteristics_ExtIEs__value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} QoS_Characteristics_ExtIEs_t;
typedef struct ROHC_Parameters_ExtIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct ROHC_Parameters_ExtIEs__value {
		ROHC_Parameters_ExtIEs__value_PR present;
		union ROHC_Parameters_ExtIEs__value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ROHC_Parameters_ExtIEs_t;
typedef struct UP_TNL_Information_ExtIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct UP_TNL_Information_ExtIEs__value {
		UP_TNL_Information_ExtIEs__value_PR present;
		union UP_TNL_Information_ExtIEs__value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UP_TNL_Information_ExtIEs_t;
typedef struct ResetType_ExtIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct ResetType_ExtIEs__value {
		ResetType_ExtIEs__value_PR present;
		union ResetType_ExtIEs__value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ResetType_ExtIEs_t;
typedef struct UE_associatedLogicalE1_ConnectionItemResIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct UE_associatedLogicalE1_ConnectionItemResIEs__value {
		UE_associatedLogicalE1_ConnectionItemResIEs__value_PR present;
		union UE_associatedLogicalE1_ConnectionItemResIEs__value_u {
			UE_associatedLogicalE1_ConnectionItem_t	 UE_associatedLogicalE1_ConnectionItem;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_associatedLogicalE1_ConnectionItemResIEs_t;
typedef struct UE_associatedLogicalE1_ConnectionItemResIEsAckIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct UE_associatedLogicalE1_ConnectionItemResIEsAckIEs__value {
		UE_associatedLogicalE1_ConnectionItemResIEsAckIEs__value_PR present;
		union UE_associatedLogicalE1_ConnectionItemResIEsAckIEs__value_u {
			UE_associatedLogicalE1_ConnectionItem_t	 UE_associatedLogicalE1_ConnectionItem;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UE_associatedLogicalE1_ConnectionItemResIEsAckIEs_t;
typedef struct System_BearerContextSetupRequest_ExtIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct System_BearerContextSetupRequest_ExtIEs__value {
		System_BearerContextSetupRequest_ExtIEs__value_PR present;
		union System_BearerContextSetupRequest_ExtIEs__value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} System_BearerContextSetupRequest_ExtIEs_t;
typedef struct System_BearerContextSetupResponse_ExtIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct System_BearerContextSetupResponse_ExtIEs__value {
		System_BearerContextSetupResponse_ExtIEs__value_PR present;
		union System_BearerContextSetupResponse_ExtIEs__value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} System_BearerContextSetupResponse_ExtIEs_t;
typedef struct System_BearerContextModificationRequest_ExtIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct System_BearerContextModificationRequest_ExtIEs__value {
		System_BearerContextModificationRequest_ExtIEs__value_PR present;
		union System_BearerContextModificationRequest_ExtIEs__value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} System_BearerContextModificationRequest_ExtIEs_t;
typedef struct System_BearerContextModificationResponse_ExtIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct System_BearerContextModificationResponse_ExtIEs__value {
		System_BearerContextModificationResponse_ExtIEs__value_PR present;
		union System_BearerContextModificationResponse_ExtIEs__value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} System_BearerContextModificationResponse_ExtIEs_t;
typedef struct System_BearerContextModificationRequired_ExtIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct System_BearerContextModificationRequired_ExtIEs__value {
		System_BearerContextModificationRequired_ExtIEs__value_PR present;
		union System_BearerContextModificationRequired_ExtIEs__value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} System_BearerContextModificationRequired_ExtIEs_t;
typedef struct System_BearerContextModificationConfirm_ExtIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct System_BearerContextModificationConfirm_ExtIEs__value {
		System_BearerContextModificationConfirm_ExtIEs__value_PR present;
		union System_BearerContextModificationConfirm_ExtIEs__value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} System_BearerContextModificationConfirm_ExtIEs_t;
typedef struct System_GNB_CU_UP_CounterCheckRequest_ExtIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct System_GNB_CU_UP_CounterCheckRequest_ExtIEs__value {
		System_GNB_CU_UP_CounterCheckRequest_ExtIEs__value_PR present;
		union System_GNB_CU_UP_CounterCheckRequest_ExtIEs__value_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} System_GNB_CU_UP_CounterCheckRequest_ExtIEs_t;
typedef struct ResetIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct ResetIEs__value {
		ResetIEs__value_PR present;
		union ResetIEs__value_u {
			TransactionID_t	 TransactionID;
			Cause_t	 Cause;
			ResetType_t	 ResetType;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ResetIEs_t;
typedef struct ResetAcknowledgeIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct ResetAcknowledgeIEs__value {
		ResetAcknowledgeIEs__value_PR present;
		union ResetAcknowledgeIEs__value_u {
			TransactionID_t	 TransactionID;
			UE_associatedLogicalE1_ConnectionListResAck_t	 UE_associatedLogicalE1_ConnectionListResAck;
			CriticalityDiagnostics_t	 CriticalityDiagnostics;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ResetAcknowledgeIEs_t;
typedef struct ErrorIndication_IEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct ErrorIndication_IEs__value {
		ErrorIndication_IEs__value_PR present;
		union ErrorIndication_IEs__value_u {
			TransactionID_t	 TransactionID;
			GNB_CU_CP_UE_E1AP_ID_t	 GNB_CU_CP_UE_E1AP_ID;
			GNB_CU_UP_UE_E1AP_ID_t	 GNB_CU_UP_UE_E1AP_ID;
			Cause_t	 Cause;
			CriticalityDiagnostics_t	 CriticalityDiagnostics;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ErrorIndication_IEs_t;
typedef struct GNB_CU_UP_E1SetupRequestIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct GNB_CU_UP_E1SetupRequestIEs__value {
		GNB_CU_UP_E1SetupRequestIEs__value_PR present;
		union GNB_CU_UP_E1SetupRequestIEs__value_u {
			TransactionID_t	 TransactionID;
			GNB_CU_UP_ID_t	 GNB_CU_UP_ID;
			GNB_CU_UP_Name_t	 GNB_CU_UP_Name;
			CNSupport_t	 CNSupport;
			SupportedPLMNs_List_t	 SupportedPLMNs_List;
			GNB_CU_UP_Capacity_t	 GNB_CU_UP_Capacity;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GNB_CU_UP_E1SetupRequestIEs_t;
typedef struct GNB_CU_UP_E1SetupResponseIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct GNB_CU_UP_E1SetupResponseIEs__value {
		GNB_CU_UP_E1SetupResponseIEs__value_PR present;
		union GNB_CU_UP_E1SetupResponseIEs__value_u {
			TransactionID_t	 TransactionID;
			GNB_CU_CP_Name_t	 GNB_CU_CP_Name;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GNB_CU_UP_E1SetupResponseIEs_t;
typedef struct GNB_CU_UP_E1SetupFailureIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct GNB_CU_UP_E1SetupFailureIEs__value {
		GNB_CU_UP_E1SetupFailureIEs__value_PR present;
		union GNB_CU_UP_E1SetupFailureIEs__value_u {
			TransactionID_t	 TransactionID;
			Cause_t	 Cause;
			TimeToWait_t	 TimeToWait;
			CriticalityDiagnostics_t	 CriticalityDiagnostics;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GNB_CU_UP_E1SetupFailureIEs_t;
typedef struct GNB_CU_CP_E1SetupRequestIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct GNB_CU_CP_E1SetupRequestIEs__value {
		GNB_CU_CP_E1SetupRequestIEs__value_PR present;
		union GNB_CU_CP_E1SetupRequestIEs__value_u {
			TransactionID_t	 TransactionID;
			GNB_CU_CP_Name_t	 GNB_CU_CP_Name;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GNB_CU_CP_E1SetupRequestIEs_t;
typedef struct GNB_CU_CP_E1SetupResponseIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct GNB_CU_CP_E1SetupResponseIEs__value {
		GNB_CU_CP_E1SetupResponseIEs__value_PR present;
		union GNB_CU_CP_E1SetupResponseIEs__value_u {
			TransactionID_t	 TransactionID;
			GNB_CU_UP_ID_t	 GNB_CU_UP_ID;
			GNB_CU_UP_Name_t	 GNB_CU_UP_Name;
			CNSupport_t	 CNSupport;
			SupportedPLMNs_List_t	 SupportedPLMNs_List;
			GNB_CU_UP_Capacity_t	 GNB_CU_UP_Capacity;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GNB_CU_CP_E1SetupResponseIEs_t;
typedef struct GNB_CU_CP_E1SetupFailureIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct GNB_CU_CP_E1SetupFailureIEs__value {
		GNB_CU_CP_E1SetupFailureIEs__value_PR present;
		union GNB_CU_CP_E1SetupFailureIEs__value_u {
			TransactionID_t	 TransactionID;
			Cause_t	 Cause;
			TimeToWait_t	 TimeToWait;
			CriticalityDiagnostics_t	 CriticalityDiagnostics;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GNB_CU_CP_E1SetupFailureIEs_t;
typedef struct GNB_CU_UP_ConfigurationUpdateIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct GNB_CU_UP_ConfigurationUpdateIEs__value {
		GNB_CU_UP_ConfigurationUpdateIEs__value_PR present;
		union GNB_CU_UP_ConfigurationUpdateIEs__value_u {
			TransactionID_t	 TransactionID;
			GNB_CU_UP_ID_t	 GNB_CU_UP_ID;
			GNB_CU_UP_Name_t	 GNB_CU_UP_Name;
			SupportedPLMNs_List_t	 SupportedPLMNs_List;
			GNB_CU_UP_Capacity_t	 GNB_CU_UP_Capacity;
			GNB_CU_UP_TNLA_To_Remove_List_t	 GNB_CU_UP_TNLA_To_Remove_List;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GNB_CU_UP_ConfigurationUpdateIEs_t;
typedef struct GNB_CU_UP_ConfigurationUpdateAcknowledgeIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct GNB_CU_UP_ConfigurationUpdateAcknowledgeIEs__value {
		GNB_CU_UP_ConfigurationUpdateAcknowledgeIEs__value_PR present;
		union GNB_CU_UP_ConfigurationUpdateAcknowledgeIEs__value_u {
			TransactionID_t	 TransactionID;
			CriticalityDiagnostics_t	 CriticalityDiagnostics;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GNB_CU_UP_ConfigurationUpdateAcknowledgeIEs_t;
typedef struct GNB_CU_UP_ConfigurationUpdateFailureIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct GNB_CU_UP_ConfigurationUpdateFailureIEs__value {
		GNB_CU_UP_ConfigurationUpdateFailureIEs__value_PR present;
		union GNB_CU_UP_ConfigurationUpdateFailureIEs__value_u {
			TransactionID_t	 TransactionID;
			Cause_t	 Cause;
			TimeToWait_t	 TimeToWait;
			CriticalityDiagnostics_t	 CriticalityDiagnostics;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GNB_CU_UP_ConfigurationUpdateFailureIEs_t;
typedef struct GNB_CU_CP_ConfigurationUpdateIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct GNB_CU_CP_ConfigurationUpdateIEs__value {
		GNB_CU_CP_ConfigurationUpdateIEs__value_PR present;
		union GNB_CU_CP_ConfigurationUpdateIEs__value_u {
			TransactionID_t	 TransactionID;
			GNB_CU_UP_Name_t	 GNB_CU_UP_Name;
			GNB_CU_CP_TNLA_To_Add_List_t	 GNB_CU_CP_TNLA_To_Add_List;
			GNB_CU_CP_TNLA_To_Remove_List_t	 GNB_CU_CP_TNLA_To_Remove_List;
			GNB_CU_CP_TNLA_To_Update_List_t	 GNB_CU_CP_TNLA_To_Update_List;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GNB_CU_CP_ConfigurationUpdateIEs_t;
typedef struct GNB_CU_CP_ConfigurationUpdateAcknowledgeIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct GNB_CU_CP_ConfigurationUpdateAcknowledgeIEs__value {
		GNB_CU_CP_ConfigurationUpdateAcknowledgeIEs__value_PR present;
		union GNB_CU_CP_ConfigurationUpdateAcknowledgeIEs__value_u {
			TransactionID_t	 TransactionID;
			CriticalityDiagnostics_t	 CriticalityDiagnostics;
			GNB_CU_CP_TNLA_Setup_List_t	 GNB_CU_CP_TNLA_Setup_List;
			GNB_CU_CP_TNLA_Failed_To_Setup_List_t	 GNB_CU_CP_TNLA_Failed_To_Setup_List;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GNB_CU_CP_ConfigurationUpdateAcknowledgeIEs_t;
typedef struct GNB_CU_CP_ConfigurationUpdateFailureIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct GNB_CU_CP_ConfigurationUpdateFailureIEs__value {
		GNB_CU_CP_ConfigurationUpdateFailureIEs__value_PR present;
		union GNB_CU_CP_ConfigurationUpdateFailureIEs__value_u {
			TransactionID_t	 TransactionID;
			Cause_t	 Cause;
			TimeToWait_t	 TimeToWait;
			CriticalityDiagnostics_t	 CriticalityDiagnostics;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GNB_CU_CP_ConfigurationUpdateFailureIEs_t;
typedef struct E1ReleaseRequestIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct E1ReleaseRequestIEs__value {
		E1ReleaseRequestIEs__value_PR present;
		union E1ReleaseRequestIEs__value_u {
			TransactionID_t	 TransactionID;
			Cause_t	 Cause;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E1ReleaseRequestIEs_t;
typedef struct E1ReleaseResponseIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct E1ReleaseResponseIEs__value {
		E1ReleaseResponseIEs__value_PR present;
		union E1ReleaseResponseIEs__value_u {
			TransactionID_t	 TransactionID;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E1ReleaseResponseIEs_t;
typedef struct BearerContextSetupRequestIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct BearerContextSetupRequestIEs__value {
		BearerContextSetupRequestIEs__value_PR present;
		union BearerContextSetupRequestIEs__value_u {
			GNB_CU_CP_UE_E1AP_ID_t	 GNB_CU_CP_UE_E1AP_ID;
			SecurityInformation_t	 SecurityInformation;
			BitRate_t	 BitRate;
			PLMN_Identity_t	 PLMN_Identity;
			ActivityNotificationLevel_t	 ActivityNotificationLevel;
			Inactivity_Timer_t	 Inactivity_Timer;
			BearerContextStatusChange_t	 BearerContextStatusChange;
			System_BearerContextSetupRequest_t	 System_BearerContextSetupRequest;
			RANUEID_t	 RANUEID;
			GNB_DU_ID_t	 GNB_DU_ID;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BearerContextSetupRequestIEs_t;
typedef struct EUTRAN_BearerContextSetupRequestIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct EUTRAN_BearerContextSetupRequestIEs__value {
		EUTRAN_BearerContextSetupRequestIEs__value_PR present;
		union EUTRAN_BearerContextSetupRequestIEs__value_u {
			DRB_To_Setup_List_EUTRAN_t	 DRB_To_Setup_List_EUTRAN;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EUTRAN_BearerContextSetupRequestIEs_t;
typedef struct NG_RAN_BearerContextSetupRequestIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct NG_RAN_BearerContextSetupRequestIEs__value {
		NG_RAN_BearerContextSetupRequestIEs__value_PR present;
		union NG_RAN_BearerContextSetupRequestIEs__value_u {
			PDU_Session_Resource_To_Setup_List_t	 PDU_Session_Resource_To_Setup_List;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NG_RAN_BearerContextSetupRequestIEs_t;
typedef struct BearerContextSetupResponseIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct BearerContextSetupResponseIEs__value {
		BearerContextSetupResponseIEs__value_PR present;
		union BearerContextSetupResponseIEs__value_u {
			GNB_CU_CP_UE_E1AP_ID_t	 GNB_CU_CP_UE_E1AP_ID;
			GNB_CU_UP_UE_E1AP_ID_t	 GNB_CU_UP_UE_E1AP_ID;
			System_BearerContextSetupResponse_t	 System_BearerContextSetupResponse;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BearerContextSetupResponseIEs_t;
typedef struct EUTRAN_BearerContextSetupResponseIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct EUTRAN_BearerContextSetupResponseIEs__value {
		EUTRAN_BearerContextSetupResponseIEs__value_PR present;
		union EUTRAN_BearerContextSetupResponseIEs__value_u {
			DRB_Setup_List_EUTRAN_t	 DRB_Setup_List_EUTRAN;
			DRB_Failed_List_EUTRAN_t	 DRB_Failed_List_EUTRAN;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EUTRAN_BearerContextSetupResponseIEs_t;
typedef struct NG_RAN_BearerContextSetupResponseIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct NG_RAN_BearerContextSetupResponseIEs__value {
		NG_RAN_BearerContextSetupResponseIEs__value_PR present;
		union NG_RAN_BearerContextSetupResponseIEs__value_u {
			PDU_Session_Resource_Setup_List_t	 PDU_Session_Resource_Setup_List;
			PDU_Session_Resource_Failed_List_t	 PDU_Session_Resource_Failed_List;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NG_RAN_BearerContextSetupResponseIEs_t;
typedef struct BearerContextSetupFailureIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct BearerContextSetupFailureIEs__value {
		BearerContextSetupFailureIEs__value_PR present;
		union BearerContextSetupFailureIEs__value_u {
			GNB_CU_CP_UE_E1AP_ID_t	 GNB_CU_CP_UE_E1AP_ID;
			GNB_CU_UP_UE_E1AP_ID_t	 GNB_CU_UP_UE_E1AP_ID;
			Cause_t	 Cause;
			CriticalityDiagnostics_t	 CriticalityDiagnostics;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BearerContextSetupFailureIEs_t;
typedef struct BearerContextModificationRequestIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct BearerContextModificationRequestIEs__value {
		BearerContextModificationRequestIEs__value_PR present;
		union BearerContextModificationRequestIEs__value_u {
			GNB_CU_CP_UE_E1AP_ID_t	 GNB_CU_CP_UE_E1AP_ID;
			GNB_CU_UP_UE_E1AP_ID_t	 GNB_CU_UP_UE_E1AP_ID;
			SecurityInformation_t	 SecurityInformation;
			BitRate_t	 BitRate;
			BearerContextStatusChange_t	 BearerContextStatusChange;
			New_UL_TNL_Information_Required_t	 New_UL_TNL_Information_Required;
			Inactivity_Timer_t	 Inactivity_Timer;
			DataDiscardRequired_t	 DataDiscardRequired;
			System_BearerContextModificationRequest_t	 System_BearerContextModificationRequest;
			RANUEID_t	 RANUEID;
			GNB_DU_ID_t	 GNB_DU_ID;
			ActivityNotificationLevel_t	 ActivityNotificationLevel;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BearerContextModificationRequestIEs_t;
typedef struct EUTRAN_BearerContextModificationRequestIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct EUTRAN_BearerContextModificationRequestIEs__value {
		EUTRAN_BearerContextModificationRequestIEs__value_PR present;
		union EUTRAN_BearerContextModificationRequestIEs__value_u {
			DRB_To_Setup_Mod_List_EUTRAN_t	 DRB_To_Setup_Mod_List_EUTRAN;
			DRB_To_Modify_List_EUTRAN_t	 DRB_To_Modify_List_EUTRAN;
			DRB_To_Remove_List_EUTRAN_t	 DRB_To_Remove_List_EUTRAN;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EUTRAN_BearerContextModificationRequestIEs_t;
typedef struct NG_RAN_BearerContextModificationRequestIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct NG_RAN_BearerContextModificationRequestIEs__value {
		NG_RAN_BearerContextModificationRequestIEs__value_PR present;
		union NG_RAN_BearerContextModificationRequestIEs__value_u {
			PDU_Session_Resource_To_Setup_Mod_List_t	 PDU_Session_Resource_To_Setup_Mod_List;
			PDU_Session_Resource_To_Modify_List_t	 PDU_Session_Resource_To_Modify_List;
			PDU_Session_Resource_To_Remove_List_t	 PDU_Session_Resource_To_Remove_List;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NG_RAN_BearerContextModificationRequestIEs_t;
typedef struct BearerContextModificationResponseIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct BearerContextModificationResponseIEs__value {
		BearerContextModificationResponseIEs__value_PR present;
		union BearerContextModificationResponseIEs__value_u {
			GNB_CU_CP_UE_E1AP_ID_t	 GNB_CU_CP_UE_E1AP_ID;
			GNB_CU_UP_UE_E1AP_ID_t	 GNB_CU_UP_UE_E1AP_ID;
			System_BearerContextModificationResponse_t	 System_BearerContextModificationResponse;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BearerContextModificationResponseIEs_t;
typedef struct EUTRAN_BearerContextModificationResponseIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct EUTRAN_BearerContextModificationResponseIEs__value {
		EUTRAN_BearerContextModificationResponseIEs__value_PR present;
		union EUTRAN_BearerContextModificationResponseIEs__value_u {
			DRB_Setup_Mod_List_EUTRAN_t	 DRB_Setup_Mod_List_EUTRAN;
			DRB_Failed_Mod_List_EUTRAN_t	 DRB_Failed_Mod_List_EUTRAN;
			DRB_Modified_List_EUTRAN_t	 DRB_Modified_List_EUTRAN;
			DRB_Failed_To_Modify_List_EUTRAN_t	 DRB_Failed_To_Modify_List_EUTRAN;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EUTRAN_BearerContextModificationResponseIEs_t;
typedef struct NG_RAN_BearerContextModificationResponseIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct NG_RAN_BearerContextModificationResponseIEs__value {
		NG_RAN_BearerContextModificationResponseIEs__value_PR present;
		union NG_RAN_BearerContextModificationResponseIEs__value_u {
			PDU_Session_Resource_Setup_Mod_List_t	 PDU_Session_Resource_Setup_Mod_List;
			PDU_Session_Resource_Failed_Mod_List_t	 PDU_Session_Resource_Failed_Mod_List;
			PDU_Session_Resource_Modified_List_t	 PDU_Session_Resource_Modified_List;
			PDU_Session_Resource_Failed_To_Modify_List_t	 PDU_Session_Resource_Failed_To_Modify_List;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NG_RAN_BearerContextModificationResponseIEs_t;
typedef struct BearerContextModificationFailureIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct BearerContextModificationFailureIEs__value {
		BearerContextModificationFailureIEs__value_PR present;
		union BearerContextModificationFailureIEs__value_u {
			GNB_CU_CP_UE_E1AP_ID_t	 GNB_CU_CP_UE_E1AP_ID;
			GNB_CU_UP_UE_E1AP_ID_t	 GNB_CU_UP_UE_E1AP_ID;
			Cause_t	 Cause;
			CriticalityDiagnostics_t	 CriticalityDiagnostics;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BearerContextModificationFailureIEs_t;
typedef struct BearerContextModificationRequiredIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct BearerContextModificationRequiredIEs__value {
		BearerContextModificationRequiredIEs__value_PR present;
		union BearerContextModificationRequiredIEs__value_u {
			GNB_CU_CP_UE_E1AP_ID_t	 GNB_CU_CP_UE_E1AP_ID;
			GNB_CU_UP_UE_E1AP_ID_t	 GNB_CU_UP_UE_E1AP_ID;
			System_BearerContextModificationRequired_t	 System_BearerContextModificationRequired;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BearerContextModificationRequiredIEs_t;
typedef struct EUTRAN_BearerContextModificationRequiredIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct EUTRAN_BearerContextModificationRequiredIEs__value {
		EUTRAN_BearerContextModificationRequiredIEs__value_PR present;
		union EUTRAN_BearerContextModificationRequiredIEs__value_u {
			DRB_Required_To_Modify_List_EUTRAN_t	 DRB_Required_To_Modify_List_EUTRAN;
			DRB_Required_To_Remove_List_EUTRAN_t	 DRB_Required_To_Remove_List_EUTRAN;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EUTRAN_BearerContextModificationRequiredIEs_t;
typedef struct NG_RAN_BearerContextModificationRequiredIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct NG_RAN_BearerContextModificationRequiredIEs__value {
		NG_RAN_BearerContextModificationRequiredIEs__value_PR present;
		union NG_RAN_BearerContextModificationRequiredIEs__value_u {
			PDU_Session_Resource_Required_To_Modify_List_t	 PDU_Session_Resource_Required_To_Modify_List;
			PDU_Session_Resource_To_Remove_List_t	 PDU_Session_Resource_To_Remove_List;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NG_RAN_BearerContextModificationRequiredIEs_t;
typedef struct BearerContextModificationConfirmIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct BearerContextModificationConfirmIEs__value {
		BearerContextModificationConfirmIEs__value_PR present;
		union BearerContextModificationConfirmIEs__value_u {
			GNB_CU_CP_UE_E1AP_ID_t	 GNB_CU_CP_UE_E1AP_ID;
			GNB_CU_UP_UE_E1AP_ID_t	 GNB_CU_UP_UE_E1AP_ID;
			System_BearerContextModificationConfirm_t	 System_BearerContextModificationConfirm;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BearerContextModificationConfirmIEs_t;
typedef struct EUTRAN_BearerContextModificationConfirmIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct EUTRAN_BearerContextModificationConfirmIEs__value {
		EUTRAN_BearerContextModificationConfirmIEs__value_PR present;
		union EUTRAN_BearerContextModificationConfirmIEs__value_u {
			DRB_Confirm_Modified_List_EUTRAN_t	 DRB_Confirm_Modified_List_EUTRAN;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EUTRAN_BearerContextModificationConfirmIEs_t;
typedef struct NG_RAN_BearerContextModificationConfirmIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct NG_RAN_BearerContextModificationConfirmIEs__value {
		NG_RAN_BearerContextModificationConfirmIEs__value_PR present;
		union NG_RAN_BearerContextModificationConfirmIEs__value_u {
			PDU_Session_Resource_Confirm_Modified_List_t	 PDU_Session_Resource_Confirm_Modified_List;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NG_RAN_BearerContextModificationConfirmIEs_t;
typedef struct BearerContextReleaseCommandIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct BearerContextReleaseCommandIEs__value {
		BearerContextReleaseCommandIEs__value_PR present;
		union BearerContextReleaseCommandIEs__value_u {
			GNB_CU_CP_UE_E1AP_ID_t	 GNB_CU_CP_UE_E1AP_ID;
			GNB_CU_UP_UE_E1AP_ID_t	 GNB_CU_UP_UE_E1AP_ID;
			Cause_t	 Cause;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BearerContextReleaseCommandIEs_t;
typedef struct BearerContextReleaseCompleteIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct BearerContextReleaseCompleteIEs__value {
		BearerContextReleaseCompleteIEs__value_PR present;
		union BearerContextReleaseCompleteIEs__value_u {
			GNB_CU_CP_UE_E1AP_ID_t	 GNB_CU_CP_UE_E1AP_ID;
			GNB_CU_UP_UE_E1AP_ID_t	 GNB_CU_UP_UE_E1AP_ID;
			CriticalityDiagnostics_t	 CriticalityDiagnostics;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BearerContextReleaseCompleteIEs_t;
typedef struct BearerContextReleaseRequestIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct BearerContextReleaseRequestIEs__value {
		BearerContextReleaseRequestIEs__value_PR present;
		union BearerContextReleaseRequestIEs__value_u {
			GNB_CU_CP_UE_E1AP_ID_t	 GNB_CU_CP_UE_E1AP_ID;
			GNB_CU_UP_UE_E1AP_ID_t	 GNB_CU_UP_UE_E1AP_ID;
			DRB_Status_List_t	 DRB_Status_List;
			Cause_t	 Cause;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BearerContextReleaseRequestIEs_t;
typedef struct BearerContextInactivityNotificationIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct BearerContextInactivityNotificationIEs__value {
		BearerContextInactivityNotificationIEs__value_PR present;
		union BearerContextInactivityNotificationIEs__value_u {
			GNB_CU_CP_UE_E1AP_ID_t	 GNB_CU_CP_UE_E1AP_ID;
			GNB_CU_UP_UE_E1AP_ID_t	 GNB_CU_UP_UE_E1AP_ID;
			ActivityInformation_t	 ActivityInformation;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} BearerContextInactivityNotificationIEs_t;
typedef struct DLDataNotificationIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct DLDataNotificationIEs__value {
		DLDataNotificationIEs__value_PR present;
		union DLDataNotificationIEs__value_u {
			GNB_CU_CP_UE_E1AP_ID_t	 GNB_CU_CP_UE_E1AP_ID;
			GNB_CU_UP_UE_E1AP_ID_t	 GNB_CU_UP_UE_E1AP_ID;
			PPI_t	 PPI;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DLDataNotificationIEs_t;
typedef struct ULDataNotificationIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct ULDataNotificationIEs__value {
		ULDataNotificationIEs__value_PR present;
		union ULDataNotificationIEs__value_u {
			GNB_CU_CP_UE_E1AP_ID_t	 GNB_CU_CP_UE_E1AP_ID;
			GNB_CU_UP_UE_E1AP_ID_t	 GNB_CU_UP_UE_E1AP_ID;
			PDU_Session_To_Notify_List_t	 PDU_Session_To_Notify_List;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ULDataNotificationIEs_t;
typedef struct DataUsageReportIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct DataUsageReportIEs__value {
		DataUsageReportIEs__value_PR present;
		union DataUsageReportIEs__value_u {
			GNB_CU_CP_UE_E1AP_ID_t	 GNB_CU_CP_UE_E1AP_ID;
			GNB_CU_UP_UE_E1AP_ID_t	 GNB_CU_UP_UE_E1AP_ID;
			Data_Usage_Report_List_t	 Data_Usage_Report_List;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DataUsageReportIEs_t;
typedef struct GNB_CU_UP_CounterCheckRequestIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct GNB_CU_UP_CounterCheckRequestIEs__value {
		GNB_CU_UP_CounterCheckRequestIEs__value_PR present;
		union GNB_CU_UP_CounterCheckRequestIEs__value_u {
			GNB_CU_CP_UE_E1AP_ID_t	 GNB_CU_CP_UE_E1AP_ID;
			GNB_CU_UP_UE_E1AP_ID_t	 GNB_CU_UP_UE_E1AP_ID;
			System_GNB_CU_UP_CounterCheckRequest_t	 System_GNB_CU_UP_CounterCheckRequest;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GNB_CU_UP_CounterCheckRequestIEs_t;
typedef struct EUTRAN_GNB_CU_UP_CounterCheckRequestIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct EUTRAN_GNB_CU_UP_CounterCheckRequestIEs__value {
		EUTRAN_GNB_CU_UP_CounterCheckRequestIEs__value_PR present;
		union EUTRAN_GNB_CU_UP_CounterCheckRequestIEs__value_u {
			DRBs_Subject_To_Counter_Check_List_EUTRAN_t	 DRBs_Subject_To_Counter_Check_List_EUTRAN;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EUTRAN_GNB_CU_UP_CounterCheckRequestIEs_t;
typedef struct NG_RAN_GNB_CU_UP_CounterCheckRequestIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct NG_RAN_GNB_CU_UP_CounterCheckRequestIEs__value {
		NG_RAN_GNB_CU_UP_CounterCheckRequestIEs__value_PR present;
		union NG_RAN_GNB_CU_UP_CounterCheckRequestIEs__value_u {
			DRBs_Subject_To_Counter_Check_List_NG_RAN_t	 DRBs_Subject_To_Counter_Check_List_NG_RAN;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NG_RAN_GNB_CU_UP_CounterCheckRequestIEs_t;
typedef struct GNB_CU_UP_StatusIndicationIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct GNB_CU_UP_StatusIndicationIEs__value {
		GNB_CU_UP_StatusIndicationIEs__value_PR present;
		union GNB_CU_UP_StatusIndicationIEs__value_u {
			TransactionID_t	 TransactionID;
			GNB_CU_UP_OverloadInformation_t	 GNB_CU_UP_OverloadInformation;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GNB_CU_UP_StatusIndicationIEs_t;
typedef struct MRDC_DataUsageReportIEs {
	ProtocolIE_ID_t	 id;
	Criticality_t	 criticality;
	struct MRDC_DataUsageReportIEs__value {
		MRDC_DataUsageReportIEs__value_PR present;
		union MRDC_DataUsageReportIEs__value_u {
			GNB_CU_CP_UE_E1AP_ID_t	 GNB_CU_CP_UE_E1AP_ID;
			GNB_CU_UP_UE_E1AP_ID_t	 GNB_CU_UP_UE_E1AP_ID;
			PDU_Session_Resource_Data_Usage_List_t	 PDU_Session_Resource_Data_Usage_List;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} MRDC_DataUsageReportIEs_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ActivityInformation_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_ActivityInformation_ExtIEs_specs_1;
extern asn_TYPE_member_t asn_MBR_ActivityInformation_ExtIEs_1[3];
extern asn_TYPE_descriptor_t asn_DEF_Cause_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_Cause_ExtIEs_specs_5;
extern asn_TYPE_member_t asn_MBR_Cause_ExtIEs_5[3];
extern asn_TYPE_descriptor_t asn_DEF_CP_TNL_Information_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_CP_TNL_Information_ExtIEs_specs_9;
extern asn_TYPE_member_t asn_MBR_CP_TNL_Information_ExtIEs_9[3];
extern asn_TYPE_descriptor_t asn_DEF_QoS_Characteristics_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_QoS_Characteristics_ExtIEs_specs_13;
extern asn_TYPE_member_t asn_MBR_QoS_Characteristics_ExtIEs_13[3];
extern asn_TYPE_descriptor_t asn_DEF_ROHC_Parameters_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_ROHC_Parameters_ExtIEs_specs_17;
extern asn_TYPE_member_t asn_MBR_ROHC_Parameters_ExtIEs_17[3];
extern asn_TYPE_descriptor_t asn_DEF_UP_TNL_Information_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_UP_TNL_Information_ExtIEs_specs_21;
extern asn_TYPE_member_t asn_MBR_UP_TNL_Information_ExtIEs_21[3];
extern asn_TYPE_descriptor_t asn_DEF_ResetType_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_ResetType_ExtIEs_specs_25;
extern asn_TYPE_member_t asn_MBR_ResetType_ExtIEs_25[3];
extern asn_TYPE_descriptor_t asn_DEF_UE_associatedLogicalE1_ConnectionItemResIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_UE_associatedLogicalE1_ConnectionItemResIEs_specs_29;
extern asn_TYPE_member_t asn_MBR_UE_associatedLogicalE1_ConnectionItemResIEs_29[3];
extern asn_TYPE_descriptor_t asn_DEF_UE_associatedLogicalE1_ConnectionItemResIEsAckIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_UE_associatedLogicalE1_ConnectionItemResIEsAckIEs_specs_33;
extern asn_TYPE_member_t asn_MBR_UE_associatedLogicalE1_ConnectionItemResIEsAckIEs_33[3];
extern asn_TYPE_descriptor_t asn_DEF_System_BearerContextSetupRequest_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_System_BearerContextSetupRequest_ExtIEs_specs_37;
extern asn_TYPE_member_t asn_MBR_System_BearerContextSetupRequest_ExtIEs_37[3];
extern asn_TYPE_descriptor_t asn_DEF_System_BearerContextSetupResponse_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_System_BearerContextSetupResponse_ExtIEs_specs_41;
extern asn_TYPE_member_t asn_MBR_System_BearerContextSetupResponse_ExtIEs_41[3];
extern asn_TYPE_descriptor_t asn_DEF_System_BearerContextModificationRequest_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_System_BearerContextModificationRequest_ExtIEs_specs_45;
extern asn_TYPE_member_t asn_MBR_System_BearerContextModificationRequest_ExtIEs_45[3];
extern asn_TYPE_descriptor_t asn_DEF_System_BearerContextModificationResponse_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_System_BearerContextModificationResponse_ExtIEs_specs_49;
extern asn_TYPE_member_t asn_MBR_System_BearerContextModificationResponse_ExtIEs_49[3];
extern asn_TYPE_descriptor_t asn_DEF_System_BearerContextModificationRequired_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_System_BearerContextModificationRequired_ExtIEs_specs_53;
extern asn_TYPE_member_t asn_MBR_System_BearerContextModificationRequired_ExtIEs_53[3];
extern asn_TYPE_descriptor_t asn_DEF_System_BearerContextModificationConfirm_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_System_BearerContextModificationConfirm_ExtIEs_specs_57;
extern asn_TYPE_member_t asn_MBR_System_BearerContextModificationConfirm_ExtIEs_57[3];
extern asn_TYPE_descriptor_t asn_DEF_System_GNB_CU_UP_CounterCheckRequest_ExtIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_System_GNB_CU_UP_CounterCheckRequest_ExtIEs_specs_61;
extern asn_TYPE_member_t asn_MBR_System_GNB_CU_UP_CounterCheckRequest_ExtIEs_61[3];
extern asn_TYPE_descriptor_t asn_DEF_ResetIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_ResetIEs_specs_65;
extern asn_TYPE_member_t asn_MBR_ResetIEs_65[3];
extern asn_TYPE_descriptor_t asn_DEF_ResetAcknowledgeIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_ResetAcknowledgeIEs_specs_69;
extern asn_TYPE_member_t asn_MBR_ResetAcknowledgeIEs_69[3];
extern asn_TYPE_descriptor_t asn_DEF_ErrorIndication_IEs;
extern asn_SEQUENCE_specifics_t asn_SPC_ErrorIndication_IEs_specs_73;
extern asn_TYPE_member_t asn_MBR_ErrorIndication_IEs_73[3];
extern asn_TYPE_descriptor_t asn_DEF_GNB_CU_UP_E1SetupRequestIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_GNB_CU_UP_E1SetupRequestIEs_specs_77;
extern asn_TYPE_member_t asn_MBR_GNB_CU_UP_E1SetupRequestIEs_77[3];
extern asn_TYPE_descriptor_t asn_DEF_GNB_CU_UP_E1SetupResponseIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_GNB_CU_UP_E1SetupResponseIEs_specs_81;
extern asn_TYPE_member_t asn_MBR_GNB_CU_UP_E1SetupResponseIEs_81[3];
extern asn_TYPE_descriptor_t asn_DEF_GNB_CU_UP_E1SetupFailureIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_GNB_CU_UP_E1SetupFailureIEs_specs_85;
extern asn_TYPE_member_t asn_MBR_GNB_CU_UP_E1SetupFailureIEs_85[3];
extern asn_TYPE_descriptor_t asn_DEF_GNB_CU_CP_E1SetupRequestIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_GNB_CU_CP_E1SetupRequestIEs_specs_89;
extern asn_TYPE_member_t asn_MBR_GNB_CU_CP_E1SetupRequestIEs_89[3];
extern asn_TYPE_descriptor_t asn_DEF_GNB_CU_CP_E1SetupResponseIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_GNB_CU_CP_E1SetupResponseIEs_specs_93;
extern asn_TYPE_member_t asn_MBR_GNB_CU_CP_E1SetupResponseIEs_93[3];
extern asn_TYPE_descriptor_t asn_DEF_GNB_CU_CP_E1SetupFailureIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_GNB_CU_CP_E1SetupFailureIEs_specs_97;
extern asn_TYPE_member_t asn_MBR_GNB_CU_CP_E1SetupFailureIEs_97[3];
extern asn_TYPE_descriptor_t asn_DEF_GNB_CU_UP_ConfigurationUpdateIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_GNB_CU_UP_ConfigurationUpdateIEs_specs_101;
extern asn_TYPE_member_t asn_MBR_GNB_CU_UP_ConfigurationUpdateIEs_101[3];
extern asn_TYPE_descriptor_t asn_DEF_GNB_CU_UP_ConfigurationUpdateAcknowledgeIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_GNB_CU_UP_ConfigurationUpdateAcknowledgeIEs_specs_105;
extern asn_TYPE_member_t asn_MBR_GNB_CU_UP_ConfigurationUpdateAcknowledgeIEs_105[3];
extern asn_TYPE_descriptor_t asn_DEF_GNB_CU_UP_ConfigurationUpdateFailureIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_GNB_CU_UP_ConfigurationUpdateFailureIEs_specs_109;
extern asn_TYPE_member_t asn_MBR_GNB_CU_UP_ConfigurationUpdateFailureIEs_109[3];
extern asn_TYPE_descriptor_t asn_DEF_GNB_CU_CP_ConfigurationUpdateIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_GNB_CU_CP_ConfigurationUpdateIEs_specs_113;
extern asn_TYPE_member_t asn_MBR_GNB_CU_CP_ConfigurationUpdateIEs_113[3];
extern asn_TYPE_descriptor_t asn_DEF_GNB_CU_CP_ConfigurationUpdateAcknowledgeIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_GNB_CU_CP_ConfigurationUpdateAcknowledgeIEs_specs_117;
extern asn_TYPE_member_t asn_MBR_GNB_CU_CP_ConfigurationUpdateAcknowledgeIEs_117[3];
extern asn_TYPE_descriptor_t asn_DEF_GNB_CU_CP_ConfigurationUpdateFailureIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_GNB_CU_CP_ConfigurationUpdateFailureIEs_specs_121;
extern asn_TYPE_member_t asn_MBR_GNB_CU_CP_ConfigurationUpdateFailureIEs_121[3];
extern asn_TYPE_descriptor_t asn_DEF_E1ReleaseRequestIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_E1ReleaseRequestIEs_specs_125;
extern asn_TYPE_member_t asn_MBR_E1ReleaseRequestIEs_125[3];
extern asn_TYPE_descriptor_t asn_DEF_E1ReleaseResponseIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_E1ReleaseResponseIEs_specs_129;
extern asn_TYPE_member_t asn_MBR_E1ReleaseResponseIEs_129[3];
extern asn_TYPE_descriptor_t asn_DEF_BearerContextSetupRequestIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_BearerContextSetupRequestIEs_specs_133;
extern asn_TYPE_member_t asn_MBR_BearerContextSetupRequestIEs_133[3];
extern asn_TYPE_descriptor_t asn_DEF_EUTRAN_BearerContextSetupRequestIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_EUTRAN_BearerContextSetupRequestIEs_specs_137;
extern asn_TYPE_member_t asn_MBR_EUTRAN_BearerContextSetupRequestIEs_137[3];
extern asn_TYPE_descriptor_t asn_DEF_NG_RAN_BearerContextSetupRequestIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NG_RAN_BearerContextSetupRequestIEs_specs_141;
extern asn_TYPE_member_t asn_MBR_NG_RAN_BearerContextSetupRequestIEs_141[3];
extern asn_TYPE_descriptor_t asn_DEF_BearerContextSetupResponseIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_BearerContextSetupResponseIEs_specs_145;
extern asn_TYPE_member_t asn_MBR_BearerContextSetupResponseIEs_145[3];
extern asn_TYPE_descriptor_t asn_DEF_EUTRAN_BearerContextSetupResponseIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_EUTRAN_BearerContextSetupResponseIEs_specs_149;
extern asn_TYPE_member_t asn_MBR_EUTRAN_BearerContextSetupResponseIEs_149[3];
extern asn_TYPE_descriptor_t asn_DEF_NG_RAN_BearerContextSetupResponseIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NG_RAN_BearerContextSetupResponseIEs_specs_153;
extern asn_TYPE_member_t asn_MBR_NG_RAN_BearerContextSetupResponseIEs_153[3];
extern asn_TYPE_descriptor_t asn_DEF_BearerContextSetupFailureIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_BearerContextSetupFailureIEs_specs_157;
extern asn_TYPE_member_t asn_MBR_BearerContextSetupFailureIEs_157[3];
extern asn_TYPE_descriptor_t asn_DEF_BearerContextModificationRequestIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_BearerContextModificationRequestIEs_specs_161;
extern asn_TYPE_member_t asn_MBR_BearerContextModificationRequestIEs_161[3];
extern asn_TYPE_descriptor_t asn_DEF_EUTRAN_BearerContextModificationRequestIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_EUTRAN_BearerContextModificationRequestIEs_specs_165;
extern asn_TYPE_member_t asn_MBR_EUTRAN_BearerContextModificationRequestIEs_165[3];
extern asn_TYPE_descriptor_t asn_DEF_NG_RAN_BearerContextModificationRequestIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NG_RAN_BearerContextModificationRequestIEs_specs_169;
extern asn_TYPE_member_t asn_MBR_NG_RAN_BearerContextModificationRequestIEs_169[3];
extern asn_TYPE_descriptor_t asn_DEF_BearerContextModificationResponseIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_BearerContextModificationResponseIEs_specs_173;
extern asn_TYPE_member_t asn_MBR_BearerContextModificationResponseIEs_173[3];
extern asn_TYPE_descriptor_t asn_DEF_EUTRAN_BearerContextModificationResponseIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_EUTRAN_BearerContextModificationResponseIEs_specs_177;
extern asn_TYPE_member_t asn_MBR_EUTRAN_BearerContextModificationResponseIEs_177[3];
extern asn_TYPE_descriptor_t asn_DEF_NG_RAN_BearerContextModificationResponseIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NG_RAN_BearerContextModificationResponseIEs_specs_181;
extern asn_TYPE_member_t asn_MBR_NG_RAN_BearerContextModificationResponseIEs_181[3];
extern asn_TYPE_descriptor_t asn_DEF_BearerContextModificationFailureIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_BearerContextModificationFailureIEs_specs_185;
extern asn_TYPE_member_t asn_MBR_BearerContextModificationFailureIEs_185[3];
extern asn_TYPE_descriptor_t asn_DEF_BearerContextModificationRequiredIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_BearerContextModificationRequiredIEs_specs_189;
extern asn_TYPE_member_t asn_MBR_BearerContextModificationRequiredIEs_189[3];
extern asn_TYPE_descriptor_t asn_DEF_EUTRAN_BearerContextModificationRequiredIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_EUTRAN_BearerContextModificationRequiredIEs_specs_193;
extern asn_TYPE_member_t asn_MBR_EUTRAN_BearerContextModificationRequiredIEs_193[3];
extern asn_TYPE_descriptor_t asn_DEF_NG_RAN_BearerContextModificationRequiredIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NG_RAN_BearerContextModificationRequiredIEs_specs_197;
extern asn_TYPE_member_t asn_MBR_NG_RAN_BearerContextModificationRequiredIEs_197[3];
extern asn_TYPE_descriptor_t asn_DEF_BearerContextModificationConfirmIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_BearerContextModificationConfirmIEs_specs_201;
extern asn_TYPE_member_t asn_MBR_BearerContextModificationConfirmIEs_201[3];
extern asn_TYPE_descriptor_t asn_DEF_EUTRAN_BearerContextModificationConfirmIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_EUTRAN_BearerContextModificationConfirmIEs_specs_205;
extern asn_TYPE_member_t asn_MBR_EUTRAN_BearerContextModificationConfirmIEs_205[3];
extern asn_TYPE_descriptor_t asn_DEF_NG_RAN_BearerContextModificationConfirmIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NG_RAN_BearerContextModificationConfirmIEs_specs_209;
extern asn_TYPE_member_t asn_MBR_NG_RAN_BearerContextModificationConfirmIEs_209[3];
extern asn_TYPE_descriptor_t asn_DEF_BearerContextReleaseCommandIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_BearerContextReleaseCommandIEs_specs_213;
extern asn_TYPE_member_t asn_MBR_BearerContextReleaseCommandIEs_213[3];
extern asn_TYPE_descriptor_t asn_DEF_BearerContextReleaseCompleteIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_BearerContextReleaseCompleteIEs_specs_217;
extern asn_TYPE_member_t asn_MBR_BearerContextReleaseCompleteIEs_217[3];
extern asn_TYPE_descriptor_t asn_DEF_BearerContextReleaseRequestIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_BearerContextReleaseRequestIEs_specs_221;
extern asn_TYPE_member_t asn_MBR_BearerContextReleaseRequestIEs_221[3];
extern asn_TYPE_descriptor_t asn_DEF_BearerContextInactivityNotificationIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_BearerContextInactivityNotificationIEs_specs_225;
extern asn_TYPE_member_t asn_MBR_BearerContextInactivityNotificationIEs_225[3];
extern asn_TYPE_descriptor_t asn_DEF_DLDataNotificationIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_DLDataNotificationIEs_specs_229;
extern asn_TYPE_member_t asn_MBR_DLDataNotificationIEs_229[3];
extern asn_TYPE_descriptor_t asn_DEF_ULDataNotificationIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_ULDataNotificationIEs_specs_233;
extern asn_TYPE_member_t asn_MBR_ULDataNotificationIEs_233[3];
extern asn_TYPE_descriptor_t asn_DEF_DataUsageReportIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_DataUsageReportIEs_specs_237;
extern asn_TYPE_member_t asn_MBR_DataUsageReportIEs_237[3];
extern asn_TYPE_descriptor_t asn_DEF_GNB_CU_UP_CounterCheckRequestIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_GNB_CU_UP_CounterCheckRequestIEs_specs_241;
extern asn_TYPE_member_t asn_MBR_GNB_CU_UP_CounterCheckRequestIEs_241[3];
extern asn_TYPE_descriptor_t asn_DEF_EUTRAN_GNB_CU_UP_CounterCheckRequestIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_EUTRAN_GNB_CU_UP_CounterCheckRequestIEs_specs_245;
extern asn_TYPE_member_t asn_MBR_EUTRAN_GNB_CU_UP_CounterCheckRequestIEs_245[3];
extern asn_TYPE_descriptor_t asn_DEF_NG_RAN_GNB_CU_UP_CounterCheckRequestIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_NG_RAN_GNB_CU_UP_CounterCheckRequestIEs_specs_249;
extern asn_TYPE_member_t asn_MBR_NG_RAN_GNB_CU_UP_CounterCheckRequestIEs_249[3];
extern asn_TYPE_descriptor_t asn_DEF_GNB_CU_UP_StatusIndicationIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_GNB_CU_UP_StatusIndicationIEs_specs_253;
extern asn_TYPE_member_t asn_MBR_GNB_CU_UP_StatusIndicationIEs_253[3];
extern asn_TYPE_descriptor_t asn_DEF_MRDC_DataUsageReportIEs;
extern asn_SEQUENCE_specifics_t asn_SPC_MRDC_DataUsageReportIEs_specs_257;
extern asn_TYPE_member_t asn_MBR_MRDC_DataUsageReportIEs_257[3];

#ifdef __cplusplus
}
#endif

#endif	/* _ProtocolIE_Field_H_ */
#include <asn_internal.h>
