/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_RLC_Mode_H_
#define	_RLC_Mode_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RLC_Mode {
	RLC_Mode_rlc_tm	= 0,
	RLC_Mode_rlc_am	= 1,
	RLC_Mode_rlc_um_bidirectional	= 2,
	RLC_Mode_rlc_um_unidirectional_ul	= 3,
	RLC_Mode_rlc_um_unidirectional_dl	= 4
	/*
	 * Enumeration is extensible
	 */
} e_RLC_Mode;

/* RLC-Mode */
typedef long	 RLC_Mode_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RLC_Mode_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RLC_Mode;
extern const asn_INTEGER_specifics_t asn_SPC_RLC_Mode_specs_1;
asn_struct_free_f RLC_Mode_free;
asn_struct_print_f RLC_Mode_print;
asn_constr_check_f RLC_Mode_constraint;
ber_type_decoder_f RLC_Mode_decode_ber;
der_type_encoder_f RLC_Mode_encode_der;
xer_type_decoder_f RLC_Mode_decode_xer;
xer_type_encoder_f RLC_Mode_encode_xer;
oer_type_decoder_f RLC_Mode_decode_oer;
oer_type_encoder_f RLC_Mode_encode_oer;
per_type_decoder_f RLC_Mode_decode_uper;
per_type_encoder_f RLC_Mode_encode_uper;
per_type_decoder_f RLC_Mode_decode_aper;
per_type_encoder_f RLC_Mode_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RLC_Mode_H_ */
#include <asn_internal.h>
