/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_ROHC_Parameters_H_
#define	_ROHC_Parameters_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ROHC_Parameters_PR {
	ROHC_Parameters_PR_NOTHING,	/* No components present */
	ROHC_Parameters_PR_rOHC,
	ROHC_Parameters_PR_uPlinkOnlyROHC,
	ROHC_Parameters_PR_choice_Extension
} ROHC_Parameters_PR;

/* Forward declarations */
struct ROHC;
struct UplinkOnlyROHC;
struct ProtocolIE_SingleContainer;

/* ROHC-Parameters */
typedef struct ROHC_Parameters {
	ROHC_Parameters_PR present;
	union ROHC_Parameters_u {
		struct ROHC	*rOHC;
		struct UplinkOnlyROHC	*uPlinkOnlyROHC;
		struct ProtocolIE_SingleContainer	*choice_Extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ROHC_Parameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ROHC_Parameters;
extern asn_CHOICE_specifics_t asn_SPC_ROHC_Parameters_specs_1;
extern asn_TYPE_member_t asn_MBR_ROHC_Parameters_1[3];
extern asn_per_constraints_t asn_PER_type_ROHC_Parameters_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ROHC_Parameters_H_ */
#include <asn_internal.h>
