/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#include "ROHC-Parameters.h"

#include "ROHC.h"
#include "UplinkOnlyROHC.h"
#include "ProtocolIE-SingleContainer.h"
static asn_oer_constraints_t asn_OER_type_ROHC_Parameters_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
asn_per_constraints_t asn_PER_type_ROHC_Parameters_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_ROHC_Parameters_1[] = {
	{ ATF_POINTER, 0, offsetof(struct ROHC_Parameters, choice.rOHC),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ROHC,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rOHC"
		},
	{ ATF_POINTER, 0, offsetof(struct ROHC_Parameters, choice.uPlinkOnlyROHC),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UplinkOnlyROHC,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"uPlinkOnlyROHC"
		},
	{ ATF_POINTER, 0, offsetof(struct ROHC_Parameters, choice.choice_Extension),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolIE_SingleContainer_102P4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"choice-Extension"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ROHC_Parameters_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* rOHC */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* uPlinkOnlyROHC */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* choice-Extension */
};
asn_CHOICE_specifics_t asn_SPC_ROHC_Parameters_specs_1 = {
	sizeof(struct ROHC_Parameters),
	offsetof(struct ROHC_Parameters, _asn_ctx),
	offsetof(struct ROHC_Parameters, present),
	sizeof(((struct ROHC_Parameters *)0)->present),
	asn_MAP_ROHC_Parameters_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ROHC_Parameters = {
	"ROHC-Parameters",
	"ROHC-Parameters",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_ROHC_Parameters_constr_1, &asn_PER_type_ROHC_Parameters_constr_1, CHOICE_constraint },
	asn_MBR_ROHC_Parameters_1,
	3,	/* Elements count */
	&asn_SPC_ROHC_Parameters_specs_1	/* Additional specs */
};

