/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_SDAP_Configuration_H_
#define	_SDAP_Configuration_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DefaultDRB.h"
#include "SDAP-Header-UL.h"
#include "SDAP-Header-DL.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* SDAP-Configuration */
typedef struct SDAP_Configuration {
	DefaultDRB_t	 defaultDRB;
	SDAP_Header_UL_t	 sDAP_Header_UL;
	SDAP_Header_DL_t	 sDAP_Header_DL;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SDAP_Configuration_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SDAP_Configuration;
extern asn_SEQUENCE_specifics_t asn_SPC_SDAP_Configuration_specs_1;
extern asn_TYPE_member_t asn_MBR_SDAP_Configuration_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _SDAP_Configuration_H_ */
#include <asn_internal.h>
