/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#include "SDAP-Configuration.h"

#include "ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_SDAP_Configuration_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SDAP_Configuration, defaultDRB),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DefaultDRB,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"defaultDRB"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SDAP_Configuration, sDAP_Header_UL),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SDAP_Header_UL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sDAP-Header-UL"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SDAP_Configuration, sDAP_Header_DL),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SDAP_Header_DL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sDAP-Header-DL"
		},
	{ ATF_POINTER, 1, offsetof(struct SDAP_Configuration, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_128P95,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_SDAP_Configuration_oms_1[] = { 3 };
static const ber_tlv_tag_t asn_DEF_SDAP_Configuration_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SDAP_Configuration_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* defaultDRB */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* sDAP-Header-UL */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* sDAP-Header-DL */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_SDAP_Configuration_specs_1 = {
	sizeof(struct SDAP_Configuration),
	offsetof(struct SDAP_Configuration, _asn_ctx),
	asn_MAP_SDAP_Configuration_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_SDAP_Configuration_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SDAP_Configuration = {
	"SDAP-Configuration",
	"SDAP-Configuration",
	&asn_OP_SEQUENCE,
	asn_DEF_SDAP_Configuration_tags_1,
	sizeof(asn_DEF_SDAP_Configuration_tags_1)
		/sizeof(asn_DEF_SDAP_Configuration_tags_1[0]), /* 1 */
	asn_DEF_SDAP_Configuration_tags_1,	/* Same as above */
	sizeof(asn_DEF_SDAP_Configuration_tags_1)
		/sizeof(asn_DEF_SDAP_Configuration_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SDAP_Configuration_1,
	4,	/* Elements count */
	&asn_SPC_SDAP_Configuration_specs_1	/* Additional specs */
};

