/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_SecurityInformation_H_
#define	_SecurityInformation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "SecurityAlgorithm.h"
#include "UPSecuritykey.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* SecurityInformation */
typedef struct SecurityInformation {
	SecurityAlgorithm_t	 securityAlgorithm;
	UPSecuritykey_t	 uPSecuritykey;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SecurityInformation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SecurityInformation;
extern asn_SEQUENCE_specifics_t asn_SPC_SecurityInformation_specs_1;
extern asn_TYPE_member_t asn_MBR_SecurityInformation_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _SecurityInformation_H_ */
#include <asn_internal.h>
