/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-PDU-Contents"
 * 	found in "E1AP-PDU-Contents.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#include "SupportedPLMNs-Item.h"

#include "Slice-Support-List.h"
#include "NR-CGI-Support-List.h"
#include "QoS-Parameters-Support-List.h"
#include "ProtocolExtensionContainer.h"
asn_TYPE_member_t asn_MBR_SupportedPLMNs_Item_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SupportedPLMNs_Item, pLMN_Identity),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PLMN_Identity,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pLMN-Identity"
		},
	{ ATF_POINTER, 4, offsetof(struct SupportedPLMNs_Item, slice_Support_List),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Slice_Support_List,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"slice-Support-List"
		},
	{ ATF_POINTER, 3, offsetof(struct SupportedPLMNs_Item, nR_CGI_Support_List),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NR_CGI_Support_List,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nR-CGI-Support-List"
		},
	{ ATF_POINTER, 2, offsetof(struct SupportedPLMNs_Item, qoS_Parameters_Support_List),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_QoS_Parameters_Support_List,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"qoS-Parameters-Support-List"
		},
	{ ATF_POINTER, 1, offsetof(struct SupportedPLMNs_Item, iE_Extensions),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ProtocolExtensionContainer_128P101,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"iE-Extensions"
		},
};
static const int asn_MAP_SupportedPLMNs_Item_oms_1[] = { 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_SupportedPLMNs_Item_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SupportedPLMNs_Item_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* pLMN-Identity */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* slice-Support-List */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* nR-CGI-Support-List */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* qoS-Parameters-Support-List */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* iE-Extensions */
};
asn_SEQUENCE_specifics_t asn_SPC_SupportedPLMNs_Item_specs_1 = {
	sizeof(struct SupportedPLMNs_Item),
	offsetof(struct SupportedPLMNs_Item, _asn_ctx),
	asn_MAP_SupportedPLMNs_Item_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_SupportedPLMNs_Item_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SupportedPLMNs_Item = {
	"SupportedPLMNs-Item",
	"SupportedPLMNs-Item",
	&asn_OP_SEQUENCE,
	asn_DEF_SupportedPLMNs_Item_tags_1,
	sizeof(asn_DEF_SupportedPLMNs_Item_tags_1)
		/sizeof(asn_DEF_SupportedPLMNs_Item_tags_1[0]), /* 1 */
	asn_DEF_SupportedPLMNs_Item_tags_1,	/* Same as above */
	sizeof(asn_DEF_SupportedPLMNs_Item_tags_1)
		/sizeof(asn_DEF_SupportedPLMNs_Item_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SupportedPLMNs_Item_1,
	5,	/* Elements count */
	&asn_SPC_SupportedPLMNs_Item_specs_1	/* Additional specs */
};

