/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-PDU-Contents"
 * 	found in "E1AP-PDU-Contents.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_SupportedPLMNs_Item_H_
#define	_SupportedPLMNs_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "PLMN-Identity.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Slice_Support_List;
struct NR_CGI_Support_List;
struct QoS_Parameters_Support_List;
struct ProtocolExtensionContainer;

/* SupportedPLMNs-Item */
typedef struct SupportedPLMNs_Item {
	PLMN_Identity_t	 pLMN_Identity;
	struct Slice_Support_List	*slice_Support_List;	/* OPTIONAL */
	struct NR_CGI_Support_List	*nR_CGI_Support_List;	/* OPTIONAL */
	struct QoS_Parameters_Support_List	*qoS_Parameters_Support_List;	/* OPTIONAL */
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SupportedPLMNs_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SupportedPLMNs_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_SupportedPLMNs_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_SupportedPLMNs_Item_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _SupportedPLMNs_Item_H_ */
#include <asn_internal.h>
