/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-PDU-Contents"
 * 	found in "E1AP-PDU-Contents.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_System_BearerContextModificationRequired_H_
#define	_System_BearerContextModificationRequired_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum System_BearerContextModificationRequired_PR {
	System_BearerContextModificationRequired_PR_NOTHING,	/* No components present */
	System_BearerContextModificationRequired_PR_e_UTRAN_BearerContextModificationRequired,
	System_BearerContextModificationRequired_PR_nG_RAN_BearerContextModificationRequired,
	System_BearerContextModificationRequired_PR_choice_extension
} System_BearerContextModificationRequired_PR;

/* Forward declarations */
struct ProtocolIE_Container;
struct ProtocolIE_SingleContainer;

/* System-BearerContextModificationRequired */
typedef struct System_BearerContextModificationRequired {
	System_BearerContextModificationRequired_PR present;
	union System_BearerContextModificationRequired_u {
		struct ProtocolIE_Container	*e_UTRAN_BearerContextModificationRequired;
		struct ProtocolIE_Container	*nG_RAN_BearerContextModificationRequired;
		struct ProtocolIE_SingleContainer	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} System_BearerContextModificationRequired_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_System_BearerContextModificationRequired;
extern asn_CHOICE_specifics_t asn_SPC_System_BearerContextModificationRequired_specs_1;
extern asn_TYPE_member_t asn_MBR_System_BearerContextModificationRequired_1[3];
extern asn_per_constraints_t asn_PER_type_System_BearerContextModificationRequired_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _System_BearerContextModificationRequired_H_ */
#include <asn_internal.h>
