/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-PDU-Contents"
 * 	found in "E1AP-PDU-Contents.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_System_BearerContextSetupResponse_H_
#define	_System_BearerContextSetupResponse_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum System_BearerContextSetupResponse_PR {
	System_BearerContextSetupResponse_PR_NOTHING,	/* No components present */
	System_BearerContextSetupResponse_PR_e_UTRAN_BearerContextSetupResponse,
	System_BearerContextSetupResponse_PR_nG_RAN_BearerContextSetupResponse,
	System_BearerContextSetupResponse_PR_choice_extension
} System_BearerContextSetupResponse_PR;

/* Forward declarations */
struct ProtocolIE_Container;
struct ProtocolIE_SingleContainer;

/* System-BearerContextSetupResponse */
typedef struct System_BearerContextSetupResponse {
	System_BearerContextSetupResponse_PR present;
	union System_BearerContextSetupResponse_u {
		struct ProtocolIE_Container	*e_UTRAN_BearerContextSetupResponse;
		struct ProtocolIE_Container	*nG_RAN_BearerContextSetupResponse;
		struct ProtocolIE_SingleContainer	*choice_extension;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} System_BearerContextSetupResponse_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_System_BearerContextSetupResponse;
extern asn_CHOICE_specifics_t asn_SPC_System_BearerContextSetupResponse_specs_1;
extern asn_TYPE_member_t asn_MBR_System_BearerContextSetupResponse_1[3];
extern asn_per_constraints_t asn_PER_type_System_BearerContextSetupResponse_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _System_BearerContextSetupResponse_H_ */
#include <asn_internal.h>
