/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_T_ReorderingTimer_H_
#define	_T_ReorderingTimer_H_


#include <asn_application.h>

/* Including external dependencies */
#include "T-Reordering.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* T-ReorderingTimer */
typedef struct T_ReorderingTimer {
	T_Reordering_t	 t_Reordering;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} T_ReorderingTimer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_T_ReorderingTimer;
extern asn_SEQUENCE_specifics_t asn_SPC_T_ReorderingTimer_specs_1;
extern asn_TYPE_member_t asn_MBR_T_ReorderingTimer_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _T_ReorderingTimer_H_ */
#include <asn_internal.h>
