/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_ULDataSplitThreshold_H_
#define	_ULDataSplitThreshold_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ULDataSplitThreshold {
	ULDataSplitThreshold_b0	= 0,
	ULDataSplitThreshold_b100	= 1,
	ULDataSplitThreshold_b200	= 2,
	ULDataSplitThreshold_b400	= 3,
	ULDataSplitThreshold_b800	= 4,
	ULDataSplitThreshold_b1600	= 5,
	ULDataSplitThreshold_b3200	= 6,
	ULDataSplitThreshold_b6400	= 7,
	ULDataSplitThreshold_b12800	= 8,
	ULDataSplitThreshold_b25600	= 9,
	ULDataSplitThreshold_b51200	= 10,
	ULDataSplitThreshold_b102400	= 11,
	ULDataSplitThreshold_b204800	= 12,
	ULDataSplitThreshold_b409600	= 13,
	ULDataSplitThreshold_b819200	= 14,
	ULDataSplitThreshold_b1228800	= 15,
	ULDataSplitThreshold_b1638400	= 16,
	ULDataSplitThreshold_b2457600	= 17,
	ULDataSplitThreshold_b3276800	= 18,
	ULDataSplitThreshold_b4096000	= 19,
	ULDataSplitThreshold_b4915200	= 20,
	ULDataSplitThreshold_b5734400	= 21,
	ULDataSplitThreshold_b6553600	= 22,
	ULDataSplitThreshold_infinity	= 23
	/*
	 * Enumeration is extensible
	 */
} e_ULDataSplitThreshold;

/* ULDataSplitThreshold */
typedef long	 ULDataSplitThreshold_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ULDataSplitThreshold_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ULDataSplitThreshold;
extern const asn_INTEGER_specifics_t asn_SPC_ULDataSplitThreshold_specs_1;
asn_struct_free_f ULDataSplitThreshold_free;
asn_struct_print_f ULDataSplitThreshold_print;
asn_constr_check_f ULDataSplitThreshold_constraint;
ber_type_decoder_f ULDataSplitThreshold_decode_ber;
der_type_encoder_f ULDataSplitThreshold_encode_der;
xer_type_decoder_f ULDataSplitThreshold_decode_xer;
xer_type_encoder_f ULDataSplitThreshold_encode_xer;
oer_type_decoder_f ULDataSplitThreshold_decode_oer;
oer_type_encoder_f ULDataSplitThreshold_encode_oer;
per_type_decoder_f ULDataSplitThreshold_decode_uper;
per_type_encoder_f ULDataSplitThreshold_encode_uper;
per_type_decoder_f ULDataSplitThreshold_decode_aper;
per_type_encoder_f ULDataSplitThreshold_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ULDataSplitThreshold_H_ */
#include <asn_internal.h>
