/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-PDU-Descriptions"
 * 	found in "E1AP-PDU-Descriptions.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_UnsuccessfulOutcome_H_
#define	_UnsuccessfulOutcome_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ProcedureCode.h"
#include "Criticality.h"
#include <ANY.h>
#include <asn_ioc.h>
#include "Reset.h"
#include "ResetAcknowledge.h"
#include "GNB-CU-UP-E1SetupRequest.h"
#include "GNB-CU-UP-E1SetupResponse.h"
#include "GNB-CU-UP-E1SetupFailure.h"
#include "GNB-CU-CP-E1SetupRequest.h"
#include "GNB-CU-CP-E1SetupResponse.h"
#include "GNB-CU-CP-E1SetupFailure.h"
#include "GNB-CU-UP-ConfigurationUpdate.h"
#include "GNB-CU-UP-ConfigurationUpdateAcknowledge.h"
#include "GNB-CU-UP-ConfigurationUpdateFailure.h"
#include "GNB-CU-CP-ConfigurationUpdate.h"
#include "GNB-CU-CP-ConfigurationUpdateAcknowledge.h"
#include "GNB-CU-CP-ConfigurationUpdateFailure.h"
#include "E1ReleaseRequest.h"
#include "E1ReleaseResponse.h"
#include "BearerContextSetupRequest.h"
#include "BearerContextSetupResponse.h"
#include "BearerContextSetupFailure.h"
#include "BearerContextModificationRequest.h"
#include "BearerContextModificationResponse.h"
#include "BearerContextModificationFailure.h"
#include "BearerContextModificationRequired.h"
#include "BearerContextModificationConfirm.h"
#include "BearerContextReleaseCommand.h"
#include "BearerContextReleaseComplete.h"
#include "ErrorIndication.h"
#include "BearerContextReleaseRequest.h"
#include "BearerContextInactivityNotification.h"
#include "DLDataNotification.h"
#include "ULDataNotification.h"
#include "DataUsageReport.h"
#include "GNB-CU-UP-CounterCheckRequest.h"
#include "GNB-CU-UP-StatusIndication.h"
#include "MRDC-DataUsageReport.h"
#include "PrivateMessage.h"
#include <OPEN_TYPE.h>
#include <constr_CHOICE.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum UnsuccessfulOutcome__value_PR {
	UnsuccessfulOutcome__value_PR_NOTHING,	/* No components present */
	UnsuccessfulOutcome__value_PR_GNB_CU_UP_E1SetupFailure,
	UnsuccessfulOutcome__value_PR_GNB_CU_CP_E1SetupFailure,
	UnsuccessfulOutcome__value_PR_GNB_CU_UP_ConfigurationUpdateFailure,
	UnsuccessfulOutcome__value_PR_GNB_CU_CP_ConfigurationUpdateFailure,
	UnsuccessfulOutcome__value_PR_BearerContextSetupFailure,
	UnsuccessfulOutcome__value_PR_BearerContextModificationFailure
} UnsuccessfulOutcome__value_PR;

/* UnsuccessfulOutcome */
typedef struct UnsuccessfulOutcome {
	ProcedureCode_t	 procedureCode;
	Criticality_t	 criticality;
	struct UnsuccessfulOutcome__value {
		UnsuccessfulOutcome__value_PR present;
		union UnsuccessfulOutcome__value_u {
			GNB_CU_UP_E1SetupFailure_t	 GNB_CU_UP_E1SetupFailure;
			GNB_CU_CP_E1SetupFailure_t	 GNB_CU_CP_E1SetupFailure;
			GNB_CU_UP_ConfigurationUpdateFailure_t	 GNB_CU_UP_ConfigurationUpdateFailure;
			GNB_CU_CP_ConfigurationUpdateFailure_t	 GNB_CU_CP_ConfigurationUpdateFailure;
			BearerContextSetupFailure_t	 BearerContextSetupFailure;
			BearerContextModificationFailure_t	 BearerContextModificationFailure;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UnsuccessfulOutcome_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UnsuccessfulOutcome;
extern asn_SEQUENCE_specifics_t asn_SPC_UnsuccessfulOutcome_specs_1;
extern asn_TYPE_member_t asn_MBR_UnsuccessfulOutcome_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _UnsuccessfulOutcome_H_ */
#include <asn_internal.h>
