/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E1AP-IEs"
 * 	found in "E1AP-IEs.asn"
 * 	`asn1c -pdu=all -fcompound-names -findirect-choice -fno-include-deps`
 */

#ifndef	_UP_Parameters_Item_H_
#define	_UP_Parameters_Item_H_


#include <asn_application.h>

/* Including external dependencies */
#include "UP-TNL-Information.h"
#include "Cell-Group-ID.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ProtocolExtensionContainer;

/* UP-Parameters-Item */
typedef struct UP_Parameters_Item {
	UP_TNL_Information_t	 uP_TNL_Information;
	Cell_Group_ID_t	 cell_Group_ID;
	struct ProtocolExtensionContainer	*iE_Extensions;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} UP_Parameters_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_UP_Parameters_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_UP_Parameters_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_UP_Parameters_Item_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _UP_Parameters_Item_H_ */
#include <asn_internal.h>
