# requirements.yaml
dependencies:
- name: simucucp
  version: "0.0.1"
  repository: http://192.168.56.200:8080
- name: simubcc
  version: "0.0.1"
  repository: http://192.168.56.200:8080
- name: simucim
  version: "0.0.1"
  repository: http://192.168.56.200:8080
- name: simumtcil
  version: "0.0.1"
  repository: http://192.168.56.200:8080
- name: simuctl
  version: "0.0.1"
  repository: http://192.168.56.200:8080  
- name: myetcd
  version: "0.0.1"
  repository: http://192.168.56.200:8080
- name: mynats
  version: "0.0.1"
  repository: http://192.168.56.200:8080
  
