# Default values for btcuup.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
        author: JamesZhang
        testname: CUUP-BBOX-TESTING
        tag: GLOBALTAG

