###############################
#                             #
#  NATS Server Configuration  #
#                             #
###############################
#
nf:
        version: v1
        nfType: bbtest
        nfId: bbtest1


componentSpec:

        deployment:
                replicas: 1
                container: 
                    hub: 192.168.56.200:30500
                    image: simumtcil
                    tag: 1.0
                    env_svc_id: "simumtcil-svc"
                    service: "simumtcil"
