apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats-server
spec:
  selector:
    matchLabels:
      app: mynats # has to match .spec.template.metadata.labels
  serviceName: "mynats"  #声明它属于哪个Headless Service.
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: mynats # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: {{.Values.componentSpec.deployment.container.image}}
        image: {{.Values.global.hub}}/{{.Values.componentSpec.deployment.container.image}}:{{.Values.componentSpec.deployment.container.tag}}
        ports:
        - containerPort: 4222
          name: nats-server
        command: ["./mynats"]
        resources:
          limits:
              cpu: {{ .Values.componentSpec.deployment.container.resources.limits.cpu }}
              memory: {{ .Values.componentSpec.deployment.container.resources.limits.memory }}
          requests:
              cpu: {{ .Values.componentSpec.deployment.container.resources.requests.cpu }}
              memory: {{ .Values.componentSpec.deployment.container.resources.requests.memory }}
