apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats-server
spec:
  selector:
    matchLabels:
      app: mynats # has to match .spec.template.metadata.labels
  serviceName: "mynats"  #声明它属于哪个Headless Service.
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: mynats # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mynats
        image: {{ .Values.global.hub }}/{{.Values.componentSpec.deployment.mynats.image}}:{{.Values.global.tag}}
        ports:
        - containerPort: 4222
          name: nats-server
        command: ["./nats-server"]
